### ISSUE TITLE
header and footers on every page

### ISSUE THREAD

**Issue by ouboub** [kjambunathan/org-mode-ox-odt#100]
Hi

is there a simple way to have a header and/or footer, when exporting to odt?
I presume, that could be done by a ott style, but I love to hear if there are simpler solutions.
regards
UB

**Comment by kjambunathan** [comment]
> Hi
> 
> is there a simple way to have a header and/or footer, when exporting to odt? I presume, that could be done by a ott style, but I love to hear if there are simpler solutions. regards UB

Yes.  You can use custom header and footer by configuring page styles. `.ott` _is_ the simplest.  For an _advanced_ example, see the manual [6.1.5 ‘ODT_MASTER_STYLES’ and ‘ODT_EXTRA_AUTOMATIC_STYLES’](https://kjambunathan.github.io/org-mode-ox-odt/Applying-custom-styles.html#ODT_005fMASTER_005fSTYLES-and-ODT_005fEXTRA_005fAUTOMATIC_005fSTYLES)

**Comment by kjambunathan** [comment]
> is there a simple way to have a header and/or footer, when exporting to odt?
> I presume, that could be done by a ott style, but I love to hear if there are simpler solutions.

`Issues` are for reporting issues.  If you have questions, I suggests that you post them under https://github.com/kjambunathan/org-mode-ox-odt/discussions.

**Comment by kjambunathan** [comment]
> header and footers on every page

This feature is now added as part of [https://github.com/kjambunathan/org-mode-ox-odt/issues/221](https://github.com/kjambunathan/org-mode-ox-odt/issues/221).
