### ISSUE TITLE
Sub figure with corner index

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#109]
A figure with sub figures can be created using list table. For example:

    #+NAME: table
    #+CAPTION: Animals
    #+ATTR_ODT: :category "figure"
    #+ATTR_ODT: :list-table t
    -
    -
        #+NAME: dog
        #+CAPTION: A Dog
        [[./org-mode-unicorn.png]]
    -
        #+NAME: goat
        #+CAPTION: A Goat
        [[./org-mode-unicorn.png]]

Some publication style put the index of sub figure at the corner of the actual image.
We need a way to put that index into the figure frame. Maybe add an index keyword with relative position specification like:

    #+NAME: table
    #+CAPTION: (a) A Dog (b) A Goat
    #+ATTR_ODT: :category "figure"
    #+ATTR_ODT: :list-table t
    -
    -
        #+NAME: dog
        #+ATTR_ODT: :index "(a)" :index-position (0.9, 0.1)
        [[./org-mode-unicorn.png]]
    -
        #+NAME: goat
        #+ATTR_ODT: :index "(b)" :index-position (0.9, 0.1)
        [[./org-mode-unicorn.png]]

**Comment by QiangF** [comment]
Or just plain text without the field property, it can be used and in figure descriptions for other figures as well 

    #+attr_odt: :text "(a)" :text-position (0.9, 0.1)

**Comment by kjambunathan** [comment]
To get this, 

![Screenshot from 2021-10-17 15-47-21](https://user-images.githubusercontent.com/19869864/137622856-2b0e8814-9538-4eb3-9eb2-41e5c2ca6441.png)

use this.

Remember to customize `org-odt-experimental-features`  and enable the  `short-caption-as-label` feature.

```org

#+CAPTION: A Mythical Beast
[[./org-mode-unicorn.png]]

#+CAPTION[Unicorn]: A Mythical Beast
[[./org-mode-unicorn.png]]

#+ATTR_ODT: :style "Text_20_body_20_bold"
#+CAPTION[Unicorn]: A Mythical Beast
[[./org-mode-unicorn.png]]

#+NAME: table
#+CAPTION: Animals
#+ATTR_ODT: :category "figure"
#+ATTR_ODT: :list-table t
-
    -
        #+NAME: dog
        #+CAPTION[([[dog]])]: A Dog
        [[./org-mode-unicorn.png]]
    -
        #+NAME: goat
        #+CAPTION[([[goat]])]: A Goat        
        [[./org-mode-unicorn.png]]





```

**Comment by kjambunathan** [comment]
You can also use imagemagick to pre-process the image to add a text label.  The recipe is based on following source [shell script - add filename as text in the corner of an image file - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/207369/add-filename-as-text-in-the-corner-of-an-image-file?rq=1). There is also an "advanced" snippet at  [Put a Text with transparent Background into a Image - ImageMagick](https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=18273)


1. [[https://unix.stackexchange.com/questions/207369/add-filename-as-text-in-the-corner-of-an-image-file?rq=1][shell script - add filename as text in the corner of an image file - Unix & Linux Stack Exchange]]
  

(The recipe here is a slight variation of the one I already shared with you  in [Add support for image rotation · Issue #96 · kjambunathan/org-mode-ox-odt](https://github.com/kjambunathan/org-mode-ox-odt/issues/96#issuecomment-912934981)


```
#+name: label-image
#+begin_src emacs-lisp :var in-file="" :var label="" :results value raw :exports results
(if (string= in-file "") ""
  (let* ((im-in-options "")
	(im-out-options (list " \"%s\" " label))
	(cmd (list "convert"  in-file "-font"  "Liberation-Sans" "-fill" "black" "-pointsize" "10" "-gravity" "NorthEast" "-annotate" "+10+10" label

		   ))

	(out-file (format "%s-%s.%s" (file-name-sans-extension in-file) (md5 (mapconcat #'identity cmd " ")) (file-name-extension in-file))))

    (apply 'call-process (car cmd)
	   nil standard-output nil (append (cdr cmd) (list out-file)))

    (format "[[file:%s]]" out-file)))
#+end_src

#+RESULTS: label-image

#+NAME: dog
#+CALL: label-image(in-file="org-mode-unicorn.png", label="(a)")

#+NAME: goat
#+CALL: label-image(in-file="org-mode-unicorn.png", label="(b)")


#+NAME: table
#+CAPTION: Animals
#+ATTR_ODT: :category "figure"
#+ATTR_ODT: :list-table t
- 
   -
       #+CAPTION: A Dog
       #+NAME: dog-with-a-label
       #+RESULTS: dog
       [[file:org-mode-unicorn-115f97c5b1816bfe993ab060f5a58966.png]]

   - 
       #+NAME: goat-with-a-label
       #+CAPTION: A Goat
       #+RESULTS: goat
       [[file:org-mode-unicorn-3cdb0a8fb4a8c5403655fce7cffe15a5.png]]
```

**Comment by QiangF** [comment]
There are still two issues:
1. the caption under each sub image is not needed, the description should be in the master figure. Ideally, if sub figure caption is empty, don't put extra space in the figure frame for the sub caption.
2. the corner label should be in front of the image, currently it's hidden by some images, example is attached.


The attached example is export of this snippet:

    #+CAPTION: Animals: (a) dog (b) goat
    #+ATTR_ODT: :category "figure"
    #+ATTR_ODT: :list-table t
    -
        -
            #+NAME: dog
            #+CAPTION[([[dog]])]:
            #+attr_odt: :width 7.1
            [[./org-mode-unicorn.png]]
        -
            #+NAME: goat
            #+CAPTION[([[goat]])]:
            #+attr_odt: :width 7.1
            [[./my-background-image.jpg]]
[test.odt](https://github.com/kjambunathan/org-mode-ox-odt/files/7361523/test.odt)

**Comment by QiangF** [comment]
The subfigure label is better put at the same place of the image frame, and we may have image of different sizes and different resolution.
If we put the label in the image, we can't get consistent label size and position.That's the problem with imagemagic.

**Comment by QiangF** [comment]
No. It's just another stupid requirement of some chinese magzines. Their rationale is that sometimes subpictures have a relationship, for examples an image has an arrow pointing down to another sub image, (a zoo keeper is holding a banana, and the monkey is in the figure below), the arrow is not supposed to point to subcaptions, so it looks better to separate sub-picture with their descriptions. The description is labeled in the main caption. I believe insisting on this kind of trivial thing is wrong, but powerful people can do whatever they want.

To me, you are a very powerful figure :-). Besides the opt out of sub captions, I really think we should put the customised style in the last example the default. The properties combination is too complicated for non xml experts. 

1. OrgImageCaptionFrame

    draw:opacity="0%" 

2. OrgDisplayImage

    style:run-through="background"
    draw:opacity="100%"

**Comment by QiangF** [comment]
I almost got what I want. I am using explicit subfigure label.

            #+CAPTION[(a)]:

The outer frame still has a much bigger height than necessary.

    #+odt_extra_styles: <style:style style:name="MyOrgImageCaptionFrame"
    #+odt_extra_styles:          style:family="graphic"
    #+odt_extra_styles:          style:parent-style-name="OrgImageCaptionFrame">
    #+odt_extra_styles:   <style:graphic-properties draw:opacity="0%" />
    #+odt_extra_styles: </style:style>

    #+odt_extra_styles: <style:style style:name="MyOrgDisplayImage" style:family="graphic"
    #+odt_extra_styles:          style:parent-style-name="OrgDisplayImage">
    #+odt_extra_styles:   <style:graphic-properties style:run-through="background"
    #+odt_extra_styles:                         draw:opacity="100%" />
    #+odt_extra_styles: </style:style>

    #+odt_extra_styles: <style:style style:name="OrgDisplayImageAnchoredToFrame" style:family="graphic"
    #+odt_extra_styles:              style:parent-style-name="OrgDisplayImage">
    #+odt_extra_styles:   <style:graphic-properties style:vertical-pos="middle"
    #+odt_extra_styles:                             style:vertical-rel="frame" style:mirror="none"
    #+odt_extra_styles:                             fo:clip="rect(0cm, 0cm, 0cm, 0cm)" draw:luminance="0%"
    #+odt_extra_styles:                             draw:contrast="0%" draw:red="0%" draw:green="0%"
    #+odt_extra_styles:                             draw:blue="0%" draw:gamma="100%" draw:color-inversion="false"
    #+odt_extra_styles:                             style:run-through="background" draw:image-opacity="100%" draw:color-mode="standard" />
    #+odt_extra_styles: </style:style>

    #+begin_src emacs-lisp :results silent :exports results
    (setcar (cdr (memq :caption-format (assoc ':SUBENTITY: org-odt-caption-and-xref-settings)))
        '(" "))
    #+end_src

    #+NAME: table
    #+CAPTION: Animals
    #+ATTR_ODT: :category "figure"
    #+ATTR_ODT: :list-table t
    -
        -
            #+CAPTION[(a)]:
            #+ATTR_ODT: :width (7 . 7)
            #+ATTR_ODT: :inner-frame (style "OrgDisplayImageAnchoredToFrame" anchor "frame")
            #+ATTR_ODT: :outer-frame (style "MyOrgImageCaptionFrame")
            [[./org-mode-unicorn.png]]
        -
            #+CAPTION[(b)]: A Mythical Beast
            #+ATTR_ODT: :inner-frame (style "OrgDisplayImageAnchoredToFrame" anchor "frame")
            #+ATTR_ODT: :outer-frame (style "MyOrgImageCaptionFrame")
            [[./org-mode-unicorn.png]]

**Comment by QiangF** [comment]
There's only one small problem in the last example. If I add an extra row. The sub label is not continuous, should be like (a) (b) (c) (d).

    #+odt_extra_styles: <style:style style:name="MyOrgImageCaptionFrame"
    #+odt_extra_styles:          style:family="graphic"
    #+odt_extra_styles:          style:parent-style-name="OrgImageCaptionFrame">
    #+odt_extra_styles:   <style:graphic-properties draw:opacity="0%" />
    #+odt_extra_styles: </style:style>

    #+odt_extra_styles: <style:style style:name="MyOrgDisplayImage" style:family="graphic"
    #+odt_extra_styles:          style:parent-style-name="OrgDisplayImage">
    #+odt_extra_styles:   <style:graphic-properties style:run-through="background"
    #+odt_extra_styles:                         draw:opacity="100%" />
    #+odt_extra_styles: </style:style>

    #+odt_extra_styles: <style:style style:name="MyOrgFigureText"
    #+odt_extra_styles:     	 style:family="paragraph"
    #+odt_extra_styles:     	 style:parent-style-name="OrgFigureText">
    #+odt_extra_styles:   <style:paragraph-properties fo:text-align="end"
    #+odt_extra_styles:     			  style:justify-single-word="false" fo:padding="0.499cm"
    #+odt_extra_styles:     			  fo:border="none" />
    #+odt_extra_styles: </style:style>

    #+odt_extra_styles: <style:style style:name="OrgSubFigure" style:family="paragraph"
    #+odt_extra_styles: 	     style:parent-style-name="Figure">
    #+odt_extra_styles:   <style:text-properties text:display="none" />
    #+odt_extra_styles: </style:style>


    #+begin_src emacs-lisp :results silent :exports results
    (setq org-odt-experimental-features
        '(language short-caption-as-label))
    #+end_src

    #+CAPTION: Animals
    #+ATTR_ODT: :category "figure"
    #+ATTR_ODT: :style "GriddedTableNew"
    #+ATTR_ODT: :list-table t
    - 
    - 
        #+NAME: dog
        #+CAPTION[([[dog]])]:
        #+ATTR_ODT: :width 7.1
        #+ATTR_ODT: :outer-frame  (style "MyOrgImageCaptionFrame" extra  "draw:z-index=\"1\"")
        #+ATTR_ODT: :inner-frame  (style "MyOrgDisplayImage" extra  "draw:z-index=\"0\"")
        #+ATTR_ODT: :style "MyOrgFigureText"
        [[./org-mode-unicorn.png]]
    - 
        #+NAME: goat
        #+CAPTION[([[goat]])]:
        #+ATTR_ODT: :width 7.1
        #+ATTR_ODT: :outer-frame  (style "MyOrgImageCaptionFrame" extra  "draw:z-index=\"1\"")
        #+ATTR_ODT: :inner-frame  (style "MyOrgDisplayImage" extra  "draw:z-index=\"0\"")
        #+ATTR_ODT: :style "MyOrgFigureText"
        [[./org-mode-unicorn.png]]
    - 
    - 
        #+NAME: dog
        #+CAPTION[([[dog]])]:
        #+ATTR_ODT: :width 7.1
        #+ATTR_ODT: :outer-frame  (style "MyOrgImageCaptionFrame" extra  "draw:z-index=\"1\"")
        #+ATTR_ODT: :inner-frame  (style "MyOrgDisplayImage" extra  "draw:z-index=\"0\"")
        #+ATTR_ODT: :style "MyOrgFigureText"
        [[./org-mode-unicorn.png]]
    - 
        #+NAME: goat
        #+CAPTION[([[goat]])]:
        #+ATTR_ODT: :width 7.1
        #+ATTR_ODT: :outer-frame  (style "MyOrgImageCaptionFrame" extra  "draw:z-index=\"1\"")
        #+ATTR_ODT: :inner-frame  (style "MyOrgDisplayImage" extra  "draw:z-index=\"0\"")
        #+ATTR_ODT: :style "MyOrgFigureText"
        [[./org-mode-unicorn.png]]
