### ISSUE TITLE
Add a convenience function to attach `:span` attribute to tables

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#114]
Add a convenience function to attach `:span` attribute to tables.

For more info see https://github.com/kjambunathan/org-mode-ox-odt/issues/108.

Cc @ouboub

**Comment by kjambunathan** [comment]
```
If you want to produce the following table

    #+begin_example
    +----------+----------+----------+
    |Column 1  |Column 2  |Column 3  |
    +----------+----------+----------+
    |A         |B                    |
    |          +----------+----------+
    |          |C         |D         |
    +----------+----------+----------+
    |E         |F                    |
    +----------+                     |
    |G         |                     |
    +----------+---------------------+
    |H                               |
    +--------------------------------+
    #+end_example

you will start with the following Org table:

    #+ATTR_ODT: :style "GriddedTable" 
    |----------+----------+----------|
    | Column 1 | Column 2 | Column 3 |
    |----------+----------+----------|
    | A        | B        |          |
    |          | C        | D        |
    | E        | F        |          |
    | G        |          |          |
    | H        |          |          |
    |----------+----------+----------|

When you invoke ~M-x org-odt-table-suggest-spans~ on this table,
you will get the following result

    #+ATTR_ODT: :style "GriddedTable"
    #+ATTR_ODT: :span "@1$3{2:1}"
    #+ATTR_ODT: :span "@2$1{2:1} @2$2{1:2}"
    #+ATTR_ODT: :span "@3$3{4:1}"
    #+ATTR_ODT: :span "@4$2{3:2}"
    #+ATTR_ODT: :span "@5$1{1:3}"
    #+ATTR_ODT: :span "@6$1{1:3}"
    |----------+----------+----------|
    | Column 1 | Column 2 | Column 3 |
    |----------+----------+----------|
    | A        | B        |          |
    |          | C        | D        |
    | E        | F        |          |
    | G        |          |          |
    | H        |          |          |
    |----------+----------+----------|

If you export this table, you will get a table with col and
rowspans but in a "wrong" way. In order to get the desired
spans, you have to do the following "edits"

     #+begin_src diff
     ,#+ATTR_ODT: :style "GriddedTable"
    -#+ATTR_ODT: :span "@1$3{2:1}"
     ,#+ATTR_ODT: :span "@2$1{2:1} @2$2{1:2}"
    -#+ATTR_ODT: :span "@3$3{4:1}"
    -#+ATTR_ODT: :span "@4$2{3:2}"
    -#+ATTR_ODT: :span "@5$1{1:3}"
    +#+ATTR_ODT: :span "@4$2{2:2}"
     ,#+ATTR_ODT: :span "@6$1{1:3}"
     #+end_src

That is,

    - Ignore /~:span~-suggestions/ for first, third and fifth rows
    - Modify the /~:span~-suggestions/ on fifth row
    - Retain other /~:span~-suggestions/ on other rows

and end up with the table like this:

    #+ATTR_ODT: :style "GriddedTable"
    #+ATTR_ODT: :span "@2$1{2:1} @2$2{1:2}"
    #+ATTR_ODT: :span "@4$2{2:2}"
    #+ATTR_ODT: :span "@6$1{1:3}"
    |----------+----------+----------|
    | Column 1 | Column 2 | Column 3 |
    |----------+----------+----------|
    | A        | B        |          |
    |          | C        | D        |
    | E        | F        |          |
    | G        |          |          |
    | H        |          |          |
    |----------+----------+----------|
```

**Comment by ouboub** [comment]
>>> "JK" == Jambunathan K ***@***.***> writes:

> ```
> If you want to produce the following table

>     #+begin_example
>     +----------+----------+----------+
>     |Column 1  |Column 2  |Column 3  |
>     +----------+----------+----------+
>     |A         |B                    |
>     |          +----------+----------+
>     |          |C         |D         |
>     +----------+----------+----------+
>     |E         |F                    |
>     +----------+                     |
>     |G         |                     |
>     +----------+---------------------+
>     |H                               |
>     +--------------------------------+
>     #+end_example


> you will start with the following Org table:

Very nice, I pulled and tried to load the new ox-odt.el(c)
I obtained an error I attach:


Debugger entered--Lisp error: (error "Unknown keyword: :export-block")
  signal(error ("Unknown keyword: :export-block"))
  error("Unknown keyword: %s" :export-block)
  org-export-define-backend(odt ((bold . org-odt-bold) (center-block . org-odt-center-block) (clock . org-odt-clock) (code . org-odt-code) (drawer . org-odt-drawer) (dynamic-block . org-odt-dynamic-block) (entity . org-odt-entity) (example-block . org-odt-example-block) (export-block . org-odt-export-block) (export-snippet . org-odt-export-snippet) (fixed-width . org-odt-fixed-width) (footnote-definition . org-odt-footnote-definition) (footnote-reference . org-odt-footnote-reference) (headline . org-odt-headline) (horizontal-rule . org-odt-horizontal-rule) (inline-src-block . org-odt-inline-src-block) (inlinetask . org-odt-inlinetask) (italic . org-odt-italic) (item . org-odt-item) (keyword . org-odt-keyword) (latex-environment . org-odt-latex-environment) (latex-fragment . org-odt-latex-fragment) (line-break . org-odt-line-break) (link . org-odt-link) (node-property . org-odt-node-property) (paragraph . org-odt-paragraph) (plain-list . org-odt-plain-list) (plain-text . org-odt-plain-text) (planning . org-odt-planning) (property-drawer . org-odt-property-drawer) (quote-block . org-odt-quote-block) (radio-target . org-odt-radio-target) (section . org-odt-section) (special-block . org-odt-special-block) (src-block . org-odt-src-block) (statistics-cookie . org-odt-statistics-cookie) (strike-through . org-odt-strike-through) (subscript . org-odt-subscript) (superscript . org-odt-superscript) (table . org-odt-table) (table-cell . org-odt-table-cell) (table-row . org-odt-table-row) (target . org-odt-target) (template . org-odt-template) (timestamp . org-odt-timestamp) (underline . org-odt-underline) (verbatim . org-odt-verbatim) (verse-block . org-odt-verse-block)) :export-block "ODT" :filters-alist ((:filter-parse-tree org-odt--translate-latex-fragments org-odt--translate-description-lists org-odt--translate-list-tables)) :menu-entry (111 "Export to ODT" ((111 "As ODT file" org-odt-export-to-odt) (79 "As ODT file and open" (lambda (a s v b) (if a (org-odt-export-to-odt t s v) (org-open-file (org-odt-export-to-odt nil s v) 'system)))))) :options-alist ((:odt-styles-file "ODT_STYLES_FILE" nil nil t) (:odt-content-template-file nil nil org-odt-content-template-file) (:odt-display-outline-level nil nil org-odt-display-outline-level) (:odt-fontify-srcblocks nil nil org-odt-fontify-srcblocks) (:odt-format-drawer-function nil nil org-odt-format-drawer-function) (:odt-format-headline-function nil nil org-odt-format-headline-function) (:odt-format-inlinetask-function nil nil org-odt-format-inlinetask-function) (:odt-inline-formula-rules nil nil org-odt-inline-formula-rules) (:odt-inline-image-rules nil nil org-odt-inline-image-rules) (:odt-pixels-per-inch nil nil org-odt-pixels-per-inch) (:odt-styles-file nil nil org-odt-styles-file) (:odt-table-styles nil nil org-odt-table-styles) (:odt-use-date-fields nil nil org-odt-use-date-fields) (:with-latex nil "tex" org-odt-with-latex)))
  eval-buffer(#<buffer  *load*> nil "/home/oub/ALLES/src/org-mode-ox-odt-hg/lisp/ox-odt..." nil t)  ; Reading at buffer position 4384
  load-with-code-conversion("/home/oub/ALLES/src/org-mode-ox-odt-hg/lisp/ox-odt..." "/home/oub/ALLES/src/org-mode-ox-odt-hg/lisp/ox-odt..." nil nil)
  load("/home/oub/ALLES/src/org-mode-ox-odt-hg/lisp/ox-odt..." nil nil t)
  load-file("~/ALLES/src/org-mode-ox-odt-hg/lisp/ox-odt.el")
  funcall-interactively(load-file "~/ALLES/src/org-mode-ox-odt-hg/lisp/ox-odt.el")
  call-interactively(load-file nil nil)
  command-execute(load-file)

**Comment by kjambunathan** [comment]
> Debugger entered--Lisp error: (error "Unknown keyword: :export-block") 
> signal(error ("Unknown keyword: :export-block")) error("Unknown keyword: %s" :export-block) 

> org-export-define-backend(

Well, the `:export-block" is commented out in my repo.

https://github.com/kjambunathan/org-mode-ox-odt/blob/424c8f54fccbf9121dcd1abf2f43efae2e01aefa/lisp/ox-odt.el#L94

Do you have some local changes at your end?  May be you added `:export-block` for some purpose ...

When you load a source file, as opposed to a compiled file, you get better clues about the call sequence on stack.  (In the present case, the stack trace is pretty straightforward, so the difference doesn't matter)

**Comment by kjambunathan** [comment]
I think I did a last minute renaming which broke successful compilation.  The result is no would fresh `.elc` file would have been introduced in the first place.  So, `*.elc` that is actually getting loaded is a old one possibly from the dinosaur era.

Sorry about this problem.

Please pull again and try ...

**Comment by ouboub** [comment]
>>> "JK" == Jambunathan K ***@***.***> writes:

> I think I did a last minute renaming which broke successful
> compilation. The result is no would fresh `.elc` file would have been
> introduced in the first place. So, `*.elc` that is actually getting
> loaded is a old one possibly from the dinosaur era.

> Sorry about this problem.

> Please pull again and try ...

I did, it worked! Thanks.

Two comments:



    1. Also I load  (load-file
       "/home/oub/ALLES/src/org-mode-ox-odt-hg/lisp/ox-odt.elc")
       locate-library od-odt
        Shows me 
        Library is file ~/emacs/site-lisp/packages/org/ox-odt.elc
        which is curious since later 
        (org-odt-table-suggest-spans)
        Is found and used, and that function is only part of your library.

    2. The function works nice, but it is not clear to me, which
    suggestions, in the general case, I have to accept and which not.
