### ISSUE TITLE
Provide some keywords to set ODT metadata.

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#117]
Cc @hwiorn

### Discussed in https://github.com/kjambunathan/org-mode-ox-odt/discussions/113

<div type='discussions-op-text'>

<sup>Originally posted by **hwiorn** October 27, 2021</sup>
Currently, exporter doesn't make general and custom properties of an ODT file. I can't set any general fields and add any custom fields inside an ODT document using ox-org only. I can define user custom fields in `#+ODT_MASTER_STYLES`, But I can't set them to metadata.

![image](https://user-images.githubusercontent.com/1394254/139083581-49bee0ba-8c06-4f41-b5dc-0d2911358d01.png)

![image](https://user-images.githubusercontent.com/1394254/139084059-107a1bdd-0ce4-44c9-a391-db1717385f8e.png)

I checked `ox-odt.el`, and I found it checks only [some keywords like title, author, description, etc](https://github.com/kjambunathan/org-mode-ox-odt/blob/master/lisp/ox-odt.el#L2874-L2946
).

I think that ox-odt needs to provide a custom property which can be overridden or `#+ODT_EXTRA_META` is a suitable solution. 

```org
#+property: created <2021-10-26 Tue>
#+property: modified <2021-10-27 Wed>
```
or
```org
#+ODT_GENERAL_META: modified <2021-10-26 Tue>
#+ODT_CUSTOM_META: Version 1.1.1
#+ODT_CUSTOM_META: Document-Id A-21-10-25-REQ-11
```
or
```org
#+ODT_EXTRA_META: <dc:date>2021-10-27T17:18:01.220502029</dc:date><meta:editing-duration>PT6M31S</meta:editing-duration><meta:editing-cycles>6</meta:editing-cycles><meta:generator>LibreOffice/7.2.2.2$Linux_X86_64 LibreOffice_project/20$Build-2</meta:generator>
```
</div>

**Comment by kjambunathan** [comment]
@PierreTechoueyres 

I use the following `yasnippet` rule to insert custom fields

```
# -*- mode: snippet -*-
# contributor : kjn
# group: kjn
# key: odtfield
# name: odtfield
# binding: <ENTER KEY BINDING>
# --

#+ODT_DOCUMENT_PROPERTIES: ${1:$(upcase yas-text)}
#+${1:$(upcase yas-text)}: $1

#+MACRO: ${1:$(capitalize yas-text)} {{{keyword-to-documentproperty(${1:$(upcase yas-text)})}}}

The document's ~${1:$(upcase yas-text)}~ is {{{${1:$(capitalize yas-text)}}}}
```

If you trigger the above snippet, and type in `version` at  you keyboard, you will get 

```
#+ODT_DOCUMENT_PROPERTIES: VERSION
#+VERSION: version

#+MACRO: Version {{{keyword-to-documentproperty(VERSION)}}}

The document's ~VERSION~ is {{{Version}}}
```
which you can export.  

The advantage is you can invent new custom fields, without having to made any changes to `ox-odt`.

In the `yasnippet`, you may find it convenient to replace `upcase` with `capitalize`.

If you have any feature requests or suggestions, let me know.

**Comment by PierreTechoueyres** [comment]
@kjambunathan Yes !!!! That works !!!
One nitpick : actually the keywords are enforced to be in uppercase, but on LibreOffice I found some that  have mixed case and also spaces. Have you any tips on them ?
For example one I added is "Vérifié par" (picked from the list in LO) is stored in meta.xml as
`<meta:user-defined meta:name="Vérifié par">Moi</meta:user-defined>`

**Comment by kjambunathan** [comment]
> For example one I added is "Vérifié par" (picked from the list in LO) is stored in meta.xml as
> `<meta:user-defined meta:name="Vérifié par">Moi</meta:user-defined>`



This is fixed as part of commmit https://github.com/kjambunathan/org-mode-ox-odt/commit/2fe81a4e51beb21ea0524adb64d3b044596eb79e.  You can see the commit message for more information.

The recipe for your requirement will be along the lines of 

```
#+ODT_DOCUMENT_PROPERTIES: DOC_VERIFIED_BY
#+DOC_VERIFIED_BY: "Pierre Techoueyres"  :name "Vérifié par"

#+MACRO: Doc_Verified_By {{{keyword-to-documentproperty(Doc_Verified_By)}}}

The document's ~DOC_VERIFIED_BY~ is {{{Doc_Verified_By}}}
```

Keyword's value as a `Emacs Lisp` `plist` without the surround `(` and `)`.  This means that the `string` values have to be double-quoted.  (Previously the meta-data keywords didn't allow additional properties. and was supporting arbitrary text)  In a way, this changes keyword syntax in a  "backward-incompatible" way.  

Feedback welcome.



-----

To produce this,

![Document Properties-1](https://github.com/kjambunathan/org-mode-ox-odt/assets/19869864/178199e8-4a24-499a-9f50-b9848b05ae06)

![Document Properties-2](https://github.com/kjambunathan/org-mode-ox-odt/assets/19869864/efd05204-f177-4a38-a21a-b5d285a20987)

do this

```
* =Custom Property= without a =:name= or a =:type=

# Define the KEYWORDS that are meant as metadata

#+UBUNTU_RELEASE_NAME: "Mantic Minotaur"
#+UBUNTU_RELEASE_NUMBER: 23.10
#+UBUNTU_IS_EOL: nil
#+UBUNTU_RELEASE_DATE: "<2023-10-12 Thu>"

# Make the above KEYWORS exportable as OpenDocument metadata

#+ODT_DOCUMENT_PROPERTIES: UBUNTU_RELEASE_NAME
#+ODT_DOCUMENT_PROPERTIES: UBUNTU_RELEASE_NUMBER
#+ODT_DOCUMENT_PROPERTIES: UBUNTU_IS_EOL
#+ODT_DOCUMENT_PROPERTIES: UBUNTU_RELEASE_DATE

# Define a convenience MACRO to embed the above KEYWORDS

#+MACRO: Ubuntu_Release_Name {{{keyword-to-documentproperty(UBUNTU_RELEASE_NAME)}}}
#+MACRO: Ubuntu_Release_Number {{{keyword-to-documentproperty(UBUNTU_RELEASE_NUMBER)}}}
#+MACRO: Ubuntu_Is_EOL {{{keyword-to-documentproperty(UBUNTU_IS_EOL)}}}
#+MACRO: Ubuntu_Release_Date {{{keyword-to-documentproperty(UBUNTU_RELEASE_DATE)}}}

| In-buffer keyword       | Value                       | Type      |
|-------------------------+-----------------------------+-----------|
| ~UBUNTU_RELEASE_NAME~   | {{{Ubuntu_Release_Name}}}   | /Text/    |
| ~UBUNTU_RELEASE_NUMBER~ | {{{Ubuntu_Release_Number}}} | /Number/  |
| ~UBUNTU_IS_EOL~         | {{{Ubuntu_Is_EOL}}}         | /Boolean/ |
| ~UBUNTU_RELEASE_DATE~   | {{{Ubuntu_Release_Date}}}   | /Date/    |

* =Custom Property= that specify a type

# Define the KEYWORDS that are meant as metadata

#+DEBIAN_RELEASE_NAME: "Bookworm" :name "Debian Release Name"
#+DEBIAN_VERSION_NUMBER: 12 :name "Debian Version Number"
#+DEBIAN_IS_ALREADY_RELEASED: t :name "Is Debian Version Already Released?"
#+DEBIAN_RELEASE_DATE: "<2023-06-10 Sat>" :name "Debian Release Date" :type date

# Make the above KEYWORS exportable

#+ODT_DOCUMENT_PROPERTIES: DEBIAN_RELEASE_NAME
#+ODT_DOCUMENT_PROPERTIES: DEBIAN_VERSION_NUMBER
#+ODT_DOCUMENT_PROPERTIES: DEBIAN_IS_ALREADY_RELEASED
#+ODT_DOCUMENT_PROPERTIES: DEBIAN_RELEASE_DATE

# Define a convenience MACRO to embed the above KEYWORDS

#+MACRO: Debian_Release_Name {{{keyword-to-documentproperty(DEBIAN_RELEASE_NAME)}}}
#+MACRO: Debian_Version_Number {{{keyword-to-documentproperty(DEBIAN_VERSION_NUMBER)}}}
#+MACRO: Debian_Is_Already_Released {{{keyword-to-documentproperty(DEBIAN_IS_ALREADY_RELEASED)}}}
#+MACRO: Debian_Release_Date {{{keyword-to-documentproperty(DEBIAN_RELEASE_DATE)}}}

| In-buffer Keyword            | Value                            | Type      |
|------------------------------+----------------------------------+-----------|
| ~DEBIAN_RELEASE_NAME~        | {{{Debian_Release_Name}}}        | /Text/    |
| ~DEBIAN_VERSION_NUMBER~      | {{{Debian_Version_Number}}}      | /Number/  |
| ~DEBIAN_RELEASE_DATE~        | {{{Debian_Release_Date}}}        | /Date/    |
| ~DEBIAN_IS_ALREADY_RELEASED~ | {{{Debian_Is_Already_Released}}} | /Boolean/ |
```

**Comment by PierreTechoueyres** [comment]
Whaou !
Many thanks, I'll check this in the following days to improve my templates.  You've made an incredible work.
