### ISSUE TITLE
Add support for column alignment in list and transcluded tables

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#121]
## Add support for column alignment in list and transcluded tables

Support of cell alignments was removed as part of https://github.com/kjambunathan/org-mode-ox-odt/issues/25.  Provide a convenient way to set the alignments.

Cc @QiangF

**Comment by kjambunathan** [comment]
To get this,

![Screenshot from 2021-10-31 16-02-50](https://user-images.githubusercontent.com/19869864/139578562-0e272cc9-7830-48ad-a8e5-f2717dfd8b12.png)

do this

```org
#+begin_src emacs-lisp :exports results :results silent
(add-to-list 'org-odt-experimental-features 'transclude-sole-footnote-references-in-a-table)
#+end_src

#+CAPTION: Regular Table
#+ATTR_ODT: :col-cookies  "|  <c>  |       | <l3>  | <c3>  | <2>   |  <r3> | <>    |"
| <l1>  |  <r1> | <r2>  | <r4>  | <l8>  | <c16> | <l1>  |
| Col-1 | Col-2 | Col-3 | Col-4 | Col-5 | Col-6 | Col-7 |
|-------+-------+-------+-------+-------+-------+-------|
|  C1   |    L1 | L3    |  C3   | L2    |    R3 | L1    |


#+CAPTION: List Table
#+ATTR_ODT: :col-cookies  "|  <c>  |       | <l3>  | <c3>  | <2>   |  <r3> | <>    |"
#+ATTR_ODT: :list-table t
- 
  - Co1-1
  - Col-2
  - Col-3
  - Col-4
  - Col-5
  - Col-6
  - Co-7
- ----------------
  - C1
  - L1
  - L3
  - C3
  - L2
  - R3
  - L1

#+CAPTION: Transcluded Table
#+ATTR_ODT: :col-cookies  "|  <c>  |       | <l3>  | <c3>  | <2>   |  <r3> | <>     |"
| Col-1 | Col-2 | Col-3 | Col-4 | Col-5 | Col-6 | Col-7  |
|-------+-------+-------+-------+-------+-------+--------|
|  C1   | L1    | L3    |  C3   | L2    |    R3 | [fn:1] |

[fn:1]

L1


```

**Comment by QiangF** [comment]
It's looks good to use "#+ATTR_ODT: :col-cookies" for list-table, but for regular or transcluded table, it is more preferable to just use the first coolie line of the original table, because that sits right above the column and easier to associate with the column content.
So instead of this:

    #+CAPTION: Regular Table
    #+ATTR_ODT: :col-cookies  "|  <c>  |       | <l3>  | <c3>  | <2>   |  <r3> | <>    |"
    | <l1> | <r1> | <r2> | <r4> | <l8> | <c16> | <l1> |
    | 1    |    2 |    3 |    4 | 5    |   6   | 7    |
    |------+------+------+------+------+-------+------|
    | C1   |   L1 |   L3 |   C3 | L2   |  R3   | L1   |

make a value "table-first-line" for col-cookies to instruct it to get the cookie from the first line, like:

    #+CAPTION: Regular Table
    #+ATTR_ODT: :col-cookies  "table-first-line"
    | <l1> | <r1> | <r2> | <r4> | <l8> | <c16> | <l1> |
    | 1    |    2 |    3 |    4 | 5    |   6   | 7    |
    |------+------+------+------+------+-------+------|
    | C1   |   L1 |   L3 |   C3 | L2   |  R3   | L1   |


    #+CAPTION: Transcluded Table
    #+ATTR_ODT: :col-cookies  "table-first-line"
    |  1 |  2 |  3 |  4 |  5 |  6 |      7 |
    |----+----+----+----+----+----+--------|
    | C1 | L1 | L3 | C3 | L2 | R3 | [fn:1] |

    [fn:1]

**Comment by QiangF** [comment]
Or make the sytax more compact, like:

    #+ATTR_ODT: :col-cookies  "1c2,3l3,4c3,5l2,6r3"

and corresponding meaning:

    center colum 1 with width of 2, left align column 3 with width of 3...
