### ISSUE TITLE
Document with a series of images doesn't import well in to Google Documents

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#137]
### Document produced by ODT exporter

[3images.odt](https://github.com/kjambunathan/org-mode-ox-odt/files/7594825/3images.odt)

### How it looks in LibreOffice

![Screenshot from 2021-11-24 15-52-21](https://user-images.githubusercontent.com/19869864/143220777-c725d583-7896-46e8-bdac-31dc9d9011ca.png)

### How it looks in Google Docs

![Screenshot from 2021-11-24 15-53-03](https://user-images.githubusercontent.com/19869864/143220820-d7643d91-d07d-41eb-bff9-ea0ee63494f1.png)

### Org snippet to produce the above document

```
An inline image [[./org-mode-unicorn.png]]

[[./org-mode-unicorn.png]]

[[./org-mode-unicorn.png]]

[[./org-mode-unicorn.png]]

```

**Comment by QiangF** [comment]
Maybe you can try the docx format.

**Comment by kjambunathan** [comment]
> Maybe you can try the docx format.

Not for this issue ... But for this issue (https://github.com/kjambunathan/org-mode-ox-odt/issues/136#issuecomment-977703497) much of the time involved having LibreOffice export to all the different doc / docx formats and see if Google Docs will render it as LibreOffice does. Unfortunately, none of those other formats worked.  I don't have access to Windows machine or Microsoft Word.  I wonder what would happen if LibreOffice ODT is opened in Microsoft Word, and fed further in to Google Docs.

By the time, I noticed this issue, I have already gone too further down one rabbit hole, and I was hesitant  to go down the other.  Next time, I am going to rely on importing to Google Docs, I will be much more careful ...

**Comment by kjambunathan** [comment]
### An uncpationed image is "overflows" a table ....

![Screenshot from 2021-12-20 06-22-52](https://user-images.githubusercontent.com/19869864/146697511-3a19a7bb-890a-4492-a4e4-a08b981592ee.png)


### Test snippet

```
#+begin_src emacs-lisp :exports results :results none
(add-to-list 'org-odt-experimental-features 'transclude-sole-footnote-references-in-a-table)
#+end_src

| [fn:1] | [fn:2] |

Some more text.

[fn:1] [[./org-mode-unicorn.png]]

[fn:2] [[./org-mode-unicorn.png]]

# Local Variables:
# org-export-use-babel: t
# End:

```

**Comment by kjambunathan** [comment]
Fixes issues with LibreOffice but introduces one another issue with Google Docs ...

### Results with LibreOffice

![Screenshot from 2021-12-20 07-03-56](https://user-images.githubusercontent.com/19869864/146699617-d8010750-7d8a-4201-9043-77731bdb692d.png)

### Results with Google Docs 

![Screenshot from 2021-12-20 07-01-02](https://user-images.githubusercontent.com/19869864/146699685-035b0a54-2eba-4159-8ffc-7b7d780fa237.png)

![Screenshot from 2021-12-20 07-01-53](https://user-images.githubusercontent.com/19869864/146699728-4fef5119-05f1-4fdb-9275-11de5fcd5231.png)

### Results  with Google Drive Preview

![Screenshot from 2021-12-20 06-49-47](https://user-images.githubusercontent.com/19869864/146699751-b28faa85-0754-4672-adef-dbc69003ecb5.png)

### Test Snippet

```
#+begin_src emacs-lisp :exports results :results none
(add-to-list 'org-odt-experimental-features 'transclude-sole-footnote-references-in-a-table)
#+end_src

An inline image [[./org-mode-unicorn.png]]

[[./org-mode-unicorn.png]]

[[./org-mode-unicorn.png]]

[[./org-mode-unicorn.png]]

#+ATTR_ODT: :style "GriddedTable"
| [fn:1] | [fn:2] |

Some more text.

[fn:1] [[./org-mode-unicorn.png]]

[fn:2] [[./org-mode-unicorn.png]]

# Local Variables:
# org-export-use-babel: t
# End:

```

**Comment by kjambunathan** [comment]
May be it is not a good idea to support Google Docs ... I think the results will be better if the image gets anchored "as-char" instead of "paragraph".  Again this is just a guess ...
