### ISSUE TITLE
Feature request: fit image width to column width

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#14]
I am using your org-mode, in list-table, if I resize the table, the image size
doesn't change. How to make images inside a table column fit the width of the
table column?

```
    #+ATTR_ODT: :style "GriddedTable"
    #+ATTR_ODT: :rel-width 5 
    #+ATTR_ODT: :list-table t
    -
       - [[./org-mode-unicorn.png]]
       - [[./org-mode-unicorn.png]]
```

**Comment by kjambunathan** [comment]
> I am using your org-mode, in list-table, if I resize the table, the image size
doesn't change. How to make images inside a table column fit the width of the
table column?

```
    #+ATTR_ODT: :style "GriddedTable"
    #+ATTR_ODT: :rel-width 5 
    #+ATTR_ODT: :list-table t
    -
       - [[./org-mode-unicorn.png]]
       - [[./org-mode-unicorn.png]]
```

_I believe you have figured out what you need to do_  

For the sake of completion,  use the following snippet together with `org-odt-transform-processes`'s  `"Optimize Column Width of all Tables"`.
```
#+ATTR_ODT: :list-table t
- 
  - 
     #+BEGIN_CENTER
     #+ATTR_ODT: :anchor "as-char"
     [[./org-mode-unicorn.png]]
     #+END_CENTER

  - 
    #+BEGIN_CENTER
    #+ATTR_ODT: :anchor "as-char"
    [[./org-mode-unicorn.png]]
    #+END_CENTER
```
