### ISSUE TITLE
Commit 715efc9 breaks multi-column section layout

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#150]
The picture shows two format errors:
1. the image layout is messed up
2. the formula and its index's alignment is terrible

![img_2021_12_09__09_48_55](https://user-images.githubusercontent.com/8192731/145319927-fcfc6cbb-8955-4722-b25d-b71f850db39a.png)
[snippet.odt](https://github.com/kjambunathan/org-mode-ox-odt/files/7681624/snippet.odt)

Other related files are in the zip file.
[gap.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/7681628/gap.zip)

**Comment by kjambunathan** [comment]
The picture shows two format errors:

   1.  the image layout is messed up
    2. the formula and its index's alignment is terrible


See if the https://github.com/kjambunathan/org-mode-ox-odt/commit/39c66cd2fcb8f33cfa2c66b945e90736b9732eb0 fixes (2).  Btw, the `org` file in [gap.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/7681628/gap.zip)   doesn't have any equation, even though the screenshot says there is one.

Regarding (1) ... could you please update the `org` file, and pass it along to me.

**Comment by kjambunathan** [comment]
> #+odt_styles_file: ./text_cn.xml

You need to update the styles file.  This is because I have introduced new styles. 

> #+odt_content_template_file: ./OrgOdtContentTemplate.xml

Comment the above line, and export.   It is a good way to find out if it is an issue with your templates file lagging behind.  I haven't update content template yet.  But I have a big change in my workarea relating to vertical alignment of table cells.  And these table changes will touch the content template file ...  Just a heads up.

**Comment by QiangF** [comment]
(1) seems to have been fixed. Maybe the equation should be centered, it looks better that way:
https://github.com/kjambunathan/org-mode-ox-odt/discussions/129

**Comment by QiangF** [comment]
The equation snippet is

    #+label: eq:2
    \begin{equation*}
    1+1=2
    \end{equation*}

I use starmath, code below is from your post :

    (setq org-latex-to-mathml-convert-command "java -jar %j -unicode -force -df %o %I"
            org-latex-to-mathml-jar-file "~/.dotfiles/emacs/org/mathtoweb.jar")

    (defun org-odt--extract-starmath-from-latex-frag (&optional latex-frag)
        (let* ((latex-frag (or latex-frag (buffer-substring-no-properties (region-beginning) (region-end))))
                (latex-frag (org-trim latex-frag)))
        (cond
            ((and (string-prefix-p "$" latex-frag)
                (string-suffix-p "$" latex-frag))
            (substring latex-frag 2 -2))
            ((and (string-prefix-p "\\[" latex-frag)
                (string-suffix-p "\\]" latex-frag))
            (substring latex-frag 2 -2))
            ((and (string-prefix-p "\\(" latex-frag)
                (string-suffix-p "\\)" latex-frag))
            (substring latex-frag 2 -2))
            ((string-match (rx-to-string '(seq "\\begin{" (group (one-or-more (any "0-9A-Za-z" "*"))) "}")) latex-frag)
            (let* ((prefix (match-string 1 latex-frag))
                    (preamble (format "\\begin{%s}" prefix))
                    (postamble (format "\\end{%s}" prefix)))
                (when (string-suffix-p postamble latex-frag)
                (substring latex-frag (length preamble) (- (length postamble))))))
            (t (error "Couldn't match latex-frag: %S" latex-frag)))))

    (defun org-create-math-formula-from-starmath (latex-frag &optional mathml-file)
        "Convert LATEX-FRAG to MathML and store it in MATHML-FILE.
    LATEX-FRAG here is in fact _not_ a latex fragment as such, but a
    startmath formula delimited using .  If the conversion is
    successful, return the portion between \"<math...> </math>\"
    elements otherwise return nil.  When MATHML-FILE is specified,
    write the results in to that file.  When invoked as an
    interactive command, prompt for LATEX-FRAG, with initial value
    set to the current active region and echo the results for user
    inspection."
        (interactive (list (let ((frag (when (org-region-active-p)
                                        (buffer-substring-no-properties
                                        (region-beginning) (region-end)))))
                            (read-string "LaTeX Fragment: " frag nil frag))))
        (let* ((starmath  (org-odt--extract-starmath-from-latex-frag latex-frag))
                (dummy (message "\n->%s<-\n\n-->%s<--\n" latex-frag starmath))

                (math
                (format "
    <math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\">
    <semantics>
    <annotation encoding=\"StarMath 5.0\">%s</annotation>
    </semantics>
    </math>

    "
                        starmath))
                (mathml
                (format "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n%s\n"
                        math)))
        (when mathml-file
            (message "Wrote %s" mathml-file)
            (write-region mathml nil mathml-file))
        math))

    ;; starmath fragment has to be enclosed in {}
    (advice-add 'org-create-math-formula :override 'org-create-math-formula-from-starmath))
