### ISSUE TITLE
insert arbitrary page breaks

### ISSUE THREAD

**Issue by mooseyboots** [kjambunathan/org-mode-ox-odt#157]
i understand there have been other discussions of pagebreaks, but i'm not clear still on whether this is possible.

what i would like to do is something like inserting `^L` and when i export, it is the equivalent of if i had run CTRL-RETURN in LO, or Insert > Page Break.

the idea being to have this be completely independent of any headings, tables, sections, etc. the user should be able to insert page breaks arbitrarily, independent of content, where they want to.

**Comment by mooseyboots** [comment]
oops, looks like i missed 

```
#+ATTR_ODT: :style "OrgPageBreakDefault"
#+PAGEBREAK:
```

**Comment by kjambunathan** [comment]
(There have been some changes to page break feature.  What you are citing
is a old format, and it may not work)

If you are using the newest revision,  use the example file here as
starting point

https://raw.githubusercontent.com/kjambunathan/org-mode-ox-odt/master/testing/examples/odt/pagebreak.org
