### ISSUE TITLE
Allow for post-processing an exported document, by a LibreOffice macro

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#16]
#### Allow for post-processing an exported document, by a LibreOffice macro

Currently the exporter _fills out_  the 'Table Of Contents' manually.  Once, macro execution is supported, the exporter could fill out just a template for 'Table of Listings', Table of Figures' etc. and let the macro equivalent for `Tools->Update->Update All` do the actual  job of filling out the template.

To  run a  LibreOffice macro (using `soffice` command),  consult the earlier experiment: [Re: [O] ODT image export](https://lists.gnu.org/archive/html/emacs-orgmode/2011-09/msg00538.html)

**Comment by QiangF** [comment]
One very useful macro that optimise table  cell width

    Sub OptimzeColumnWidth
    Dim s As String
    Dim i As Long
    Dim oTables
    Dim oTable
    Dim oCell
    oTables = ThisComponent.getTextTables()
    If NOT oTables.hasElements() Then Exit Sub
    For i = 0 To oTables.getCount() - 1
        oTable = oTables.getByIndex(i)
        ThisComponent.getCurrentController().select(oTable)
        oFrame = ThisComponent.CurrentController.Frame
        oDispHelper = createUnoService("com.sun.star.frame.DispatchHelper")
        oDispHelper.executeDispatch(oFrame, ".uno:SelectTable", "", 0, Array())
        oDispHelper.executeDispatch(oFrame, ".uno:SetOptimalColumnWidth", "", 0, Array()) 
    Next
    End Sub

If the macro is saved in a library within the document (not in my macros but in
myfile.odt in the macro hierarchy), it can be run with:

    libreoffice "macro://./Standard.FormatPandocOdt.OptimzeColumnWidth" myfile.odt

With security options (middle), libroffice open and ask if you want to activate
the macros within the document.

But I don't know how to save the macro in the odt file.

**Comment by kjambunathan** [comment]
> Allow for post-processing an exported document, by a LibreOffice macro

Done.

> One very useful macro that optimise table cell width

I have checked in `OrgModeUtilities.oxt`, a LibreOffice extension, for collecting macros of interest to ODT exporter.  You can install that extension and add your macro to it.

**Comment by QiangF** [comment]
This is not working for me. I have added my column width optimization macro to the orgmodutilities but it didn 't run with the following setting.

    (add-to-list 'org-odt-transform-processes '("optimise table column width" "soffice" "--norestore" "--invisible" "--headless" "macro:///OrgMode.Utilities.OptimizeColumnWidth(%I)"))

However, the macro can be run in libreoffice 5.2.5.
My test setting for emacs is :

    (setq debug-on-error t)
    (setq load-prefer-newer t)
    (require 'package)
    (require 'cl)
    (setq load-path (remove-if (lambda (x) (string-match-p "org$" x)) load-path))
    (cl-pushnew "~/.emacs.d/org-mode-ox-odt/lisp/" load-path)
    (cl-pushnew "~/.emacs.d/org-mode-ox-odt/contrib/lisp/" load-path)

    (package-initialize)
    (require 'use-package)

    (use-package org
    :load-path "~/.emacs.d/org-mode-ox-odt/lisp/"
    )
    (use-package org-plus-contrib
    :load-path "~/.emacs.d/org-mode-ox-odt/contrib/lisp/"
    )
    (use-package ox-odt
        :load-path "~/.emacs.d/org-mode-ox-odt/lisp/"
        :config
        (add-to-list 'org-odt-transform-processes '("optimise table column width" "soffice" "--norestore" "--invisible" "--headless" "macro:///OrgMode.Utilities.OptimizeColumnWidth(%I)"))
        (require 'ox)
        (require 'ox-odt)
        (setq org-export-odt-convert-processes
            "/usr/bin/soffice --headless --convert-to %f%x --outdir %d %i"
            org-odt-prettify-xml t
            org-odt-schema-dir "~/.dotfiles/org/schema"
            ;; org-odt-styles-dir "~/.dotfiles/org/styles"
            org-odt-styles-dir "~/.emacs.d/org-mode-ox-odt/etc/styles"
            org-export-odt-preferred-output-format "odt"
            org-export-backends (quote (ascii html latex odt)))
    )

    (use-package ox-jabref
        :load-path "~/.emacs.d/org-mode-ox-odt/contrib/lisp/"
        :config
            (setq org-jabref-command '("java" "-jar" "/home/q/.emacs.d/JabRef-2.9.2.jar" "-n" "true"))
    )

**Comment by kjambunathan** [comment]
> This is not working for me. I have added my column width optimization macro to the orgmodutilities but it didn 't run 

There is a problem with your macro (when run as a script): It doesn't  save the document once the tables are optimized.  

I have included a working version of your macro with https://github.com/kjambunathan/org-mode-ox-odt/blob/master/contrib/odt/OrgModeUtilities.oxt.  Please re-install this LibreOffice Extension and customize the variable `org-odt-transform-processes` to include the new macro.

**Comment by kjambunathan** [comment]
> I have included a working version of your macro within https://github.com/kjambunathan/org-mode-ox-odt/blob/master/contrib/odt/OrgModeUtilities.oxt. Please re-install this LibreOffice Extension and customize the variable org-odt-transform-processes to include the new macro.

You _may_ use the following snippet to exercise the two utility transformers.

    #+TOC: tables

    \\

    #+CAPTION: Example Table
    | EST | New York | -5:00 |
    | IST | Madras   | +5:30 |
    | AST | Bahrain  |       |
