### ISSUE TITLE
Extra space between caption category and counter

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#162]
Chinese sentence doesn't need space to seperate word. So figure category word and the figure counter should be a single entity without space between.
I have set explicitly for no space between category and counter.

    (setq org-odt-caption-and-xref-settings
          '((:FIGURE:
              :caption-position below :caption-format
              (category counter ": " caption)
              :xref-format
              (value))))

    (setq org-odt-caption-and-numbering-settings
          '((:FIGURE: :variable "Figure" :entity-name "图" :caption-style "Figure" :use-outline-levelp nil :seq-num-format "1")))

The space must have sneaked in somewhere.

![img_2022_02_14__21_32_22](https://user-images.githubusercontent.com/8192731/153873661-f0816937-9ea1-4851-aa5f-1002336a6ebe.png)

**Comment by kjambunathan** [comment]
The solution is here https://ask.libreoffice.org/t/keep-caption-with-table/55701

> The caption is an ordinary text paragraph. Make sure there isn’t another paragraph between the caption and the table, and enable the TextFlow property Keep with next paragraph for the caption.

> If you prefer to have the caption below the table (as I do) you need to enable the mentioned property for the table itself.

Where the text flow property goes depends on how the caption is positioned.  So, I may have to choose different styles based on where the caption is positioned.

Simpler solution would be for you to roll your own caption style or table style, AFTER deciding whether you want to position your caption before or after.

Paragraph property to look for is `fo:keep-with-next="always"`.

In your case, use this snippet, and remember to eval the babel block.


```
#+options:  toc:nil author:nil tex:t latex:t :H 10

# #+odt_extra_styles: <style:style style:name="Figure"
# #+odt_extra_styles:              style:parent-style-name="Caption"
# #+odt_extra_styles:              style:family="paragraph"
# #+odt_extra_styles:              style:class="extra"
# #+odt_extra_styles:              style:master-page-name="">
# #+odt_extra_styles:   <style:paragraph-properties fo:keep-with-next="always"
# #+odt_extra_styles:                               style:page-number="auto" />
# #+odt_extra_styles: </style:style>

#+begin_src emacs-lisp :exports results :results none
(setq org-odt-table-style-format
  "
<style:style style:name=\"%s\" style:family=\"table\" %s>
  <style:table-properties fo:margin-top=\"0cm\" fo:margin-bottom=\"0.20cm\" table:align=\"center\" %s fo:keep-with-next=\"always\"/>
</style:style>
"
  )
#+end_src


#+caption: Org unicorn
#+attr_odt: :category "figure" :list-table t
-
  -
    #+attr_odt: :width 7.1
    [[./org-mode-unicorn.png]]

  -
    #+attr_odt: :width 7.1
    [[./org-mode-unicorn.png]]


Line inserted to cause caption and figure seperation.

Line inserted to cause caption and figure seperation.

Line inserted to cause caption and figure seperation.

Line inserted to cause caption and figure seperation.

Line inserted to cause caption and figure seperation.

Line inserted to cause caption and figure seperation.

Line inserted to cause caption and figure seperation.

Line inserted to cause caption and figure seperation.
#+caption: Org unicorn
#+attr_odt: :category "figure" :list-table t
-
  -
    #+attr_odt: :width 7.1
    [[./org-mode-unicorn.png]]

  -
    #+attr_odt: :width 7.1
    [[./org-mode-unicorn.png]]


```

**Comment by kjambunathan** [comment]
There is no such space that is generated in my case 

```xml
<text:p text:style-name="Figure">图<text:bookmark text:name="org78a85f8"/><text:sequence text:ref-name="org78a85f8" text:name="Figure" text:formula="ooow:Figure+1" style:num-format="1">1</text:sequence>: Org unicorn</text:p>
```

Are you running tidy on XML buffer?  I suspect there is a new line in your XML, and it is because of `tidy` doing it's thing.

**Comment by QiangF** [comment]
Indeed, the problem is gone with

    (setq org-odt-prettify-xml "")

Thank you!
