### ISSUE TITLE
cite is not working

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#18]
I cloned your repo in /home/q/.emacs.d/org-mode-ox-odt.
Created a test file (/home/q/.emacs.d/org-mode-ox-odt/testing/examples/odt/test.org)
with the following content:

    a Master Thesis \cite{geer}

    #+ATTR_ODT: :style "Chicago (full-note)"
    #+BIBLIOGRAPHY: ./biblatex-examples/biblatex-examples.bib

My emacs configuration:

    (setq debug-on-error t)
    (setq load-prefer-newer t)
    (require 'package)
    (require 'cl)
    (setq load-path (remove-if (lambda (x) (string-match-p "org$" x)) load-path))
    (cl-pushnew "~/.emacs.d/org-mode-ox-odt/lisp/" load-path)
    (cl-pushnew "~/.emacs.d/org-mode-ox-odt/contrib/lisp/" load-path)

    (package-initialize)
    (require 'use-package)

    (use-package org
    :load-path "~/.emacs.d/org-mode-ox-odt/lisp/"
    )
    (use-package org-plus-contrib
    :load-path "~/.emacs.d/org-mode-ox-odt/contrib/lisp/"
    )
    (use-package ox-odt
        :load-path "~/.emacs.d/org-mode-ox-odt/lisp/"
        :config
        (add-to-list 'org-odt-transform-processes '("optimise table column width" "soffice" "--norestore" "--invisible" "--headless" "macro:///OrgMode.Utilities.OptimizeColumnWidth(%I)"))
        (require 'ox)
        (require 'ox-odt)
        (setq org-export-odt-convert-processes
            "/usr/bin/soffice --headless --convert-to %f%x --outdir %d %i"
            org-odt-prettify-xml t
            org-odt-schema-dir "~/.dotfiles/org/schema"
            org-odt-styles-dir "~/.emacs.d/org-mode-ox-odt/etc/styles"
            org-export-odt-preferred-output-format "odt"
            org-export-backends (quote (ascii html latex odt)))
    )

    (use-package ox-jabref
        :load-path "~/.emacs.d/org-mode-ox-odt/contrib/lisp/"
        :config
            (setq org-jabref-command '("java" "-jar" "/home/q/.emacs.d/JabRef-2.9.2.jar" "-n" "true"))
    )

*Message* buffer:

    Running java -jar /home/q/.emacs.d/JabRef-2.9.2.jar -n true -o /tmp/jabref-4914Qtu.xml,chicago.ODF.footend.short /home/q/.emacs.d/org-mode-ox-odt/testing/examples/odt/biblatex-examples/biblatex-examples.bib
    Bibliography is filtered
    Entering debugger...

**Comment by QiangF** [comment]
*Backtrace*:

    Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
    replace-regexp-in-string("[ 	\n
]+\\'" "" nil)
    org-trim(nil)
    (let* ((cite-key (org-trim (car cite-key-text))) (text (org-trim (cdr cite-key-text)))) (if (atom formatter) (progn (setq formatter (list formatter)))) (funcall (car formatter) cite-key text pre-note post-note (cdr formatter)))
    (closure ((between-citations . "<text:span text:style-name=\"OrgSuperscript\">, </text:span>") (formatter org-jabref-odt-format-citation-as-footnote-definition :substring (0 . -1) :braces ((nil . ".")) :text-after-pre-note " " :text-before-post-note ", ") (formatter-info :between-citations "<text:span text:style-name=\"OrgSuperscript\">, </text:span>" :formatter (org-jabref-odt-format-citation-as-footnote-definition :substring (0 . -1) :braces ((nil . ".")) :text-after-pre-note " " :text-before-post-note ", ")) (post-note . "") (pre-note . "") (cite-key-text-alist ("geer")) t) (cite-key-text) (let* ((cite-key (org-trim (car cite-key-text))) (text (org-trim (cdr cite-key-text)))) (if (atom formatter) (progn (setq formatter (list formatter)))) (funcall (car formatter) cite-key text pre-note post-note (cdr formatter))))(("geer"))
    mapconcat((closure ((between-citations . "<text:span text:style-name=\"OrgSuperscript\">, </text:span>") (formatter org-jabref-odt-format-citation-as-footnote-definition :substring (0 . -1) :braces ((nil . ".")) :text-after-pre-note " " :text-before-post-note ", ") (formatter-info :between-citations "<text:span text:style-name=\"OrgSuperscript\">, </text:span>" :formatter (org-jabref-odt-format-citation-as-footnote-definition :substring (0 . -1) :braces ((nil . ".")) :text-after-pre-note " " :text-before-post-note ", ")) (post-note . "") (pre-note . "") (cite-key-text-alist ("geer")) t) (cite-key-text) (let* ((cite-key (org-trim (car cite-key-text))) (text (org-trim (cdr cite-key-text)))) (if (atom formatter) (progn (setq formatter (list formatter)))) (funcall (car formatter) cite-key text pre-note post-note (cdr formatter)))) (("geer")) "<text:span text:style-name=\"OrgSuperscript\">, </text:span>")
    (org-jabref--strip-and-add-pre/post-notes (mapconcat (function (lambda (cite-key-text) (let* ((cite-key (org-trim ...)) (text (org-trim ...))) (if (atom formatter) (progn (setq formatter ...))) (funcall (car formatter) cite-key text pre-note post-note (cdr formatter))))) cite-key-text-alist between-citations) pre-note post-note formatter-info)
    (let* ((formatter (plist-get formatter-info :formatter)) (between-citations (plist-get formatter-info :between-citations))) (org-jabref--strip-and-add-pre/post-notes (mapconcat (function (lambda (cite-key-text) (let* ((cite-key ...) (text ...)) (if (atom formatter) (progn ...)) (funcall (car formatter) cite-key text pre-note post-note (cdr formatter))))) cite-key-text-alist between-citations) pre-note post-note formatter-info))
    org-jabref--multicite((("geer")) "" "" (:between-citations "<text:span text:style-name=\"OrgSuperscript\">, </text:span>" :formatter (org-jabref-odt-format-citation-as-footnote-definition :substring (0 . -1) :braces ((nil . ".")) :text-after-pre-note " " :text-before-post-note ", ")))
    funcall(org-jabref--multicite (("geer")) "" "" (:between-citations "<text:span text:style-name=\"OrgSuperscript\">, </text:span>" :formatter (org-jabref-odt-format-citation-as-footnote-definition :substring (0 . -1) :braces ((nil . ".")) :text-after-pre-note " " :text-before-post-note ", ")))
    (let* ((pre-note (org-export-data (org-element-property :prefix citation) info)) (post-note (org-export-data (org-element-property :suffix citation) info)) (cite-keys (org-element-map citation (quote citation-reference) (function (lambda (citation-reference) (org-element-property :key citation-reference))))) (export-formats (org-jabref--get-export-format info :in-text :jabref-format)) (formatter-name (org-jabref--get-export-format info :in-text :formatter)) (formatter (org-jabref--get-citation-formatter info formatter-name)) (citation-cache (plist-get info :citation-cache)) (cite-key-text-alist (mapcar (function (lambda (cite-key) (let* (...) (cons cite-key ...)))) cite-keys))) (funcall (car formatter) cite-key-text-alist pre-note post-note (cdr formatter)))
    org-jabref-citation((citation (:parenthetical nil :parent (paragraph (:begin 161 :end 351 :contents-begin 161 :contents-end 350 :post-blank 1 :post-affiliated 161 :parent (section (:begin 100 :end 722 :contents-begin 100 :contents-end 721 :post-blank 1 :post-affiliated 100 :parent (headline (:raw-value "Cite using ~\\cite{}~ fragments" :begin 64 :end 721 :pre-blank 1 :contents-begin 100 :contents-end 721 :level 3 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 64 :title ... :parent ...) #4)) (paragraph (:begin 100 :end 161 :contents-begin 100 :contents-end 160 :post-blank 1 :post-affiliated 100 :parent #4) #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 (:parent #5))) #2 (keyword (:key "BIBLIOGRAPHY" :value "./biblatex-examples/biblatex-examples.bib" :begin 351 :end 451 :post-blank 1 :post-affiliated 392 :attr_odt (":style \"Chicago (full-note)\"") :parent #4)))) #("Here I cite a Master Thesis " 0 28 (:parent #2)) #0 #("and few books\n" 0 14 (:parent #2)) (citation (:parenthetical nil :parent #2) (citation-reference (:key "aristotle:anima" :parent #3)) (citation-reference (:key "aristotle:physics" :parent #3))) #(".  Cite a\ncollection. " 0 22 (:parent #2)) (citation (:parenthetical nil :parent #2) (citation-reference (:key "britannica" :parent #3))) #("Here I re-cite an earlier book\n" 0 31 (:parent #2)) (citation (:parenthetical nil :parent #2) (citation-reference (:key "aristotle:anima" :parent #3))) #(".\n" 0 2 (:parent #2)))) (citation-reference (:key "geer" :parent #0))) "" (:export-options nil :back-end [cl-struct-org-export-backend odt nil ((keyword . org-jabref-keyword) (citation . org-jabref-citation) (bold . org-odt-bold) (center-block . org-odt-center-block) (clock . org-odt-clock) (code . org-odt-code) (drawer . org-odt-drawer) (dynamic-block . org-odt-dynamic-block) (entity . org-odt-entity) (example-block . org-odt-example-block) (export-block . org-odt-export-block) (export-snippet . org-odt-export-snippet) (fixed-width . org-odt-fixed-width) (footnote-definition . org-odt-footnote-definition) (footnote-reference . org-odt-footnote-reference) (headline . org-odt-headline) (horizontal-rule . org-odt-horizontal-rule) (inline-src-block . org-odt-inline-src-block) (inlinetask . org-odt-inlinetask) (italic . org-odt-italic) (item . org-odt-item) (keyword . org-odt-keyword) (latex-environment . org-odt-latex-environment) (latex-fragment . org-odt-latex-fragment) (line-break . org-odt-line-break) (link . org-odt-link) (node-property . org-odt-node-property) (paragraph . org-odt-paragraph) (plain-list . org-odt-plain-list) (plain-text . org-odt-plain-text) (planning . org-odt-planning) (property-drawer . org-odt-property-drawer) (quote-block . org-odt-quote-block) (radio-target . org-odt-radio-target) (section . org-odt-section) (special-block . org-odt-special-block) (src-block . org-odt-src-block) (statistics-cookie . org-odt-statistics-cookie) (strike-through . org-odt-strike-through) (subscript . org-odt-subscript) (superscript . org-odt-superscript) (table . org-odt-table) (table-cell . org-odt-table-cell) (table-row . org-odt-table-row) (target . org-odt-target) (template . org-odt-template) (timestamp . org-odt-timestamp) (underline . org-odt-underline) (verbatim . org-odt-verbatim) (verse-block . org-odt-verse-block) ...) ((:odt-styles-file "ODT_STYLES_FILE" nil nil t) (:odt-content-template-file nil nil org-odt-content-template-file) (:odt-display-outline-level nil nil org-odt-display-outline-level) (:odt-fontify-srcblocks nil nil org-odt-fontify-srcblocks) (:odt-format-drawer-function nil nil org-odt-format-drawer-function) (:odt-format-headline-function nil nil org-odt-format-headline-function) (:odt-format-inlinetask-function nil nil org-odt-format-inlinetask-function) (:odt-inline-formula-rules nil nil org-odt-inline-formula-rules) (:odt-inline-image-rules nil nil org-odt-inline-image-rules) (:odt-pixels-per-inch nil nil org-odt-pixels-per-inch) (:odt-styles-file nil nil org-odt-styles-file) (:odt-table-styles nil nil org-odt-table-styles) (:odt-use-date-fields nil nil org-odt-use-date-fields) (:with-latex nil "tex" org-odt-with-latex)) ((:filter-parse-tree org-odt--translate-cite-fragments org-odt--collect-cite-keys org-odt--translate-latex-fragments org-odt--translate-description-lists org-odt--translate-list-tables)) nil (111 "Export to ODT (With Jabref Processing)" ((111 "As ODT file" org-odt-export-to-odt) (79 "As ODT file and open" (lambda (a s v b) (if a (org-odt-export-to-odt t s v) (org-open-file ... ...))))))] :translate-alist ((keyword . org-jabref-keyword) (citation . org-jabref-citation) (bold . org-odt-bold) (center-block . org-odt-center-block) (clock . org-odt-clock) (code . org-odt-code) (drawer . org-odt-drawer) (dynamic-block . org-odt-dynamic-block) (entity . org-odt-entity) (example-block . org-odt-example-block) (export-block . org-odt-export-block) (export-snippet . org-odt-export-snippet) (fixed-width . org-odt-fixed-width) (footnote-definition . org-odt-footnote-definition) (footnote-reference . org-odt-footnote-reference) (headline . org-odt-headline) (horizontal-rule . org-odt-horizontal-rule) (inline-src-block . org-odt-inline-src-block) (inlinetask . org-odt-inlinetask) (italic . org-odt-italic) (item . org-odt-item) (keyword . org-odt-keyword) (latex-environment . org-odt-latex-environment) (latex-fragment . org-odt-latex-fragment) (line-break . org-odt-line-break) (link . org-odt-link) (node-property . org-odt-node-property) (paragraph . org-odt-paragraph) (plain-list . org-odt-plain-list) (plain-text . org-odt-plain-text) (planning . org-odt-planning) (property-drawer . org-odt-property-drawer) (quote-block . org-odt-quote-block) (radio-target . org-odt-radio-target) (section . org-odt-section) (special-block . org-odt-special-block) (src-block . org-odt-src-block) (statistics-cookie . org-odt-statistics-cookie) (strike-through . org-odt-strike-through) (subscript . org-odt-subscript) (superscript . org-odt-superscript) (table . org-odt-table) (table-cell . org-odt-table-cell) (table-row . org-odt-table-row) (target . org-odt-target) (template . org-odt-template) (timestamp . org-odt-timestamp) (underline . org-odt-underline) (verbatim . org-odt-verbatim) (verse-block . org-odt-verse-block) ...) :exported-data #s(hash-table size 4001 test eq rehash-size 1.5 rehash-threshold 0.8 data ((keyword (:key "TITLE" :value "Testfile for OpenDocumentText Exporter" :begin 1 :end 49 :post-blank 0 :post-affiliated 1 :parent (section (:begin 1 :end 50 :contents-begin 1 :contents-end 49 :post-blank 1 :post-affiliated 1 :parent (org-data nil #4 (headline ... ...) (headline ... ...))) #2))) "" (section (:begin 1 :end 50 :contents-begin 1 :contents-end 49 :post-blank 1 :post-affiliated 1 :parent (org-data nil #2 (headline (:raw-value "Citations" :begin 50 :end 722 :pre-blank 1 :contents-begin 64 :contents-end 721 :level 2 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 1 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 50 :title (#("Citations" 0 9 ...)) :parent #4) (headline (:raw-value "Cite using ~\\cite{}~ fragments" :begin 64 :end 721 :pre-blank 1 :contents-begin 100 :contents-end 721 :level 3 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 64 :title ... :parent #5) (section ... ... ... ...))) (headline (:raw-value "Footnotes" :begin 722 :end 790 :pre-blank 1 :contents-begin 735 :contents-end 790 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p t :archivedp nil :commentedp nil :post-affiliated 722 :title (#("Footnotes" 0 9 ...)) :parent #4) (section (:begin 735 :end 790 :contents-begin 735 :contents-end 790 :post-blank 0 :post-affiliated 735 :parent #5) (footnote-definition ... ...))))) (keyword (:key "TITLE" :value "Testfile for OpenDocumentText Exporter" :begin 1 :end 49 :post-blank 0 :post-affiliated 1 :parent #2))) "\n" #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 (:parent (paragraph (:begin 100 :end 161 :contents-begin 100 :contents-end 160 :post-blank 1 :post-affiliated 100 :parent (section (:begin 100 :end 722 :contents-begin 100 :contents-end 721 :post-blank 1 :post-affiliated 100 :parent ...) #4 (paragraph ... #("Here I cite a Master Thesis " 0 28 ...) ... #("and few books\n" 0 14 ...) ... #(".  Cite a\ncollection. " 0 22 ...) ... #("Here I re-cite an earlier book\n" 0 31 ...) ... #(".\n" 0 2 ...)) (keyword ...))) #2))) #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 (:parent (paragraph (:begin 100 :end 161 :contents-begin 100 :contents-end 160 :post-blank 1 :post-affiliated 100 :parent (section (:begin 100 :end 722 :contents-begin 100 :contents-end 721 :post-blank 1 :post-affiliated 100 :parent ...) #4 (paragraph ... #("Here I cite a Master Thesis " 0 28 ...) ... #("and few books\n" 0 14 ...) ... #(".  Cite a\ncollection. " 0 22 ...) ... #("Here I re-cite an earlier book\n" 0 31 ...) ... #(".\n" 0 2 ...)) (keyword ...))) #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 (:parent #4))))) (paragraph (:begin 100 :end 161 :contents-begin 100 :contents-end 160 :post-blank 1 :post-affiliated 100 :parent (section (:begin 100 :end 722 :contents-begin 100 :contents-end 721 :post-blank 1 :post-affiliated 100 :parent (headline (:raw-value "Cite using ~\\cite{}~ fragments" :begin 64 :end 721 :pre-blank 1 :contents-begin 100 :contents-end 721 :level 3 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 64 :title ... :parent ...) #4)) #2 (paragraph (:begin 161 :end 351 :contents-begin 161 :contents-end 350 :post-blank 1 :post-affiliated 161 :parent #4) #("Here I cite a Master Thesis " 0 28 (:parent #5)) (citation (:parenthetical nil :parent #5) (citation-reference ...)) #("and few books\n" 0 14 (:parent #5)) (citation (:parenthetical nil :parent #5) (citation-reference ...) (citation-reference ...)) #(".  Cite a\ncollection. " 0 22 (:parent #5)) (citation (:parenthetical nil :parent #5) (citation-reference ...)) #("Here I re-cite an earlier book\n" 0 31 (:parent #5)) (citation (:parenthetical nil :parent #5) (citation-reference ...)) #(".\n" 0 2 (:parent #5))) (keyword (:key "BIBLIOGRAPHY" :value "./biblatex-examples/biblatex-examples.bib" :begin 351 :end 451 :post-blank 1 :post-affiliated 392 :attr_odt (":style \"Chicago (full-note)\"") :parent #4)))) #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 (:parent #2))) #("\n<text:p text:style-name=\"Text_20_body\">Citations and Bibliography are supported using ox-jabref.el\n</text:p>\n\n" 40 100 (:parent (paragraph (:begin 100 :end 161 :contents-begin 100 :contents-end 160 :post-blank 1 :post-affiliated 100 :parent (section (:begin 100 :end 722 :contents-begin 100 :contents-end 721 :post-blank 1 :post-affiliated 100 :parent ...) #4 (paragraph ... #("Here I cite a Master Thesis " 0 28 ...) ... #("and few books\n" 0 14 ...) ... #(".  Cite a\ncollection. " 0 22 ...) ... #("Here I re-cite an earlier book\n" 0 31 ...) ... #(".\n" 0 2 ...)) (keyword ...))) #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 (:parent #4))))) #("Here I cite a Master Thesis " 0 28 (:parent (paragraph (:begin 161 :end 351 :contents-begin 161 :contents-end 350 :post-blank 1 :post-affiliated 161 :parent (section (:begin 100 :end 722 :contents-begin 100 :contents-end 721 :post-blank 1 :post-affiliated 100 :parent ...) (paragraph ... #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 ...)) #4 (keyword ...))) #2 (citation (:parenthetical nil :parent #4) (citation-reference (:key "geer" :parent #5))) #("and few books\n" 0 14 (:parent #4)) (citation (:parenthetical nil :parent #4) (citation-reference (:key "aristotle:anima" :parent #5)) (citation-reference (:key "aristotle:physics" :parent #5))) #(".  Cite a\ncollection. " 0 22 (:parent #4)) (citation (:parenthetical nil :parent #4) (citation-reference (:key "britannica" :parent #5))) #("Here I re-cite an earlier book\n" 0 31 (:parent #4)) (citation (:parenthetical nil :parent #4) (citation-reference (:key "aristotle:anima" :parent #5))) #(".\n" 0 2 (:parent #4))))) #("Here I cite a Master Thesis " 0 28 (:parent (paragraph (:begin 161 :end 351 :contents-begin 161 :contents-end 350 :post-blank 1 :post-affiliated 161 :parent (section (:begin 100 :end 722 :contents-begin 100 :contents-end 721 :post-blank 1 :post-affiliated 100 :parent ...) (paragraph ... #("Citations and Bibliography are supported using ox-jabref.el\n" 0 60 ...)) #4 (keyword ...))) #("Here I cite a Master Thesis " 0 28 (:parent #4)) (citation (:parenthetical nil :parent #4) (citation-reference (:key "geer" :parent #5))) #("and few books\n" 0 14 (:parent #4)) (citation (:parenthetical nil :parent #4) (citation-reference (:key "aristotle:anima" :parent #5)) (citation-reference (:key "aristotle:physics" :parent #5))) #(".  Cite a\ncollection. " 0 22 (:parent #4)) (citation (:parenthetical nil :parent #4) (citation-reference (:key "britannica" :parent #5))) #("Here I re-cite an earlier book\n" 0 31 (:parent #4)) (citation (:parenthetical nil :parent #4) (citation-reference (:key "aristotle:anima" :parent #5))) #(".\n" 0 2 (:parent #4))))) (citation-reference (:key "geer" :parent (citation (:parenthetical nil :parent (paragraph (:begin 161 :end 351 :contents-begin 161 :contents-end 350 :post-blank 1 :post-affiliated 161 :parent ...) #("Here I cite a Master Thesis " 0 28 ...) #4 #("and few books\n" 0 14 ...) (citation ... ... ...) #(".  Cite a\ncollection. " 0 22 ...) (citation ... ...) #("Here I re-cite an earlier book\n" 0 31 ...) (citation ... ...) #(".\n" 0 2 ...))) #2))) "" nil "" ...)) :input-buffer "test.org" :input-file "/home/q/.emacs.d/org-mode-ox-odt/testing/examples/odt/test.org" :odt-styles-file nil :odt-content-template-file nil :odt-display-outline-level 2 :odt-fontify-srcblocks t :odt-format-drawer-function #[514 "\207" [] 3 "\n\n(fn NAME CONTENTS)"] :odt-format-headline-function org-odt-format-headline-default-function :odt-format-inlinetask-function org-odt-format-inlinetask-default-function :odt-inline-formula-rules (("file" . "\\.\\(mathml\\|mml\\|odf\\)\\'")) :odt-inline-image-rules (("file" . "\\.\\(jpeg\\|jpg\\|png\\|gif\\|svg\\)\\'")) :odt-pixels-per-inch 96.0 :odt-table-styles (("OrgEquation" "OrgEquation" ((use-first-column-styles . t) (use-last-column-styles . t))) ("TableWithHeaderRowAndColumn" "Custom" ((use-first-row-styles . t) (use-first-column-styles . t))) ("TableWithFirstRowandLastRow" "Custom" ((use-first-row-styles . t) (use-last-row-styles . t))) ("GriddedTable" "Custom" nil)) :odt-use-date-fields nil :with-latex verbatim :title (#("Testfile for OpenDocumentText Exporter" 0 38 (:parent #1))) :date nil :author (#("Debian q" 0 8 (:parent #1))) :email "q@debian.unassigned-domain" :language "en" :select-tags ("export") ...))
    #[0 "\302\300\303\204\n

**Comment by QiangF** [comment]
Ahh! I fogot to install the plugin. Sorry.

**Comment by kjambunathan** [comment]
> The full backtrace is here: http://s000.tinyupload.com/?file_id=55155272497685994860

> Ahh! I fogot to install the plugin. Sorry.

I must check if the plugin is installed or not.  Re-opening the issue.
