### ISSUE TITLE
export text with colors

### ISSUE THREAD

**Issue by ouboub** [kjambunathan/org-mode-ox-odt#189]
Hi

a short hack of the sort 
```(defun my-color-html ()
  (interactive)
  (while (re-search-forward "#\\([^#]*\\)#" nil t)
    (replace-match "<span style=\"color:red\">\\1</span>")))
```
Allows me to export text like this 
#important#

 to HTML where the resulted text is colored  in red.

Now, how can I achieve something like this for the odt export?

Reards
Uwe Brauer

**Comment by QiangF** [comment]
I think currently you need odt style, define that in your style file, then you can use:

    @@odt:<text:span text:style-name="your_red_font_style">your text</text:span>@@

or

    #+attr_odt: :style "your_red_font_style"
    your text

I think embed "@@odt:<text:span text:style-name=...</text:span>" is very distracting, and the text format is not clear by looking at it. It will be convenient if impromptu text style can be set via a inline command more easily, like in the following paragraph: 

   I wish \odt{:color red :font SimSun :font_size 12}{big red text} can be set more easily without style files.

**Comment by ouboub** [comment]
> #+attr_odt: :style "your_red_font_style"
> your text

thanks, I digged into that (replacing red by background highlighted yellow)
and 
```
#+odt_extra_styles: <style:style style:name="Highlight" style:family="text">
#+odt_extra_styles:     <style:text-properties fo:background-color="#ffff00"/>
#+odt_extra_styles: </style:style>

@@odt:<text:span text:style-name="Highlight">your text</text:span>@@
```
worked 
but 
```
#+attr_odt: :style "Highlight"
your text
```
could not even by exported

**Comment by kjambunathan** [comment]
[custom-spans.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/8878084/custom-spans.zip)

![custom-props-1](https://user-images.githubusercontent.com/19869864/173047355-facbed18-2e55-481c-9f96-6ba43cb7c172.png)

![custom-props-2](https://user-images.githubusercontent.com/19869864/173047382-af76f153-1d62-466a-9758-12eafe8b0120.png)


The resulting `zip` file and screenshots are attached.  The procedure is done with `emacs -Q`, so it should be reproducible at your end.    I have attached screenshots to get yourself oriented about all `babel`-fu happening here.

Needless to say, this works only with my fork of the exporter.





- `emacs -Q`
-  `M-x load-file ~/src1/org-mode-ox-odt/lisp/ox-odt.el`
- `C-x C-f custom-spans/custom-spans.org` (Say "yes" when prompted)
- `C-c C-v b` 
- Follow it up with `C-/` or `C-x C-s`. Doesn't matter which one.
- `C-c C-e h o`
- `C-c C-e o O`
- `C-x b custom-spans.org`, `C-x v v`, See that the custom  spans are highlighted



```
#+options: tex:t
#+description:
#+keywords:
#+subtitle:
#+odt_math_syntax: latex
#+odt_preferred_output_format: pdf
#+odt_styles_file:
#+odt_extra_images:
#+odt_extra_styles:
#+odt_extra_automatic_styles:
#+odt_master_styles:
#+odt_content_template_file:
#+odt_automatic_styles:
#+odt_display_outline_level: 2
#+odt_app:
#+odt_document_properties:
#+odt_extra_meta:
#+odt_prettify_xml:
#+odt_validate:
#+odt_endnote_regexp: ^$

* Face to CSS

#+begin_src emacs-lisp :exports none
(require 'hi-lock)
(require 'htmlfontify)
(require 'rx)
(defun face->css-props (face)
  (let ((s (cdr (hfy-face-to-css-default face))))
    (when (string-match (rx-to-string '(and "{" (group (zero-or-more any)) "}")) s)
      (format "<span style=\"%s\">%%s</span>" (match-string 1 s)))))
#+end_src

#+name: hi-yellow-css
#+begin_src emacs-lisp :exports none
(face->css-props 'hi-yellow)
#+end_src

#+name: hi-red-b-css
#+begin_src emacs-lisp :exports none
(face->css-props 'hi-red-b)
#+end_src

* Face to ODT Text Properties

#+name: face-to-text-properties
#+begin_src emacs-lisp :exports none :resuts silent
(defun face->style:text-properties (face)
  (org-odt--lisp-to-xml
   (assoc 'style:text-properties (org-odt--xml-to-lisp (cdr (org-odt-hfy-face-to-css face))))))
#+end_src

#+name: hi-yellow-odt
#+begin_src emacs-lisp :exports none
(face->style:text-properties 'hi-yellow)
#+end_src

#+name: hi-red-b-odt
#+begin_src emacs-lisp :exports none
(face->style:text-properties 'hi-red-b)
#+end_src

* Character Styles

#+ATTR_ODT: :target "extra_styles"
#+begin_src nxml :noweb yes :exports code  :eval never
<style:style style:name="MyBangBang"
             style:family="text">
  <<hi-yellow-odt()>>
</style:style>

<style:style style:name="MyBangHash"
             style:family="text">
  <<hi-red-b-odt()>>
</style:style>
#+end_src

* Paragraph styles

#+ATTR_ODT: :target "extra_styles"
#+begin_src nxml :exports code :eval never
<style:style style:name="MyEclecticTextBody"
             style:parent-style-name="Text_20_body"
             style:family="paragraph">
  <style:paragraph-properties>
    <style:tab-stops />
  </style:paragraph-properties>
  <style:text-properties fo:background-color="#3ed1fc"
                         fo:color="#653a91"
                         fo:font-size="14pt"
                         fo:font-style="italic"
                         fo:font-weight="bold" />
</style:style>
#+end_src

* Setup

#+begin_src emacs-lisp :exports none :results silent
(setq my-custom-specs
  `(("hi-yellow" . (:regexp ("!!" . "!!")
                     :formatter ((html . ,(face->css-props 'hi-yellow))
                                 (odt . "<text:span text:style-name=\"MyBangBang\">%s</text:span>"))
                     :face hi-yellow))
    ("hi-red-b" . (:regexp ("!#" . "#!")
                     :formatter ((html . ,(face->css-props 'hi-red-b))
                                (odt . "<text:span text:style-name=\"MyBangHash\">%s</text:span>"))
                    :face hi-red-b))))

(defun my-custom-spans (text backend info)
  (with-temp-buffer
    (insert text)
    (cl-loop for (marker . spec) in my-custom-specs
	     for markers = (plist-get spec :regexp)
	     for beg-marker = (car markers)
	     for end-marker = (cdr markers)
	     for regex = (rx-to-string `(and ,beg-marker
					     (group (minimal-match
						     (zero-or-more (or any "\n"))))
					     ,end-marker))
	     for formatter = (plist-get spec :formatter)
	     for fmt = (alist-get backend formatter)
	     do
	     (goto-char (point-min))
	     (while (re-search-forward regex nil t)
	       (replace-match (format fmt (match-string 1)) t)))
    (buffer-substring-no-properties (point-min) (point-max))))

(add-to-list 'org-export-filter-plain-text-functions
             'my-custom-spans)

(add-hook 'org-mode-hook
          (defun my-org-mode-hook ()
            (hi-lock-mode 1)
            (cl-loop for (marker . spec) in my-custom-specs
                     for markers = (plist-get spec :regexp)
                     for beg-marker = (car markers)
                     for end-marker = (cdr markers)
                     for regex = (rx-to-string `(and ,beg-marker
						     (group
						      (minimal-match
						       (zero-or-more (or any "\n"))))
                                                     ,end-marker))
                     for face = (plist-get spec :face)
                     do (highlight-regexp regex face 1))))
#+end_src

* Text

- BangBang Text :: !!Non nulla velit ea eiusmod labore!!
- BangHash Text :: !#Nostrud fugiat ut occaecat dolore officia#!
- BangBang BangHash Text :: !!Adipiscing proident, nulla pariatur !#Aliqua ad enim irure#! aute pariatur incididunt est excepteur!!
- BangHash BangBang Text :: !#Anim aute minim !!Adipiscing in incididunt!! pariatur officia#!

- Hash Paragraph ::

  #+ATTR_ODT: :style "MyEclecticTextBody"
  Consectetur sint ut tempor labore nisi aliqua id occaecat laboris
  cupidatat !!id pariatur!!.  Aute veniam, !!amet, in proident, velit!!
  pariatur incididunt.  Enim reprehenderit cillum elit, nostrud amet,
  excepteur quis.  !#Id ad cillum tempor exercitation do labore eiusmod.
  Consequat fugiat est#! laboris sit labore cillum fugiat ut ad velit
  eiusmod est enim voluptate mollit.  Laborum nulla ex ea adipiscing
  ad non culpa proident,.

# Local Variables:
# org-export-use-babel: t
# org-confirm-babel-evaluate: nil
# End:

```

**Comment by kjambunathan** [comment]
This is the bare minimal version of the monster in the previous message ....

`MyEclecticTextBody`, **_a paragraph style_**, shows what all text properties one may need.  `MyBangBang`, **_a character style_** uses only `fo:background-color`. 

I have added enough pointers.  Source code is your friend.  

FWIW, I have added  [Good Resources for learning LibreOffice](https://github.com/kjambunathan/org-mode-ox-odt#good-resources-for-learning-libreoffice)
 

```
#+ATTR_ODT: :target "extra_styles"
#+begin_src nxml :noweb yes :exports code  :eval never
<style:style style:name="MyBangBang"
             style:family="text">
  <style:text-properties fo:background-color="#ffff00" fo:color="#000000"/>
</style:style>
#+end_src

#+ATTR_ODT: :target "extra_styles"
#+begin_src nxml :exports code :eval never
<style:style style:name="MyEclecticTextBody"
             style:parent-style-name="Text_20_body"
             style:family="paragraph">
  <style:paragraph-properties>
    <style:tab-stops />
  </style:paragraph-properties>
  <style:text-properties fo:background-color="#3ed1fc"
                         fo:color="#653a91"
                         fo:font-size="14pt"
                         fo:font-style="italic"
                         fo:font-weight="bold" />
</style:style>
#+end_src

@@odt:<text:span text:style-name="MyBangBang">This is highlighted text</text:span>@@.  But this is regular text.



















```

**Comment by kjambunathan** [comment]
> I wish \odt{:color red :font SimSun :font_size 12}{big red text} can be set more easily without style files.

Fontification of source blocks already generates colors dynamically.  But the existing `face`->`XML` mappings only  use only foreground and background colors.    I never felt the need for changing the font, it's weight etc.

If you think it is useful it could be added.

Btw, if you haven't already noticed ODT styles now uses `nxml` source blocks for styles.  This means that

- they can be easily edited
- they can be dynamically built by assembling individual components  (i.e., noweb expansion)

There is plenty of example using `nxml` source blocks, `noweb` substituition, dynamic genertion of page headers and footers using `babel` blocks etc.  in the `issues` pages, and also on [Emacs Stackexchange](https://emacs.stackexchange.com/search?tab=newest&q=odt).

**Comment by kjambunathan** [comment]
That one is revert buffer. This is so that the org mode hook installed by
babel execute buffer turns on the  hi lock mode and, buffer refontfies.

 Multiline font lock needs a totally different set of moves .... So buffer
fontification may not be perfect.  I added font lock keywords, so that one
can orient oneself about the new emphasis  markers

**Comment by ouboub** [comment]
> Please pull again. The error will go away. It is C-c C-v b, org babel execute buffer or some.such thing.
thanks, but now when I run
 `org-babel-execute-buffer`

I Obtain
```
Debugger entered--Lisp error: (error "No org-babel-execute function for nxml!")
  signal(error ("No org-babel-execute function for nxml!"))
  error("No org-babel-execute function for %s!" "nxml")
  org-babel-execute-src-block(nil)
  org-babel-execute-buffer(nil)
  funcall-interactively(org-babel-execute-buffer nil)
  call-interactively(org-babel-execute-buffer nil nil)
  command-execute(org-babel-execute-buffer)
```

**Comment by kjambunathan** [comment]
> Debugger entered--Lisp error: (error "No org-babel-execute function for nxml!")
>   signal(error ("No org-babel-execute function for nxml!"))
>   error("No org-babel-execute function for %s!" "nxml")

Are you using `emacs -Q` or `emacs -q` .... I am using the `emacs` with `Capital Q`.

In `custom-spans.org`,  `nxml` blocks have `:eval` set to `never`. Why would babel look for an `execute` function for a block which is never `eval`-ed?   

```
2 matches for "nxml" in buffer: custom-spans.org
     66:#+begin_src nxml :noweb yes :exports code  :eval never
     81:#+begin_src nxml :exports code :eval never
```

It works on my end without any errors.  This is what I see on `*Messages*` before  ... Note specifically the log line for `nxm` which says `disabled`.



```
<style:style style:name="MyBangBang"
             style:family="text">
  <style:text-properties fo:background-color="#ffff00" fo:color="#000000"/>
</style:style>

<style:style style:name="MyBangHash"
             style:family="text">
  <style:text-properties fo:background-color="#ffffff" fo:color="#ee2c2c"/>
</style:style>
```





```
executing Emacs-Lisp code block...
Code block evaluation complete.
executing Emacs-Lisp code block (hi-yellow-css)...
Code block evaluation complete.
executing Emacs-Lisp code block (hi-red-b-css)...
Code block evaluation complete.
executing Emacs-Lisp code block (face-to-text-properties)...
Code block evaluation complete.
executing Emacs-Lisp code block (hi-yellow-odt)...
Code block evaluation complete.
executing Emacs-Lisp code block (hi-red-b-odt)...
Code block evaluation complete.
Evaluation of this nxml code block is disabled. [2 times]
executing Emacs-Lisp code block...
(my-org-mode-hook #[0 "\300\301\302\303\304$\207" [add-hook change-major-mode-hook org-show-all append local] 5] #[0 "\300\301\302\303\304$\207" [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] org-babel-result-hide-spec org-babel-hide-all-hashes)

```

**Comment by ouboub** [comment]
Ok, I repeated all steps (using -Q) but unzipped again the file you attached 

then it **works**! Excellent thanks!
I will try it out now with all my init files
thanks again, very very useful indeed.
if it works i will include this lisp functions in my private setting or are you planning to include 
these addons in future releases?

**Comment by kjambunathan** [comment]
`noweb` expansion is besides the point ....

Try the attached `custom-spans-sans-babel.zip`.

[custom-spans-sans-babel.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/8883428/custom-spans-sans-babel.zip)


1. `emacs -Q`
2. `M-x load-file ~/src1/org-mode-ox-odt/lisp/ox-odt.el`
3. `M-x load-file ~/Downloads/custom-spans-sans-babel/custom-spans.el`
4. `C-x C-f ~/Downloads/custom-spans-sans-babel/custom-spans.org
5. `C-c C-e o O`

If you  change the faces--which you may never--you need to change the  XML attributes in the `custom-spans.org` and you can use the helper function to calculate the text properties.  Or you can do away with the helper function altogether and just plug in the hex values.

```
*** Welcome to IELM ***  Type (describe-mode) or press C-h m for help.
ELISP> (face->style:text-properties 'hi-yellow)

"<style:text-properties fo:background-color=\"#ffff00\" fo:color=\"#000000\"/>"
ELISP> (face->style:text-properties 'hi-red-b)

"<style:text-properties fo:background-color=\"#ffffff\" fo:color=\"#ee2c2c\"/>"
ELISP> (face->style:text-properties 'font-lock-function-name-face)

"<style:text-properties fo:background-color=\"#ffffff\" fo:color=\"#0000ff\"/>"
ELISP> 
```

**Comment by kjambunathan** [comment]
> if it works i will include this lisp functions in my private setting or are you planning to include
> these addons in future releases?

I have extracted the `elisp` pieces to `custom-spans.el` ...  I won't make a release for `custom-spans.el`.  So add it to your `.emacs`.

Make suitable modifications for the `latex` backend.

**Comment by ouboub** [comment]
> > if it works i will include this lisp functions in my private setting or are you planning to include
> > these addons in future releases?
> 
> I have extracted the `elisp` pieces to `custom-spans.el` ... I won't make a release for `custom-spans.el`. So add it to your `.emacs`.
> 
> Make suitable modifications for the `latex` backend.

thanks! very much

**Comment by kjambunathan** [comment]
I have added a new repo [*=org-extra-emphasis.el= --- _Extra Emphasis markers for Org_*](https://github.com/kjambunathan/org-extra-emphasis).  =org-extra-emphasis= works well with =ox-odt-9.5.3.467=.  

If any of you are interested in becoming a maintainer of =org-extra-emphasis=, I will  transfer the ownership to you.  I have no objections if you want to submit this to MELPA or GNU ELPA.  (I wouldn't personally do the submission myself)

**Comment by kjambunathan** [comment]
The following post appeared in  [Planet Emacslife](https://planet.emacslife.com/) RSS feed

[Use `org-extra-emphasis’ , when you need more Emphasis Markers in Emacs Org mode (or) How to produce
Geronimo Stilton-esque Books
with Emacs Org mode](https://emacsnotes.wordpress.com/2022/06/29/use-org-extra-emphasis-when-you-need-more-emphasis-markers-in-emacs-org-mode/)

**Comment by kjambunathan** [comment]
That one is revert buffer. This is so that the org mode hook installed by
babel execute buffer turns on the  hi lock mode and, buffer refontfies.

 Multiline font lock needs a totally different set of moves .... So buffer
fontification may not be perfect.  I added font lock keywords, so that one
can orient oneself about the new emphasis  markers
