### ISSUE TITLE
improper caption width and extra space between caption and subframe

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#191]
Test snippet:

        #+options:  toc:nil author:nil tex:t latex:t :H 10
        * number pair as width not working (can not set a wider caption width)

        #+caption: org-mode-unicorn.png is a long caption, need wider space
        #+attr_odt: :width (2,7) :style "Caption"
        [[./org-mode-unicorn.png]]

        * subcaption
        There is an extra line under the inner frame. (Between caption "animals" and subcaption)

        #+caption: animals
        #+attr_odt: :category "figure" :list-table t
        -
          -
            #+caption[(a)]: cat
            #+attr_odt: :width 7.1 :style "Caption"
            [[./org-mode-unicorn.png]]
          -
            #+caption[(b)]: dog
            #+attr_odt: :width 7.1 :style "Caption"
            [[./org-mode-unicorn.png]]

Screenshot:
![img_2022_07_02__16_40_27](https://user-images.githubusercontent.com/8192731/176993533-335a864f-bec2-4b52-be50-48fa7e790105.png)
[test.odt](https://github.com/kjambunathan/org-mode-ox-odt/files/9032675/test.odt)

**Comment by kjambunathan** [comment]
>  #+attr_odt: :width (2,7) :style "Caption

`:width` is a `cons`.  So use 

```
#+attr_odt: :width (2 . 7) :style "Caption"
```

The syntax is easy to remember the following rule.   

> `ATTR_ODT` is a `plist` without surrounding `()`.

**Comment by QiangF** [comment]
What's a mistake!
I feel my head is crammed with too much every day bullshit.
Thank you so much for your patience.
