### ISSUE TITLE
Linebreak in sub caption

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#200]
My friend is writing a thesis, which is needed to be qualified for her job. I recommended her to use this exporter, so she will at least learn something from writing a crap thesis. The stupid university managers want two captions for each figure. One caption in Chinese, the other in English and placed right below the first one. I have managed to do that for the main caption by add a line break "\\", but the line break doesn't work in the sub caption. 

So please make the linebreak in subcaption work, or maybe make the line break implicit by putting each "#+caption:" line on seperate lines. 

Thank you!

Test snippet:

    #+caption: 独角兽\\
    #+caption: Fig. [[fig:1]] Org unicorn
    #+label:  fig:1
    #+attr_odt: :category "figure" :list-table t
    -
      -
        #+caption: 独角兽宝宝 \\ ([[fig:a]]) Baby unicorn
        #+label:  fig:a
        #+attr_odt: :width 7.1 :style "Caption"
        [[./org-mode-unicorn.png]]
      -
        #+caption: 独角兽妈妈 \\ ([[fig:b]]) Monther unicorn
        #+label:  fig:b
        #+attr_odt: :width 7.1 :style "Caption"
        [[./org-mode-unicorn.png]]

    #+caption: 独角兽\\
    #+caption: Fig. [[fig:2]] Org unicorn
    #+label:  fig:2
    #+attr_odt: :category "figure" :list-table t
    -
      -
        #+caption: 独角兽哥哥 \\ ([[fig:a]]) Brother unicorn
        #+label:  fig:a
        #+attr_odt: :width 7.1 :style "Caption"
        [[./org-mode-unicorn.png]]
      -
        #+caption: 独角兽爸爸 \\ ([[fig:b]]) Father unicorn
        #+label:  fig:b
        #+attr_odt: :width 7.1 :style "Caption"
        [[./org-mode-unicorn.png]]
[captions.odt](https://github.com/kjambunathan/org-mode-ox-odt/files/9204525/captions.odt)

**Comment by QiangF** [comment]
![img_2022_07_28__09_13_21](https://user-images.githubusercontent.com/8192731/181399473-df9380ec-5b97-4ea5-a94e-d03d1050c6d9.png)

**Comment by kjambunathan** [comment]
You can use both `\\` and `{{{ODTLineBreak}}}` to create line breaks.  If you want an empty line just add another of these line break constructs.

![Screenshot from 2022-07-28 11-22-52](https://user-images.githubusercontent.com/19869864/181431299-acf5be74-f8ad-4504-8e22-8e2652cc2519.png)

I think the extra `space` is introduced by `ox.el`.  (I need to look patiently)

```
#+caption: 独角兽{{{ODTLineBreak}}}Fig. [[fig:1]] Org unicorn
#+label:  fig:1
#+attr_odt: :category "figure" :list-table t
- 
  - 
    #+caption: 独角兽宝宝{{{ODTLineBreak}}}([[fig:a]]) Baby unicorn
    #+label:  fig:a
    #+attr_odt: :width 7.1 :style "Caption"
    [[./org-mode-unicorn.png]]
  - 
    #+caption: 独角兽妈妈\\
    #+caption: ([[fig:b]]) Mother unicorn
    #+label:  fig:b
    #+attr_odt: :width 7.1 :style "Caption"
    [[./org-mode-unicorn.png]]

```

**Comment by kjambunathan** [comment]
> #+caption: 独角兽宝宝 \\ ([[fig:a]]) Baby unicorn

```
#+caption: 独角兽宝宝\\
#+caption: ([[fig:a]]) Baby unicorn
```

or 

```
#+caption: 独角兽宝宝{{{ODTLineBreak}}}([[fig:a]]) Baby unicorn
```

`\\` can occur only at `end of line`.  `{{{ODTLineBreak}}}` can occur anywhere.
