### ISSUE TITLE
when exporting with colors org-compat.el is needed

### ISSUE THREAD

**Issue by ouboub** [kjambunathan/org-mode-ox-odt#208]
hi

I am not sure whether this sort of topic should be posted here or in 
https://github.com/QiangF/org-extra-emphasis/issues
My apologies if this is the wrong place.
I attach two org files, one contains colors and it export fails the error message is 

Symbol’s function definition is void: org-font-lock-ensure

the solution consists in loading org-compat.el 

Not sure what the best solution is

regards

[bug-export-color.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/9399880/bug-export-color.zip)

**Comment by kjambunathan** [comment]
Looks like you have found a solution ...  I will look at the issue mid next
week


You can report org export emphasis issues here .... no problem.  I dont
have QiangF's repo on my watchlist. So  if you report issues there, I may
not get notification.
