### ISSUE TITLE
Feature request: insert a toc of sub levels

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#21]
The usecase is to insert sub-outline in presentations slide. So something like:

    #+toc: subheadlines 1
    #+PAGEBREAK:

will insert one sub level to the current heading.

**Comment by kjambunathan** [comment]
> The usecase is to insert sub-outline in presentations slide. 

Have you tried https://help.libreoffice.org/Writer/Outline_to_Presentation?

**Comment by QiangF** [comment]
Yes, but that just send the outline, I want to keep all the content. Actually I don't care if it is odt or odp. BTW, sub table of content is also helpful for a big document, such as a book with many chapter, sub toc for each chapter is a common practice.

**Comment by kjambunathan** [comment]
For sample Org snippet, see [test-new.org](https://github.com/kjambunathan/org-mode-ox-odt/commit/85331655769c05c3f88baa3a69222ad7574149b7 )
