### ISSUE TITLE
Improve git workflow for designers by supporting `.fodt` styles

### ISSUE THREAD

**Issue by camio** [kjambunathan/org-mode-ox-odt#217]
Designers prefer WYSIWYG tools for style creation since the feedback loop is instantaneous. The `ODT_STYLES_FILE` key goes a long way towards supporting this workflow. Unfortunately, both supported WYSIWYG options (`.ott` and `.odt`) use binary files which Git doesn't handle well.

Fortunately, there is a text-based format that is supported by WYSIWYG tools, `.fodt`. These are otherwise known as "Single OpenDocument XML files". If org-mode-ox-odt were to support `.fodt` with `ODT_STYLES_FILE`, the end result would be a workflow that is both designer and Git friendly. More information on this format can be found in section 3.1.2 of the [OpenDocument v1.2 specification](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1414998_253892949).

To implement such a feature, one could modify the `org-odt-write-styles-file` function in `ox-odt.el` to support the `.fodt` extension. It would essentially build the `styles.xml` file by creating a `<office:document-styles>` element whose contents are the `<office:automatic-styles>`, `<office:font-face-decls>`, `<office:master-styles>` and `<office:styles>` elements that are under the `<office:document>` tag in the `.fodt` file.

**Comment by kjambunathan** [comment]
Implementing `fodt` is not a big deal.  It is just a concatenation of the component xml files in a single file.

If you want to generate `fodt` files, you can do this

Add an entry to  `org-odt-convert-capabilities` as below

```lisp
(let ((entry (assoc-default "Text" org-odt-convert-capabilities)))
  (push "fodt" (nth 0 entry))
  (push '("fodt" "fodt") (nth 1 entry)))
```

and export an `org` file with `#+odt_preferred_output_format` set to `fodt`.

```
#+odt_preferred_output_format: fodt

Excepteur dolor commodo ut labore commodo cupidatat dolore.  Nostrud
laboris et mollit incididunt elit, magna fugiat.  Magna officia sint
aliqua ut adipiscing sunt qui tempor fugiat mollit officia dolor
dolore voluptate eu minim velit.  Id officia qui ea excepteur laboris
dolore minim fugiat ad deserunt aliqua enim adipiscing proident,.
Nulla in culpa exercitation ullamco do dolore esse eu eu.

```

When you export the above file, this is what you will see in the `*Messages*` buffer

```
ODT Zip Dir is /tmp/odt-7gyRC7/
Formatting LaTeX using mathml
ox-odt: Content template file is /home/kjambunathan/src1/org-mode-ox-odt/etc/styles/OrgOdtContentTemplate.xml
Wrote /tmp/odt-7gyRC7/content.xml
ox-odt: Styles file is /home/kjambunathan/src1/org-mode-ox-odt/etc/styles/OrgOdtStyles.xml
Wrote /tmp/odt-7gyRC7/styles.xml [2 times]
Wrote /tmp/odt-7gyRC7/meta.xml
Wrote /tmp/odt-7gyRC7/mimetype
Wrote /tmp/odt-7gyRC7/META-INF/manifest.xml
Create OpenDocument file ‘dtlioyj0wmj0.odt’...
Using schema ~/src1/org-mode-ox-odt/etc/schema/od-schema.rnc
Running zip -mX0 dtlioyj0wmj0.odt mimetype
Running zip -rmTq dtlioyj0wmj0.odt .
Created /home/kjambunathan/src1/org-mode-ox-odt/testing/examples/odt/dtlioyj0wmj0.odt
Executing soffice --headless --convert-to fodt --outdir /home/kjambunathan/src1/org-mode-ox-odt/testing/examples/odt/ /home/kjambunathan/src1/org-mode-ox-odt/testing/examples/odt/dtlioyj0wmj0.odt
convert /home/kjambunathan/src1/org-mode-ox-odt/testing/examples/odt/dtlioyj0wmj0.odt -> /home/kjambunathan/src1/org-mode-ox-odt/testing/examples/odt/dtlioyj0wmj0.fodt using filter : OpenDocument Text Flat XML
```

Note the last line in the above extract, which says that it uses an existing filter called ` OpenDocument Text Flat XML` to do the conversion.

**Comment by QiangF** [comment]
I second the use of .fodt file as the style file, it has two benefit:

1. the user can open the .fodt file in libreoffice and change the styles in a what you see is what you get manner
2. the change in .fodt is tracked by git      

But for the export, I would always prefer odt file.

**Comment by kjambunathan** [comment]
If you are using `fodt` files, images would get embedded as inline binary data.  I don't want huge blobs of encoded data in the file I am working with.

Documents which are worth their salt have atleast a company logo, and many illustration.

`fodt` sounds good in theory only.

With `odt` there is clear separatrion of concerns in to styles, content, meta data, application settings etc.  You see images as images--you can open the `zip` file, and see the image right in `Emacs`, with binary blob you have no clue what the heck it is.

I recommend that you use LibreOffice to create `fodt` files.  

**(I am closing this feature request, as not on my radar.  I may visit it at later point though)**

_Btw, I don't accept PRs and patches.  (I have mentioned this in `README.md`)  Unfortunately, I oouldn't find a setting which disables PRs for git repo._

**Comment by QiangF** [comment]
@kjambunathan As far as I know, we can use a odt file as the ODT_STYLES_FILE, but only the style.xml is used, images are not part of the style.

@camio fodt created by libreoffice might be friendly to git, but the styles inside is not in order, if you want a style file with related styles next to each other, you have to edit the styles.xml by hand anyway.
