### ISSUE TITLE
How to use title page style for the first page?

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#22]
My template file has a title page style, but it is not used in the exported document.

**Comment by kjambunathan** [comment]
> My template file has a title page style, but it is not used in the exported document.


1. Modify `OrgTitle` page style and include a page break before it. (See section titled ~A new Chapter starts with a new Page~, ~page 6~ of [Writing a Thesis in OpenOffice.org](http://www.openoffice.org/documentation/HOW_TO/word_processing/How_to_Write_a_Thesis_in_OOo.pdf).  

2. Use the modified template as part of ~#+ODT_STYLES_FILE: ~


Here is a sample snippet that you can use to experiment with:

    #+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
    #+OPTIONS: author:nil broken-links:nil c:nil creator:nil
    #+OPTIONS: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:t
    #+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
    #+OPTIONS: timestamp:nil title:nil toc:nil todo:t |:t
    #+TITLE: test
    #+DATE: <2017-08-22 Tue>
    #+AUTHOR: Jambunathan K
    #+EMAIL: kjambunathan@gmail.com
    #+LANGUAGE: en
    #+SELECT_TAGS: export
    #+EXCLUDE_TAGS: noexport
    #+CREATOR: Emacs 25.2.2 (Org mode 9.0.9)

    #+OPTIONS: tex:t
    #+ODT_STYLES_FILE: "test.ott"

    #+ATTR_ODT: :style "OrgTitle"
    #+PAGEBREAK: 

    #+ATTR_ODT: :style "OrgPageImage" :anchor "page"
    #+BEGIN_textbox
	#+BEGIN_CENTER
	    #+ATTR_ODT: :style "OrgTitle"
	    Title

	    #+ATTR_ODT: :style "OrgSubtitle"
	    Subtitle
	#+END_CENTER
    #+END_textbox


    #+PAGEBREAK:

    #+ATTR_ODT: :style "Text"
    #+BEGIN_abstract
    Abstract goes here.  Abstract goes here.  Abstract goes here.
    Abstract goes here.  Abstract goes here.  Abstract goes here.
    #+END_abstract

    * Blah Blah Blah Blah

    Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah
    Blah blah Blah blah
