### ISSUE TITLE
Ensure that the styles.xml doesn't ever contain duplicate styles

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#220]
Same as 

- [ODT_STYLES_FILE doesn't respect Htmlfontify style settings](https://github.com/kjambunathan/org-mode-ox-odt/issues/215) and 
- [Fix issue where some styles in style files are overridden](https://github.com/kjambunathan/org-mode-ox-odt/pull/216) 

but with an extended scope.

In other words, not only should the stlyes in `office:styles` be unique, but styles in `office:automatic-styles` and `office:master-styles` in `styles.xml` should be unique. 

Relying on implementation details of LibreOffice---that is the specific style that will be applied, when there are duplicate style definitions---is unreliable.

In case of `office:styles` , the latter styles override the previous ones, but in case of `office:automatic-styles` the prior ones override the latter style definitions.  See https://github.com/kjambunathan/org-mode-ox-odt/blob/bfa1ba0de66c833c59cbcbb1aff89f5051b373b8/lisp/ox-odt.el#L3911 which says

> When there are duplicate page layouts with same name defined, `LibreOffice` seems to go with the first definition it encounters.  So, inserting at the beginning of automatic styles section, gives us the flexibility of redefining page layouts using `#+ODT_EXTRA_AUTOMATIC_STYLES: ...`.  You can see this in action in `doc/org-odt-manual/list-table-1.org` etc where I change the page height to create an image file that is aesthetically pleasing for inclusion in the manuals.

**Comment by kjambunathan** [comment]
@camio I have addressed the issue your raised in [Fix issue where some styles in style files are overridden](https://github.com/kjambunathan/org-mode-ox-odt/pull/216) and [ODT_STYLES_FILE doesn't respect Htmlfontify style settings](https://github.com/kjambunathan/org-mode-ox-odt/issues/215).

I have unit-tested the changes, and I am happy with the results.

(I have some more additions to unit test, which I will commit tomorrow)

Meanwhile, if you could independently verify my changes, I will be very happy.  See https://github.com/kjambunathan/org-mode-ox-odt/commit/9c6556d86252ad8b11ffc510d177c9935d51cfbe for details of fix.

**Comment by camio** [comment]
I can confirm that the issue has been fixed for my use-case. Thanks so much!
