### ISSUE TITLE
Feature request: add font size and column width customization for table

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#23]
The use case is to fit a big table in a small space such as in a slide show.
An example keyword name and syntax is:

    # change font size to 10 point
    #+ATTR_ODT: :font-size 10

    # specify column width for list table
    #+ATTR_ODT: :col-width (3,1,1,1) 

So the following snnipet:

    #+ATTR_ODT: :font-size 10
    #+ATTR_ODT: :col-width (3,1,1,1) 
    #+ATTR_ODT: :list-table t
    -
    - Row 1
    - 1.1
    - 1.2
    - 1.3
    - -----
    - Row 2
    - 2.1
    - 2.2
    - 2.3

will be exported as though it were an Org table like the one show
below.

    | <c3>  | <c1>| <c1>| <c1>|
    |--------+-----+-----+-----|
    | Row 1 |  1.1  |  1.2  | 1.3  |
    |-------+-----+-----+-----|
    | Row 2 | 2.1  | 2.2  | 2.3 |

**Comment by kjambunathan** [comment]
I have added support for col. width and col. group attributes.  To test drive, use the following snippet:

    #+ATTR_ODT: :list-table t
    - | /    | <    |    > |       |
    - | <l8> | <r4> | <c2> | <l1>  |
    - --------
      - Row 1
      - Row 1.1
	- Subitem under 1.1
	- Yet another subitem under 1.1
      - Row 1.2
      - Row 1.3
    - --------
      - Row 2
      - Row 2.1

	Subtext for 2.1
      - Row 2.2
      - Row 2.3
    - --------

**Comment by kjambunathan** [comment]
As for font-sizing in tables, it is best achieved by applying a custom paragraph style for table.  Would you like to open a new issue for this?  This way, you will get a notification once I get around to fixing it.
