### ISSUE TITLE
Feature request: applying a custom paragraph style for a table

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#24]
Part of the request from
https://github.com/kjambunathan/org-mode-ox-odt/issues/23

**Comment by kjambunathan** [comment]
List tables now use `OrgTable...` styles.  You can simply customize these styles.  If you want per-table styles, you can use a snippet you see below.  Before you do that, read docstring of  `org-odt-table-cell--get-paragraph-styles`

    #+ATTR_ODT: :p-style "MyOrgTable"
    | a | b | c |

**Comment by kjambunathan** [comment]
If you  are using this feature, remember to include col alignment cookie.  Otherwise you will run in to https://github.com/kjambunathan/org-mode-ox-odt/issues/25.  (You _may_ want to  forward this issue to Orgmode maintainers)

**Comment by kjambunathan** [comment]
> If you are using this feature, remember to include col alignment cookie.

I have added a [workaround](https://github.com/kjambunathan/org-mode-ox-odt/commit/851b588dd80b5d59caa6ea9972cf2e6a54eb3620).  Col alignment cookies are ignored in list tables.  This done, it would still be a good idea to forward the issue to Org mode maintainers and request a fix.

**Comment by QiangF** [comment]
p-style for table is not working. The test file is:
https://gist.githubusercontent.com/QiangF/9470d09290bb80e6286270b365d8a06a/raw/6cd5c9e13ebcb182f1f931f82e94a181fe71b657/table_style.org

**Comment by kjambunathan** [comment]
> p-style for table is not working. The test file is:
https://gist.githubusercontent.com/QiangF/9470d09290bb80e6286270b365d8a06a/raw/6cd5c9e13ebcb182f1f931f82e94a181fe71b657/table_style.org

Try this

```
#+ODT_EXTRA_STYLES: <style:style style:name="Text_20_body_small" style:family="paragraph" style:parent-style-name="Text_20_body">
#+ODT_EXTRA_STYLES:   <style:text-properties fo:font-size="50%"/>
#+ODT_EXTRA_STYLES: </style:style>

#+ODT_EXTRA_STYLES: <style:style style:name="MyOrgTableContents" style:family="paragraph" style:parent-style-name="Text_20_body_small"/>
#+ODT_EXTRA_STYLES: <style:style style:name="MyOrgTableHeading" style:family="paragraph" style:parent-style-name="MyOrgTableContents" style:class="extra">
#+ODT_EXTRA_STYLES:   <style:text-properties fo:font-weight="bold"/>
#+ODT_EXTRA_STYLES: </style:style>

* Table 2

#+ATTR_ODT: :p-style "MyOrgTable"
|  <r> | <c>  | <l>  |
| aaaa | bbbb | cccc |
|------+------+------|
| dddd | eeee | ffff |
| gggg | hhhh | iiii |
```
