### ISSUE TITLE
bug when try to export a large table that uses vmax (and the new alias)

### ISSUE THREAD

**Issue by ouboub** [kjambunathan/org-mode-ox-odt#255]
Hi

I cannot convert the following table (which is now a serious problem)
```
#+Name: propuesta-pad
| Nombre | Q1 | PesoQ1 | Q2 | PesoQ2 | Q3 | PesoQ3 | PubRes | PubScl3 | ProyNac | PesoPrNac | ProyEu | PesoEU | ProyAut | PesoAut | ProyTot | ProySca1 | CongInter | PesoCongInter | CongNac | PesoCongNac | Conf | PesoConf | Sem | PesoSem | Conftot | ConfSca1 | InvTot3 |
|--------+----+--------+----+--------+----+--------+--------+---------+---------+-----------+--------+--------+---------+---------+---------+----------+-----------+---------------+---------+-------------+------+----------+-----+---------+---------+----------+---------|
| User   |  2 |      1 |  1 |   0.75 |  0 |    0.5 |   2.75 |    0.80 |       2 |       0.5 |      0 |   0.75 |       0 |    0.25 |    1.00 |     0.67 |         0 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.00 |      0.0 |    1.47 |
| User   |  2 |      1 |  0 |   0.75 |  0 |    0.5 |   2.00 |    0.59 |       0 |       0.5 |      0 |   0.75 |       0 |    0.25 |    0.00 |     0.00 |         0 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.00 |      0.0 |    0.59 |
| User   |  0 |      1 |  0 |   0.75 |  0 |    0.5 |   0.00 |    0.00 |       0 |       0.5 |      0 |   0.75 |       0 |    0.25 |    0.00 |     0.00 |         0 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.00 |      0.0 |    0.00 |
| User   |  0 |      1 |  3 |   0.75 |  0 |    0.5 |   2.25 |    0.66 |       0 |       0.5 |      0 |   0.75 |       0 |    0.25 |    0.00 |     0.00 |         1 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.10 |      0.0 |    0.66 |
| User   |  0 |      1 |  0 |   0.75 |  0 |    0.5 |   0.00 |    0.00 |       0 |       0.5 |      0 |   0.75 |       0 |    0.25 |    0.00 |     0.00 |         0 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.00 |      0.0 |    0.00 |
| User   |  5 |      1 |  3 |   0.75 |  0 |    0.5 |   7.25 |    2.12 |       3 |       0.5 |      0 |   0.75 |       0 |    0.25 |    1.50 |     1.00 |         3 |           0.1 |      24 |        0.05 |    0 |     0.05 |   0 |    0.05 |    1.50 |      1.0 |    4.12 |
| User   |  1 |      1 |  0 |   0.75 |  0 |    0.5 |   1.00 |    0.29 |       0 |       0.5 |      0 |   0.75 |       0 |    0.25 |    0.00 |     0.00 |         0 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.00 |      0.0 |    0.29 |
| User   |  0 |      1 |  0 |   0.75 |  0 |    0.5 |   0.00 |    0.00 |       0 |       0.5 |      0 |   0.75 |       0 |    0.25 |    0.00 |     0.00 |         0 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.00 |      0.0 |    0.00 |
| User   |  7 |      1 |  3 |   0.75 |  2 |    0.5 |  10.25 |    3.00 |       2 |       0.5 |      0 |   0.75 |       0 |    0.25 |    1.00 |     0.67 |         2 |           0.1 |       6 |        0.05 |    6 |     0.05 |   2 |    0.05 |    0.90 |     0.67 |    4.34 |
| User   |  2 |      1 |  0 |   0.75 |  2 |    0.5 |   3.00 |    0.88 |       0 |       0.5 |      0 |   0.75 |       0 |    0.25 |    0.00 |     0.00 |         0 |           0.1 |       0 |        0.05 |    0 |     0.05 |   0 |    0.05 |    0.00 |      0.0 |    0.88 |
#+TBLFM: $8=$2*$3+$4*$5+$6*$7;f2::$9=($8/vmax(@2$8..@11$8))*3;f2::$16=$10*$11+$12*$13+$14*$15;f2::$17=$16/vmax(@2$16..@11$16);f2::$26=$18*$19+$20*$21+$22*$23+$24*$25;f2::$28=$9+$17+$27;f2
#+END:
```

the formula seem all correct, however I obtain the following error:

```
Quit
previous-line: Beginning of buffer [8 times]
Saving file /home/oub/UCM-Ay_Doc23/HG-Candidatos/bug.org...
Wrote /home/oub/UCM-Ay_Doc23/HG-Candidatos/bug.org
‘org-odt-extra-styles’ and ‘org-ods-automatic-styles’ is updated for this session
ODT Zip Dir is /tmp/odt-YLCp84/
Formatting LaTeX using mathml
org-ods-encode-digit: Invalid digit 27
```
although I have set debug-on-error to t, 
I did not obain a useful debug message

**Comment by kjambunathan** [comment]
org-ods-encode-digit: Invalid digit 27


My gut feeling is ...

The $27 in the formula.  May be $27 is beyond Z and becomes AA or some
such thing ...


See if you can bring down the number of cols to less than 26.

**Comment by ouboub** [comment]
>>> "k" == kjn  ***@***.***> writes:

> org-ods-encode-digit: Invalid digit 27
> My gut feeling is ...

> The $27 in the formula.  May be $27 is beyond Z and becomes AA or some
> such thing ...


> See if you can bring down the number of cols to less than 26.

That seems to be the problem, since I deleted all other formula and just left in 

#+TBLFM: $28=$9+$17+$27;f2

And I had the same problems. Oops now I have a real problem since the whole table has even 56 columns

I could split it  into tree, and convert them individually, however I am not sure, what happens if in LO I try to combine via copy and paste the tables, will the formula be correctly transformed?



-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the NATO membership of Ukraine.
I support the EU membership of Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by kjambunathan** [comment]
The table you pasted is taking a lot of time to export on my poor laptop ...  

It is safer to go with the following definition of `org-ods-encode-digit`.

(I am assuming you are having less than 78 cells.)



```
(defun org-ods-encode-digit (digit)
  ;; (append (cl-loop for n from 1 to 26
  ;; 		 for x from ?A to ?Z
  ;; 		 collect (cons n (format "%c" x)))
  ;; 	(cl-loop for n from 27 to 52
  ;; 		 for x from ?A to ?Z
  ;; 		 collect (cons n (format "A%c" x)))
  ;; 	(cl-loop for n from 53 to 78
  ;; 		 for x from ?A to ?Z
  ;; 		 collect (cons n (format "B%c" x)))
  ;; 	)
  (assoc-default digit
		 '((1 . "A") (2 . "B") (3 . "C") (4 . "D") (5 . "E") (6 . "F") (7 . "G")
		   (8 . "H") (9 . "I") (10 . "J") (11 . "K") (12 . "L") (13 . "M")
		   (14 . "N") (15 . "O") (16 . "P") (17 . "Q") (18 . "R") (19 . "S")
		   (20 . "T") (21 . "U") (22 . "V") (23 . "W") (24 . "X") (25 . "Y")
		   (26 . "Z") (27 . "AA") (28 . "AB") (29 . "AC") (30 . "AD")
		   (31 . "AE") (32 . "AF") (33 . "AG") (34 . "AH") (35 . "AI")
		   (36 . "AJ") (37 . "AK") (38 . "AL") (39 . "AM") (40 . "AN")
		   (41 . "AO") (42 . "AP") (43 . "AQ") (44 . "AR") (45 . "AS")
		   (46 . "AT") (47 . "AU") (48 . "AV") (49 . "AW") (50 . "AX")
		   (51 . "AY") (52 . "AZ") (53 . "BA") (54 . "BB") (55 . "BC")
		   (56 . "BD") (57 . "BE") (58 . "BF") (59 . "BG") (60 . "BH")
		   (61 . "BI") (62 . "BJ") (63 . "BK") (64 . "BL") (65 . "BM")
		   (66 . "BN") (67 . "BO") (68 . "BP") (69 . "BQ") (70 . "BR")
		   (71 . "BS") (72 . "BT") (73 . "BU") (74 . "BV") (75 . "BW")
		   (76 . "BX") (77 . "BY") (78 . "BZ"))))
```

**Comment by kjambunathan** [comment]
The table exports successfully and transposed table retains the formula ....  Just use the above definition of `org-ods-encode-digit`.  

## Zip file

[big-table.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/12797207/big-table.zip)



## Screenshots

![big-table-and-big-table-transposed](https://github.com/kjambunathan/org-mode-ox-odt/assets/19869864/245f39c3-bbfc-4a72-a83d-9d7fa73b077f)

**Comment by kjambunathan** [comment]
I will take up the fix for `org-ods-encode-digit ' early tomorrow ...  There is already a `org-ods-encode-digit ', so it should be a minor fix, if I am careful enough to avoid the one-off errors. 

_(It is really really very late here that it is almost tomorrow.  I didn't want to disappoint you when you had a big day coming)_  

I wish you all the best.

**Comment by ouboub** [comment]
>>> "k" == kjn  ***@***.***> writes:

> I will take up the fix for `org-ods-encode-digit ' early tomorrow ...
> There is already a `org-ods-encode-digit ', so it should be a minor
> fix, if I am careful enough to avoid the one-off errors.

> _(It is really really very late here that it is almost tomorrow.  I didn't want to disappoint you when you had a big day coming)_  


Thank you so much. I want to bed a bit worried, and now I am a bit relived. (Still I have not finished). The meeting is at 15:30, so I have still some time


> I wish you all the best.

Thanks very much, and sorry for causing so much trouble....
-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the NATO membership of Ukraine.
I support the EU membership of Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by ouboub** [comment]
>>> "k" == kjn  ***@***.***> writes:

> The table you pasted is taking a lot of time to export on my poor laptop ...  

Oos I am really sorry, I thought of uploading it, but you told me, in general, you prefer the code embedded (but of course not that large I presume)
> It is safer to go with the following definition of `org-ods-encode-digit`.


I do, BTW, it I received from the LO list a message telling me that indeed one could split tables in calc, and link them. 

Not that I am going to try that now, just to let you know, in case you didn't know it.

An old time friend (and had-core Excel user) of mine suggested, once I have converted the table to ods/xlsx

    1. To use grouping (as you sent me)

    2. To transpose it (but he finds this more difficult for users of left-to-write languages)


> (I am assuming you are having less than 78 cells.)

I do.

Thanks I will try that out and cross my fingers

> ```
> (defun org-ods-encode-digit (digit)
>   ;; (append (cl-loop for n from 1 to 26
>   ;; 		 for x from ?A to ?Z
>   ;; 		 collect (cons n (format "%c" x)))
>   ;; 	(cl-loop for n from 27 to 52
>   ;; 		 for x from ?A to ?Z
>   ;; 		 collect (cons n (format "A%c" x)))
>   ;; 	(cl-loop for n from 53 to 78
>   ;; 		 for x from ?A to ?Z
>   ;; 		 collect (cons n (format "B%c" x)))
>   ;; 	)
>   (assoc-default digit
> 		 '((1 . "A") (2 . "B") (3 . "C") (4 . "D") (5 . "E") (6 . "F") (7 . "G")
> 		   (8 . "H") (9 . "I") (10 . "J") (11 . "K") (12 . "L") (13 . "M")
> 		   (14 . "N") (15 . "O") (16 . "P") (17 . "Q") (18 . "R") (19 . "S")
> 		   (20 . "T") (21 . "U") (22 . "V") (23 . "W") (24 . "X") (25 . "Y")
> 		   (26 . "Z") (27 . "AA") (28 . "AB") (29 . "AC") (30 . "AD")
> 		   (31 . "AE") (32 . "AF") (33 . "AG") (34 . "AH") (35 . "AI")
> 		   (36 . "AJ") (37 . "AK") (38 . "AL") (39 . "AM") (40 . "AN")
> 		   (41 . "AO") (42 . "AP") (43 . "AQ") (44 . "AR") (45 . "AS")
> 		   (46 . "AT") (47 . "AU") (48 . "AV") (49 . "AW") (50 . "AX")
> 		   (51 . "AY") (52 . "AZ") (53 . "BA") (54 . "BB") (55 . "BC")
> 		   (56 . "BD") (57 . "BE") (58 . "BF") (59 . "BG") (60 . "BH")
> 		   (61 . "BI") (62 . "BJ") (63 . "BK") (64 . "BL") (65 . "BM")
> 		   (66 . "BN") (67 . "BO") (68 . "BP") (69 . "BQ") (70 . "BR")
> 		   (71 . "BS") (72 . "BT") (73 . "BU") (74 . "BV") (75 . "BW")
> 		   (76 . "BX") (77 . "BY") (78 . "BZ"))))
> ```

**Comment by ouboub** [comment]
>>> "k" == kjn  ***@***.***> writes:

> The table you pasted is taking a lot of time to export on my poor laptop ...  
> It is safer to go with the following definition of `org-ods-encode-digit`.

> (I am assuming you are having less than 78 cells.)


I just want to tell you that worked! Great, now I have to fiddle a bit more and make the final export. What a relive. Thanks again

**Comment by kjambunathan** [comment]
> I do, BTW, it I received from the LO list a message telling me that indeed one could split tables in calc, and link them. Not that I am going to try that now, just to let you know, in case you didn't know it.

I think you are referring to  [[Re: [libreoffice-users] split a huge table in subtables (say on different sheets) and link some columns between these tables](https://listarchives.tdf.io/i/MBeEE3J8Q4JsFs1d_n3a44QG)](https://listarchives.libreoffice.org/global/users/2023/msg00700.html)

Create a bug report ...  

Please include **_both_** the `Org' TBLFM formula and the corresponding LO Excel/Calc formula in your example

**_(I will take up the task of assessing or improving the mapping from TBLFM to Calc Formula)_**
