### ISSUE TITLE
Add left and right aligned text paragraph styles

### ISSUE THREAD

**Issue by bzindovic** [kjambunathan/org-mode-ox-odt#26]
It would be nice to have styles for left and right aligned paragraphs, similar to html exporter's support for `#+begin_left #+end_left` and `#+begin_right #+end_right` blocks.

**Comment by kjambunathan** [comment]
> It would be nice to have styles for left and right aligned paragraphs, similar to html exporter's support for #+begin_left #+end_left and #+begin_right #+end_right blocks.

What uses do you have in mind? 

Do you want something like _marginalia_?  

Or you are writing a letter or an author's preface or quoting another source and you want to "right align" the author's name and source.

If you attach a sample _docx_ or _odt_ file, with the formatting that you need, it would help me immensely.

**Comment by bzindovic** [comment]
I don't have the marginalia in mind but a regular text content for reports and legal docs. For instance, some documents require addressing it to a specific institution, sector and/or person at the top of the page. This text is usually less than a line long but can be aligned to the left, to the right or centered (depending on the required format).

Also, these documents require signature of the sender, the date and the location of the sender, this is solved somewhat differently: date and location are left aligned while signer name is right aligned. The easiest solution is to put this in a table but it can be clunky. The easiest solution in Word/Writer is to use left and right tab.

I've attached the Word docs file (Github seems not to support attaching LO Writer files via web interface) and the first problem I have is given at the top (first two lines in this example are left aligned). The second problem is usually located after the main text (in this example it is the last line).

[Legal_doc_example.docx](https://github.com/kjambunathan/org-mode-ox-odt/files/1420147/Legal_doc_example.docx)

I've attached the example without using styles just to keep things as simple as possible. I presume that I can use [custom, one-off styles in ODT](http://orgmode.org/manual/Creating-one_002doff-styles.html#Creating-one_002doff-styles) but these are too verbose and distract a lot.

What is the easiest way to solve these two issues?

**Comment by kjambunathan** [comment]
I have added the feature your requested as part of commit https://github.com/kjambunathan/org-mode-ox-odt/commit/c397ae4f69e2ba2fefd0c4284cdf97c8d834b873


You need to use Verse blocks; not just any verse block, but a Verse with custom paragraph style. 

1. Update the ODT exporter
1.  Download [`Covering Letter.org`](http://s000.tinyupload.com/index.php?file_id=04351428633204397709) 
2. Download [`Covering Letter.ott`](http://s000.tinyupload.com/index.php?file_id=15855606641895420089) and save it  in the same folder as (1)
3. Export it.

In the snippet below,   

3. I use one or more tabs, in the second verse block.  Use `whitespace-mode` within Emacs to verify this. 
1. I use a custom paragraph style called `MyOrgVerse` for the verse block.
2. In the `ott` file, I define a custom paragraphy style `MyOrgVerse`.  This new style inherits from `OrgVerse`, _and_ customizes both the font and tab stop properties.






    #+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
    #+OPTIONS: author:nil broken-links:nil c:nil creator:nil
    #+OPTIONS: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:t
    #+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
    #+OPTIONS: timestamp:t title:nil toc:t todo:t |:t
    #+TITLE: Covering Letter
    #+LANGUAGE: en
    #+SELECT_TAGS: export
    #+EXCLUDE_TAGS: noexport
    #+CREATOR: Emacs 25.2.2 (Org mode 9.0.9)

    #+ODT_STYLES_FILE: "./Covering Letter.ott"

    #+ATTR_ODT: :style "MyOrgVerse"
    #+BEGIN_VERSE
    Elevator Service Inc.
    Training Facility
    #+END_VERSE

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
    scelerisque mollis viverra. Morbi ac orci in urna tempus
    tincidunt. Morbi hendrerit malesuada nunc sed maximus. Mauris eget
    nisi non neque elementum rhoncus. Aenean et elit sodales, pretium
    massa eu, iaculis velit. 

    Nulla sit amet massa elit. Aliquam quis erat
    dictum, auctor massa euismod, aliquam turpis. Sed ultricies et justo a
    tempor. Nam et eleifend odio, ac vestibulum sem. Cras tempus, tortor
    molestie accumsan fringilla, tortor ex posuere nunc, nec tempus enim
    magna a mauris.

    #+ATTR_ODT: :style "MyOrgVerse"
    #+BEGIN_VERSE
    Oct 27, 2017				Jambunathan K
    Bangalore
    #+END_VERSE

**Comment by kjambunathan** [comment]
> You need to use Verse blocks; not just any verse block, but a Verse with custom paragraph style.

In `Org`, Verse blocks are paragraphs that preserve line breaks, tabs etc.  So, you can achieve what you want with

    #+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
    #+OPTIONS: author:nil broken-links:nil c:nil creator:nil
    #+OPTIONS: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:t
    #+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
    #+OPTIONS: timestamp:t title:nil toc:t todo:t |:t
    #+TITLE: Covering Letter
    #+LANGUAGE: en
    #+SELECT_TAGS: export
    #+EXCLUDE_TAGS: noexport
    #+CREATOR: Emacs 25.2.2 (Org mode 9.0.9)

    #+MACRO: tab (eval (mapconcat #'identity (make-list $1 "@@odt:<text:tab/>@@") ""))

    /*Elevator Service Inc.*/\\
    /*Training Facility*/

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
    scelerisque mollis viverra. Morbi ac orci in urna tempus
    tincidunt. Morbi hendrerit malesuada nunc sed maximus. Mauris eget
    nisi non neque elementum rhoncus. Aenean et elit sodales, pretium
    massa eu, iaculis velit. 

    Nulla sit amet massa elit. Aliquam quis erat
    dictum, auctor massa euismod, aliquam turpis. Sed ultricies et justo a
    tempor. Nam et eleifend odio, ac vestibulum sem. Cras tempus, tortor
    molestie accumsan fringilla, tortor ex posuere nunc, nec tempus enim
    magna a mauris.

    /*Oct 27, 2017*/ {{{tab(4)}}} /*Jambunathan K*/\\
    /*Bangalore*/ @@odt:<text:tab/>@@@@odt:<text:tab/>@@@@odt:<text:tab/>@@@@odt:<text:tab/>@@ /*Author, ODT Exporter*/

**Comment by bzindovic** [comment]
Superb, that's exactly the solution I was looking for. Thank you for all the help.

With kind regards.
