### ISSUE TITLE
Table border line not shown for GriddedTable

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#28]
Example:
    #+attr_odt: :style GriddedTable
    |1|2|

The desired effect is

![img_2017_10_17__02_47_33](https://user-images.githubusercontent.com/8192731/31650354-88d5a552-b349-11e7-9fa2-42e5d7e7fca6.png)

**Comment by kjambunathan** [comment]
> #+attr_odt: :style GriddedTable

Quote the style name. i.e., Use

    #+attr_odt: :style "GriddedTable"
