### ISSUE TITLE
Feature request: add attr_odt for paragraph

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#29]
The property that can be changed includes style name, font name, font size and
alignment. This will enable the user to create ad-hoc paragraph styles easier
and to get rid of the extra line introduce by "#+pagebreak", such as in the
following demo code:

    #+odt: <style:style style:name="pagebreak-paragraph-style"
    #+odt: style:family="paragraph"
    #+odt: style:parent-style-name="default-paragraph-style"
    #+odt: style:master-page-name="Standard">
    #+odt: <style:paragraph-properties style:page-number="auto"
    #+odt: fo:break-before="auto" fo:break-after="auto"/>

    hello,

    #+attr_odt: :style "pagebreak-paragraph-style" :align "center"
    #+attr_odt: :font "font-name" :font-size 12
    world!

**Comment by kjambunathan** [comment]
Does this work for you?

    Hello
    #+ATTR_ODT: :style "OrgPageBreakDefault"
    World

**Comment by QiangF** [comment]
This solves the pagebreak problem perfectly for breaking before text, what if
the content following the pagebreak is a figure frame or a table? Maybe adding
an odt_attr: :pagebreak for captioned figure and table?

**Comment by QiangF** [comment]
Also pagebreak in front of a heading doesn't work by specifying :style, example is:

    Hello
    #+ATTR_ODT: :style "OrgPageBreakDefault"
    * World
    Thank you!

**Comment by kjambunathan** [comment]
> Also pagebreak in front of a heading doesn't work by specifying :style, example is:

You can't apply attributes to a outline heading.  You can achieve what you want, by editing the `Heading 1` etc to include page breaks.  See section titled `A new Chapter starts with a new Page`, `page 6` of [Writing a Thesis in OpenOffice.org](http://www.openoffice.org/documentation/HOW_TO/word_processing/How_to_Write_a_Thesis_in_OOo.pdf

**Comment by QiangF** [comment]
But I don't need pagebreak before heading in all places.
Maybe it's a good feature to allow specify heading paragraph format.

**Comment by QiangF** [comment]
Pagebreak is useful in creating presentation slice in odt format. 
The workaround for "#+pagebreak:" would be

    #+attr_odt: :style "tiny-font-paragraph"
    a line of empty spaces

It doesn't look pretty.

**Comment by kjambunathan** [comment]
> Maybe it's a good feature to allow specify heading paragraph format.

Done.  When I export [pagebreak.org](http://s000.tinyupload.com/index.php?file_id=81767957816652759523), I get [pagebreak.odt](http://s000.tinyupload.com/index.php?file_id=00521834132296241514).

_*Comments on `org` snippet*_:  `Org` distinguishes between outline headings and paragraphs.  But LibreOffice, makes no such distinction.  i.e., In LibreOffice, headings are ordinary paragraphs with a different paragraph style.  For example, in the following snippet, the first two _`org` paragraphs_ with styles `Heading_20_1` and `Heading_20_1_With_PageBreak` end up as chapter headings in LibreOffice.  You don't always have to create custom heading styles for beginning a chapter on a new page.  You can apply `MyPageBreakAfter` paragraph style to the last paragraph of the previous chapter, to create a page break before the current chapter.   Needless to say, this later expedient will backfire if you shuffle text in the `org` file.

```
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: hello
#+DATE: <2017-11-05 Sun>
#+AUTHOR: Jambunathan K
#+EMAIL: kjambunathan@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.2.2 (Org mode 9.0.9)

#+ODT_AUTOMATIC_STYLES: <style:style style:name="Heading_20_1_With_PageBreak" style:family="paragraph" style:parent-style-name="Heading_20_1">
#+ODT_AUTOMATIC_STYLES:  <style:paragraph-properties fo:break-before="page"/>
#+ODT_AUTOMATIC_STYLES:  <style:text-properties officeooo:paragraph-rsid="000e05d7"/>
#+ODT_AUTOMATIC_STYLES: </style:style>

#+ODT_AUTOMATIC_STYLES: <style:style style:name="MyPageBreakBefore" style:family="paragraph" style:parent-style-name="Text_20_body">
#+ODT_AUTOMATIC_STYLES:  <style:paragraph-properties fo:break-before="page"/>
#+ODT_AUTOMATIC_STYLES: </style:style>

#+ODT_AUTOMATIC_STYLES: <style:style style:name="MyPageBreakAfter" style:family="paragraph" style:parent-style-name="Text_20_body">
#+ODT_AUTOMATIC_STYLES:  <style:paragraph-properties fo:break-after="page"/>
#+ODT_AUTOMATIC_STYLES: </style:style>

#+ATTR_ODT: :style "Heading_20_1"
Donec hendrerit tempor tellus

Nullam eu ante vel est convallis dignissim.  Fusce suscipit, wisi nec
facilisis facilisis, est dui fermentum leo, quis tempor ligula erat
quis odio.  Nunc porta vulputate tellus.  Nunc rutrum turpis sed pede.
Sed bibendum.

#+ATTR_ODT: :style "Heading_20_1_With_PageBreak"
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus

#+ATTR_ODT: :style "MyPageBreakAfter"
Nullam eu ante vel est convallis dignissim.  Fusce suscipit, wisi nec
facilisis facilisis, est dui fermentum leo, quis tempor ligula erat
quis odio.  Nunc porta vulputate tellus.  Nunc rutrum turpis sed pede.
Sed bibendum.

* Donec vitae dolor

Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non
orci commodo lobortis.  Proin neque massa, cursus ut, gravida ut,
lobortis eget, lacus.  Sed diam.

#+ATTR_ODT: :style "MyPageBreakBefore"
Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam.
Etiam vel tortor sodales tellus ultricies commodo.  Suspendisse
potenti.  Aenean in sem ac leo mollis blandit.

* Nullam eu ante vel est convallis dignissim
  :PROPERTIES:
  :ATTR_ODT:  :style-suffix "_unnumbered"
  :END:

Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non
orci commodo lobortis.  Proin neque massa, cursus ut, gravida ut,
lobortis eget, lacus.  Sed diam.
```

**Comment by kjambunathan** [comment]
With the new commits, the below magic is no longer needed.

```
#+ODT_AUTOMATIC_STYLES: <style:style style:name="Heading_20_1_With_PageBreak" style:family="paragraph" style:parent-style-name="Heading_20_1">
#+ODT_AUTOMATIC_STYLES:  <style:paragraph-properties fo:break-before="page"/>
#+ODT_AUTOMATIC_STYLES:  <style:text-properties officeooo:paragraph-rsid="000e05d7"/>
#+ODT_AUTOMATIC_STYLES: </style:style>

#+ODT_AUTOMATIC_STYLES: <style:style style:name="MyPageBreakBefore" style:family="paragraph" style:parent-style-name="Text_20_body">
#+ODT_AUTOMATIC_STYLES:  <style:paragraph-properties fo:break-before="page"/>
#+ODT_AUTOMATIC_STYLES: </style:style>

#+ODT_AUTOMATIC_STYLES: <style:style style:name="MyPageBreakAfter" style:family="paragraph" style:parent-style-name="Text_20_body">
#+ODT_AUTOMATIC_STYLES:  <style:paragraph-properties fo:break-after="page"/>
#+ODT_AUTOMATIC_STYLES: </style:style>
```

I have re-defined  `#+PAGEBREAK: ` to insert a page break _after_ the paragraph.  An empty paragraph at the end of the page, is not quite  as ugly as an empty paragraph at the beginning of the page.
