### ISSUE TITLE
Feature request: allow image to be linked instead of embeded

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#3]
When I use org-dot exporter to write a document, often I need to expor several times to see how it looks, insert image by linking probably will be more efficient in this case. Mabe add another document option like,

    :embed t

**Comment by kjambunathan** [comment]
> When I use org-dot exporter to write a document, often I need to expor several times to see how it looks, insert image by linking probably will be more efficient in this case.

Why do you think embedding images  right within the `odt` file takes  _much_ time?  If you suspect export is slow, I suggest that you do some _profiling_ to identify the bottlenecks.  For now, I am closing this bug.
