### ISSUE TITLE
Feature request: a better way of using user defined style file

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#34]
Currently the user can specify a customised style file with
"#+odt_styles_file:". A xml file is better suited than a customised ott template
file, because plain text is easier to see the changes. To make the odt exporter
work, the customised style file needs to includes most of the supplied default
style file. But the customisation only happens in a few element.

A better way is to add another document property,  ""#+odt_user_styles_file:",
the file will include three element for each kind of styles like:

    <office:styles>
        user's redefinition of element
    </office:styles>

    <office:automatic-styles>
        user's redefinition of element
    </office:automatic-styles>

    <office:master-styles>
        user's redefinition of element
    </office:master-styles>

Then during the export, the "user's redefinition of element" is appended to the
end of the corresponding element to override the default definition (the last
definition takes effect for duplicate element in xml), eg. for <office:styles>,
that content is inserted before the closing tag </office:styles>. Alternativly,
the xml include mechanism can be used.

This way, the user managed style file is free of the unnecessary clutter and
easier to manage.

**Comment by kjambunathan** [comment]
You can use an  `xml` file, that overrides [the default styles file](etc/styles/OrgOdtStyles.xml).  Just put the styles  you need right in that file.

`C-h v org-odt-styles-file` says  ...

```
Default styles file for use with ODT export.
Valid values are one of:
1. nil
2. path to a styles.xml file
3. path to a *.odt or a *.ott file
...
```

**Comment by QiangF** [comment]
But there can be only one style file, what I am suggesting is seperating the as
provided style file (the xml in the etc folder) with a user defined file, but
combine the two before exporting. I am trying with xinclude by inserting the
following in the provided style file. 

    <xi:include href="./my_styles.xml" xmlns:xi="http://www.w3.org/2001/XInclude"/>

But I can't get it to work.

**Comment by kjambunathan** [comment]
> But there can be only one style file, what I am suggesting is seperating the as
provided style file (the xml in the etc folder) with a user defined file, but
combine the two before exporting. I am trying with xinclude by inserting the
following in the provided style file.

> `<xi:include href="./my_styles.xml" xmlns:xi="http://www.w3.org/2001/XInclude"/>`

> But I can't get it to work.

Use `xmllint' and `xsltproc.  

What you want to do is _transform_ the  default `OrgOdtStyles.xml` to something else.  So, you need  `xsltproc`.  Since, you want to `xinclude` the styles, you need to use  `xmllint`.  

For example, with a shell command like this

```
xmllint --xinclude transform.xsl | xsltproc --output MyOrgOdtStyles.xml  - OrgOdtStyles.xml 
```

and with the following `transform.xsl`,

```
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
		xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
		xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
		xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
		xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
		xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
		xmlns:xlink="http://www.w3.org/1999/xlink"
		xmlns:dc="http://purl.org/dc/elements/1.1/"
		xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
		xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0"
		xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
		xmlns:chart="urn:oasis:names:tc:opendocument:xmlns:chart:1.0"
		xmlns:dr3d="urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0"
		xmlns:math="http://www.w3.org/1998/Math/MathML"
		xmlns:form="urn:oasis:names:tc:opendocument:xmlns:form:1.0"
		xmlns:script="urn:oasis:names:tc:opendocument:xmlns:script:1.0"
		xmlns:ooo="http://openoffice.org/2004/office"
		xmlns:ooow="http://openoffice.org/2004/writer"
		xmlns:oooc="http://openoffice.org/2004/calc"
		xmlns:dom="http://www.w3.org/2001/xml-events"
		xmlns:rpt="http://openoffice.org/2005/report"
		xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2"
		xmlns:xhtml="http://www.w3.org/1999/xhtml"
		xmlns:grddl="http://www.w3.org/2003/g/data-view#"
		>
  <!-- IdentityTransform -->
  <xsl:template match="/ | @* | node()">
    <xsl:copy>
      <xsl:apply-templates select="@* | node()" />
    </xsl:copy>
  </xsl:template>

  <xsl:template match="office:styles" >
    <office:styles>
      <xsl:copy-of select="node()"/>
      <xi:include href="my-extra-styles.xml" xmlns:xi="http://www.w3.org/2001/XInclude" xpointer="xpointer(id('these')/*)"/>
    </office:styles>
  </xsl:template>
</xsl:stylesheet>
```

you would put your additional styles  in the file `my-extra-styles.xml`, which would look like,

```
<document xmlns:anim = "urn:oasis:names:tc:opendocument:xmlns:animation:1.0"
	  xmlns:chart = "urn:oasis:names:tc:opendocument:xmlns:chart:1.0"
	  xmlns:config = "urn:oasis:names:tc:opendocument:xmlns:config:1.0"
	  xmlns:db = "urn:oasis:names:tc:opendocument:xmlns:database:1.0"
	  xmlns:dc = "http://purl.org/dc/elements/1.1/"
	  xmlns:dr3d = "urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0"
	  xmlns:draw = "urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
	  xmlns:fo = "urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
	  xmlns:form = "urn:oasis:names:tc:opendocument:xmlns:form:1.0"
	  xmlns:grddl = "http://www.w3.org/2003/g/data-view#"
	  xmlns:math = "http://www.w3.org/1998/Math/MathML"
	  xmlns:meta = "urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
	  xmlns:number = "urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0"
	  xmlns:office = "urn:oasis:names:tc:opendocument:xmlns:office:1.0"
	  xmlns:presentation = "urn:oasis:names:tc:opendocument:xmlns:presentation:1.0"
	  xmlns:script = "urn:oasis:names:tc:opendocument:xmlns:script:1.0"
	  xmlns:smil = "urn:oasis:names:tc:opendocument:xmlns:smil-compatible:1.0"
	  xmlns:style = "urn:oasis:names:tc:opendocument:xmlns:style:1.0"
	  xmlns:svg = "urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
	  xmlns:table = "urn:oasis:names:tc:opendocument:xmlns:table:1.0"
	  xmlns:text = "urn:oasis:names:tc:opendocument:xmlns:text:1.0"
	  xmlns:xforms = "http://www.w3.org/2002/xforms"
	  xmlns:xhtml = "http://www.w3.org/1999/xhtml"
	  xmlns:xlink = "http://www.w3.org/1999/xlink">
  <mystyles xml:id="these">
    <style:style style:name="Heading_20_1_With_PageBreak" style:family="paragraph" style:parent-style-name="Heading_20_1">
      <style:paragraph-properties fo:break-before="page"/>
    </style:style>
    <style:style style:name="MyPageBreakBefore" style:family="paragraph" style:parent-style-name="Text_20_body">
      <style:paragraph-properties fo:break-before="page"/>
    </style:style>
    <style:style style:name="MyPageBreakAfter" style:family="paragraph" style:parent-style-name="Text_20_body">
      <style:paragraph-properties fo:break-after="page"/>
    </style:style>
  </mystyles>
</document>
```

I find all the above steps tedious and complex.  I wonder why you want to go with `xinclude` ...?

**Comment by QiangF** [comment]
What I am trying to achieve is just a few customised style files, but only a few
styles have been changed compare to the default OrgOdtStyles.xml in the
repo. For example, in the style file for a presentation only the master page
size need to be changed, and for report style file may be just a different line
spacing.

I can do that with an ott template file, but the change is not easily
spotted. And if you release a new version of OrgOdtStyles.xml that change the
style name from "Heading_1" to "heading_1", and I need to make a new style
template all over again.

With the xinclude way, I can put all my change in a small file, easy to manange
and adapt to changes.
