### ISSUE TITLE
Help: case, headline, t are not known to be defined

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#35]
I recently installed Debian 9 with emacs 25, and I cloned this repo and run the
command "make compile" in the repo's root folder. The result shows that three
functions are missing. Here is the log output:

    q@debian org-mode-ox-odt$ make compile
    make -C doc clean;  make -C lisp clean;
    fatal: No names found, cannot describe anything.
    fatal: No names found, cannot describe anything.
    fatal: No names found, cannot describe anything.
    fatal: No names found, cannot describe anything.
    make[1]: Entering directory '/home/q/.emacs.d/org-mode-ox-odt/doc'
    rm -f org *.pdf *.html *_letter.tex org-version.inc org-version.tex \
        *.aux *.cp *.cps *.dvi *.fn *.fns *.ky *.kys *.pg *.pgs \
        *.toc *.tp *.tps *.vr *.vrs *.log *.html *.ps
    make[1]: Leaving directory '/home/q/.emacs.d/org-mode-ox-odt/doc'
    make[1]: Entering directory '/home/q/.emacs.d/org-mode-ox-odt/lisp'
    rm -f org-version.el org-loaddefs.el org-version.elc org-loaddefs.elc org-install.elc
    rm -f *.elc
    make[1]: Leaving directory '/home/q/.emacs.d/org-mode-ox-odt/lisp'
    make -C lisp compile
    fatal: No names found, cannot describe anything.
    fatal: No names found, cannot describe anything.
    fatal: No names found, cannot describe anything.
    fatal: No names found, cannot describe anything.
    make[1]: Entering directory '/home/q/.emacs.d/org-mode-ox-odt/lisp'
    rm -f org-version.el org-loaddefs.el org-version.elc org-loaddefs.elc org-install.elc
    org-version:  ()
    Loading /home/q/.emacs.d/org-mode-ox-odt/lisp/org-compat.el (source)...
    Loading /home/q/.emacs.d/org-mode-ox-odt/mk/org-fixup.el (source)...
    org-loaddefs:  ()
    Loading /home/q/.emacs.d/org-mode-ox-odt/lisp/org-compat.el (source)...
    Loading /home/q/.emacs.d/org-mode-ox-odt/mk/org-fixup.el (source)...
    Making generated-autoload-file local to  *autoload-file* while let-bound!
    make compile-dirall
    make[2]: Entering directory '/home/q/.emacs.d/org-mode-ox-odt/lisp'
    ==================== dirall ====================
    Checking /home/q/.emacs.d/org-mode-ox-odt/lisp...
    Compiling /home/q/.emacs.d/org-mode-ox-odt/lisp/ob-C.el...
    In org-odt--read-attribute:
    ox-odt.el:1335:59:Warning: ‘t’ called as a function

    In end of data:
    ox-odt.el:5438:1:Warning: the following functions are not known to be defined:
        case, headline, t
    Compiling /home/q/.emacs.d/org-mode-ox-odt/lisp/ox.el...
    Done (Total of 117 files compiled, 3 skipped)

**Comment by kjambunathan** [comment]
> Help: case, headline, t are not known to be defined

Thanks for the report.  I have fixed this error.
