### ISSUE TITLE
Temporary directory doesn't exist error

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#36]
The relevant line is:

    delete-directory: Opening directory: directory doesn't exist, /tmp/odt-3024G5B

This is the full *Message* output:

    Formatting LaTeX using mathml
    (ox-jabref): Bib file:  nil
    (ox-jabref): Citation style: Numeric
    Wrote /tmp/odt-3024G5B/meta.xml
    Using schema ~/.emacs.d/org-mode-ox-odt/etc/schema/od-schema-v1.2-os.rnc [2 times]
    Saving file /tmp/odt-3024G5B/styles.xml...
    Wrote /tmp/odt-3024G5B/styles.xml
    Using vacuous schema
    Wrote /tmp/odt-3024G5B/mimetype
    Using vacuous schema
    Indenting region...done
    Saving file /tmp/odt-3024G5B/META-INF/manifest.xml...
    Wrote /tmp/odt-3024G5B/META-INF/manifest.xml
    Indenting region...done
    Saving file /tmp/odt-3024G5B/content.xml...
    Wrote /tmp/odt-3024G5B/content.xml
    Indenting region...done
    Saving file /tmp/odt-3024G5B/styles.xml...
    Wrote /tmp/odt-3024G5B/styles.xml
    Creating ODT file...
    Running zip -mX0 test.odt mimetype
    Running zip -rmTq test.odt .
    Created /home/q/Documents/odt/test.odt
    Applying Transformation: optimise table column width
    Running soffice --norestore --invisible --headless macro:///OrgMode.Utilities.OptimizeColumnWidth(file:///home/q/Documents/odt/test.odt)
    delete-directory: Opening directory: 没有那个文件或目录, /tmp/odt-3024G5B

**Comment by kjambunathan** [comment]
> Temporary directory doesn't exist error 

Did you make some changes to `ox-odt.el` and you _RELOADED_ it for the second time?  

If yes, as a workaround, don't load `ox-odt.el` more than once in a given Emacs session i.e., If you want to test some local changes to `ox-odt.el`, compile the file and restart your Emacs.  If you do this, you won't run  in to the above error.

I have not looked in to this issue, even though, I used to run in to this error very often.  It used to confuse me a lot.  But once I started doing what I suggested in the previous paragraph, the problem stopped happening.


That said ... the issue you reported is in my radar.  I will look in to it, when i have some time.

**Comment by QiangF** [comment]
No. I did a fresh pull and run make in the root folder. Then set the path with:

    (require 'cl) ;remove-if is in cl library
    (require 'cl-lib)
    (setq load-path (remove-if (lambda (x) (string-match-p "org$" x)) load-path)) ; remove emacs default org from load path
    (setq package-enable-at-startup nil   ; To prevent initialising twice
    package-user-dir "~/.emacs.d/elpa/")
    (add-to-list 'load-path "~/.emacs.d/extra")
    (cl-pushnew "~/.emacs.d/org-mode-ox-odt/lisp/" load-path)
    (cl-pushnew "~/.emacs.d/org-mode-ox-odt/contrib/lisp/" load-path)

In Emacs 24, everything works. Probably due to my update to emacs 25.

**Comment by QiangF** [comment]
I must be a terrible user. I installed the latest libreoffice manually, and
didn't add it to the path. The error disappears after doing so. I am sorry!
