### ISSUE TITLE
Feature request: make org-odt-styles-dir a keyword?

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#37]
Section styles only work in the automatic styles section of
 odt-content-template-file. I mean section definition like:

    <style:style style:name="three_columns" style:family="section">
    <style:section-properties fo:background-color="#ffffff" style:editable="false">
    <style:columns fo:column-count="3" fo:column-gap="0.2cm"/>
    </style:section-properties>
    </style:style>

So the customization have to include both the content template file and the style
file. Will it be better to add an keyword like:

    #+org_odt_styles_dir:

So I can specify all styles using one line.
The other approach is to use file local variables, but it needs to be in the end
of the file which may cause inconveniences during editing.

**Comment by kjambunathan** [comment]
There are two options.

1. To add styles to content template file, you can use [#+ODT_AUTOMATIC_STYLES](https://github.com/kjambunathan/org-mode-ox-odt/issues/31#issuecomment-341315823).

2. To add styles to styles file, you can use [#+ODT_EXTRA_STYLES](https://github.com/kjambunathan/org-mode-ox-odt/issues/24#issuecomment-348683880)

In your specific case, use option (1).

**Comment by QiangF** [comment]
Option 1 puts reusable code into every file, I have create a script that can make pure text based style file creation easier.  https://github.com/QiangF/my_odt_style
I will try the local variable option.

**Comment by QiangF** [comment]
I have solved the probelm by put file-local-variable at the front of the file

    # -*- org-odt-styles-dir: "~/Document/odt/text"; -*-

**Comment by QiangF** [comment]
OK, I see, section definition in OrgOdtStyles.xml and OrgOdtContentTemplate.xml
are not exported.

**Comment by kjambunathan** [comment]
> I have solved the probelm by put file-local-variable at the front of the file
> # -*- org-odt-styles-dir: "~/Document/odt/text"; -*-
> The file local variable is not in effect.

Your comment here tells me that you haven't tried one of my earlier responses here: https://github.com/kjambunathan/org-mode-ox-odt/issues/34

Use

```
#+ODT_STYLES_FILE: "/my/styles/file.xml"
```

to specify your own styles file (and directory).   Remember, to terminate the file with an `xml` extension.

All the templates here https://github.com/QiangF/my_odt_style/tree/master/templates are `document-styles` and you need to try my suggested option, before opening any feature requests.


(Also, please don't  _close_ an issue and _then_ add a comment.  It confuses me whether are not my response satisfied your needs)

**Comment by QiangF** [comment]
The problem is the section definition in #+odt_styles_file is not used. It needs to be put in the automatic styles file.

**Comment by kjambunathan** [comment]
Use 

```
#+ODT_STYLES_FILE: "/my/styles/file.xml"
#+ODT_CONTENT_TEMPLATE_FILE: "/my/content/template/file.xml"
```
