### ISSUE TITLE
Question: how to create a centered as-char image frame using a custom style

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#38]
There is a know issue of as-char frame vs paragraph anchored frame, and as-char
is the solution. Currently I have to use template like:

    #+begin_section
    #+begin_center
    #+attr_odt: :anchor "as-char" 
    [[image]]
    #+end_center
    #+end_section

Thre are 3 problems:
1. #+begin_center and #+end_center may get mismatched during copying around.
2. the caption is not centered.
3. the frame is inside a paragraph with paragraph style set as "Text_20_body",
   if the style contains indentations, the image is not centered.
   
I am trying to get the the image centered with a style, here is the snippet I am
working on:

    #+odt_automatic_styles: <style:style style:name="two_columns" style:family="section">
    #+odt_automatic_styles:  <style:section-properties fo:background-color="#ffff99" style:editable="false">
    #+odt_automatic_styles:   <style:columns fo:column-count="2" fo:column-gap="0.1cm"/>
    #+odt_automatic_styles:  </style:section-properties>
    #+odt_automatic_styles: </style:style>

    #+odt_extra_styles:  <style:style style:name="center_image" style:family="paragraph" style:parent-style-name="Standard">
    #+odt_extra_styles:   <style:paragraph-properties fo:margin-top="0.0cm"
    #+odt_extra_styles:                               fo:margin-bottom="0.0cm"
    #+odt_extra_styles:                               fo:text-align="center"
    #+odt_extra_styles:                               fo:line-height="100%"
    #+odt_extra_styles:                               style:justify-single-word="false">
    #+odt_extra_styles:   </style:paragraph-properties>
    #+odt_extra_styles:  </style:style>

    * image centered with a center environment

    #+attr_odt: :style "two_columns"
    #+begin_section
    #+begin_center
    #+caption: this is the caption
    #+attr_odt: :width 8.1  :anchor "as-char" 
    [[./org-mode-unicorn.png]]  

    #+caption: this is the caption
    #+attr_odt: :width 8.1  :anchor "as-char" 
    [[./org-mode-unicorn.png]]  
    #+end_center
    #+end_section

    * image centered with a style

    #+attr_odt: :style "two_columns"
    #+begin_section
    #+caption: this is the caption
    #+attr_odt: :width 8.1 :style "center_image" :anchor "as-char" 
    [[./org-mode-unicorn.png]]  

    #+caption: this is the caption
    #+attr_odt: :width 8.1 :style "center_image" :anchor "as-char" 
    [[./org-mode-unicorn.png]]  
    #+end_section

Images under the second heading still have tow problems:
1. there is a visible bounding box around the image frame, which is not wanted.
2. the caption is not centered.
Is there a way to get around the two problems and achieve the formating in the
attached file?
http://www.fileconvoy.com/dfl.php?id=g8acc15b4108c410c10000434962b43d9ffbf0000be

**Comment by kjambunathan** [comment]
There are two steps.

1. Use `:p-style`, not `:style` 

```
#+attr_odt: :style "OrgTwoColumnSection"
#+begin_section
#+caption: this is the caption
#+attr_odt: :width 8.1 :p-style "OrgCenter" :anchor "as-char" 
[[./org-mode-unicorn.png]]  

#+caption: this is the caption
#+attr_odt: :width 8.1 :p-style "OrgCenter" :anchor "as-char" 
[[./org-mode-unicorn.png]]  
#+end_section
```

2. Modify the `Illustration` style (in `styles.xml`) to use _center_ alignment.

**Comment by QiangF** [comment]
Perfect! Thank you so much!
