### ISSUE TITLE
Feature request: a table style that shows all table cell boudaries

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#4]
Too many boundary lines added by horizontal rule lines look terrible during
editing. Adding a custom table styple that shows all cell boundaries would be a
better approach. The style:

    #+ATTR_ODT: :style TableWithHeaderRowAndColumn

shows all table cell boundaries, but the header row and column have dark
backgrounds.

**Comment by kjambunathan** [comment]
> Feature request: a table style that shows all table cell boudaries 

Try this

    #+ATTR_ODT: :style "GriddedTable"
    | a | b | c |
    | d | e | f |
