### ISSUE TITLE
Feature request: add "#+odt-display-outline-level"

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#40]
Use case: table and figure numbering without the chapter prefix.
Would be nice to add this choice to figure and table caption attributes.
Thank you for your consideration.

**Comment by kjambunathan** [comment]
To strip chapter numbers from table and figure captions, use either

    #+ODT_DISPLAY_OUTLINE_LEVEL: 

or 

    #+ODT_DISPLAY_OUTLINE_LEVEL:  0
