### ISSUE TITLE
Deeper headings are converted into notes instead of freemind nodes

### ISSUE THREAD

**Issue by gcamaril** [kjambunathan/org-mode-ox-odt#41]
When I convert the following org file using:

   M-x org-freemind-export-to-freemind

Items 1 to 3 become nodes; however, items 4 to 7 don't. Instead, items 4 to 7 become notes within the node corresponding to Item 3.

What should happen is that all headings in the org file, no matter their depth, should become nodes. That is, all items, from 1 to 7, should become freemind nodes after the conversion.

 * Item 1
 ** Item 2
 *** Item 3
 **** Item 4
 ***** Item 5
 ****** Item 6
 ******* Item 7

**Comment by kjambunathan** [comment]
> Items 1 to 3 become nodes; however, items 4 to 7 don't. Instead, items 4 to 7 become notes within the node corresponding to Item 3.

Set the H option to value higher than the default 3.  

In the snippet below, I have used `H:8`.

    #+OPTIONS: ':nil *:t -:t ::t <:t H:8 \n:nil ^:t arch:headline
    #+OPTIONS: author:t broken-links:nil c:nil creator:nil
    #+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
    #+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
    #+OPTIONS: timestamp:t title:t toc:t todo:t |:t
    #+TITLE: test
    #+DATE: <2018-02-03 Sat>
    #+AUTHOR: Jambunathan K
    #+EMAIL: kjambunathan@gmail.com
    #+LANGUAGE: en
    #+SELECT_TAGS: export
    #+EXCLUDE_TAGS: noexport
    #+CREATOR: Emacs 25.2.2 (Org mode 9.0.9)


    * Item 1
    ** Item 2
    *** Item 3
    **** Item 4
    ***** Item 5
    ****** Item 6
    ******* Item 7

**Comment by kjambunathan** [comment]
Please close the bug, if my earlier reply addresses your concerns.

**Comment by gcamaril** [comment]
Thanks for your quick response! Setting H to a higher value per your suggestion works perfectly well.
