### ISSUE TITLE
Feature request: add the macro to delete empty page

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#46]
I use odt file for presentation by changing the page size. When I want the
content to start on another page, I insert a pagebreak. Sometimes I get a extra
empty page where the place the pagebreak is inserted, because the page is
breaking at that place already. But I won't know the page where the page is
breaking until the document is exported. So I have to remove the manually added
pagebreak.

So I did a search online for a macro that will automatically remove empty pages.
And I found this:
http://www.imaccanici.org/en.libreofficeforum.org/node/13491.html
The modified version is:

    sub deleteparas
    oDocSrc   = ThisComponent
        oVCursSrc   = oDocSrc.CurrentController.getViewCursor()
        'loop through all of the paragraphs in the source document
        oParEnum = oDocSrc.getText().createEnumeration()
        Do While oParEnum.hasMoreElements()
            oPar = oParEnum.nextElement()
            'fix for using tables:

            Do while oPar.supportsService("com.sun.star.text.TextTable")
                oPar = oParEnum.nextElement()
                noneEmptyPageNumber = oVCursSrc.page
            loop

            oVCursSrc.gotoRange(oPar,false)
            oVCursSrc.gotoendofline(false)
            If  len(oPar.getString()) <> 0 Then
                noneEmptyPageNumber = oVCursSrc.page
            End If
            If  len(oPar.getString()) = 0 Then
                curpagenumber = oVCursSrc.page
                If  (curpagenumber <> noneEmptyPageNumber) Then
                    oPar.dispose
                End If
            End If
        Loop
    end sub

The caveat is If there is an image anchored to an empty paragraph it will also be deleted with the paragraph.
So for the test file, the images are also removed. Is there a way to work around this.

**Comment by kjambunathan** [comment]
Ok.  I will look in to this issue.  Before that I need 3 things:

1. The `test.org` file
2. The `test.odt` created by the ODT exporter
3. The `test.odt` file after it has been processed by the macro converter.

(1) and (2) above are essential for me to understand this issue better.   (3) is optional.

**Comment by QiangF** [comment]
There are some functions on shape anchors here:
https://forum.openoffice.org/en/forum/viewtopic.php?f=25&t=82792

**Comment by QiangF** [comment]
I asked the question on openoffice forum and found the solution:

    sub delete_empty_paragraph
        doc = thiscomponent
        paragraphs = doc.Text
        for each para in paragraphs
            if para.String = "" then
                for each portion in para
                    if portion.TextPortionType <> "Text" then
                        goto continue
                    end if
                next portion
                para.dispose()
            end if
            continue:
        next para
    end sub

**Comment by QiangF** [comment]
The final macros are:

    sub DeleteEmptyParagraph(Optional inFileURL)
        Dim inDoc
        Dim interactive

    If IsMissing(inFileURL) Then
        interactive = True
        ' Most likely, the Macro is run interactively. Act on
        ' the current document
        If ThisComponent.HasLocation() Then
            inDoc = ThisComponent
            inFileURL = inDoc.GetLocation()
        End If
    Else
        interactive = False
        Dim oProps(0) as New com.sun.star.beans.PropertyValue
        oProps(0).Name = "Hidden"
        oProps(0).Value = True
        inDoc = StarDesktop.loadComponentFromURL(inFileURL, "_blank", 0, oProps())
    End If

        paragraphs = inDoc.Text
        for each para in paragraphs
            if para.String = "" then
                for each portion in para
                    if portion.TextPortionType <> "Text" then
                        goto continue
                    end if
                next portion
                para.dispose()
            end if
            continue:
        next para
        If (inDoc.isModified() AND inDoc.hasLocation() AND (Not inDoc.isReadOnly())) Then
        inDoc.store()
        End If

        If Not interactive Then
        inDoc.Close(True)
        End If
    end sub

    Sub SilentlyReload
        ThisComponent.setModified(False)  'Ignore changes'
        document = ThisComponent.CurrentController.Frame
        dispatcher = createUnoService("com.sun.star.frame.DispatchHelper")
        dispatcher.executeDispatch(document, ".uno:Reload", "", 0, Array())
    End Sub

If those macros looks interesting, could you please includes those in the utilities.oxt file.
Also I open the document after export and do a reload automatically with:

    (defun my-org-export-to-odt-and-open ()
        (interactive)
        (call-process "soffice" nil 0 nil (org-odt-export-to-odt) "macro:///OrgMode.Utilities.SilentlyReload"))

**Comment by QiangF** [comment]
Deleting empty paragraphs only works when there is an office program open.

    (defun my-org-odt-export-to-odt ()
        (interactive)
        ;; only export the current heading
        ;; (call-process "xdg-open" nil 0 nil (org-odt-export-to-odt nil t)))
        (let ((file-name (org-odt-export-to-odt nil t)))
             (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.SilentlyReload")
             (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.DeleteEmptyParagraph")))

    (defun my-org-export-to-odt-and-open ()
        (interactive)
        (let ((file-name (org-odt-export-to-odt)))
             (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.SilentlyReload")
             (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.DeleteEmptyParagraph")))

**Comment by QiangF** [comment]
OK. I am lost, the macro doesn't work consistently, I am not sure whether
"#+pagebreak" is related to empty paragraphs or not. I have created a very
simple example to illustrate the problem I am facing:

    * 1

    #+caption: hello world
    #+attr_odt: :width 24 :style "center_image" :anchor "as-char"
    [[an image with a very big height]]

    #+pagebreak:

    * 2
    I want heading 2 to be on a seperate page, so I inserted a pagebreak. But as
    you see, the previous image (very high image (very high image (very high
    image) is too long to fit on a sinlge page. So the pagebreak following the
    image is not needed.

    This is just one case of not respecting the user's intention, because
    org-mode-odt is not a what you see is what you get type of editing, where the
    page breaks is not known, and all we can do is instert "#+pagebreak" at the
    place we want, and let the macro remove the empty pages.

**Comment by QiangF** [comment]
This is a macro that not working.
        
    sub DeleteEmptyPages
        emptyPages = ""
        noneEmptyPageNumber = 0
        foundEmptyObj = False

        sTextContent = "com.sun.star.text.TextContent"
        oText = ThisComponent.Text
        oViewCursor = ThisComponent.CurrentController.getViewCursor()

        REM find empty pages
        oParEnum1 = ThisComponent.getText().createEnumeration()
        Do While oParEnum1.hasMoreElements()
            oPar = oParEnum1.nextElement()
            oViewCursor.gotoRange(oPar,false)
            oViewCursor.gotoendofline(false)
            curPageNumber = oViewCursor.page

            REM an empty page is an empty object on a single page
            If (curpagenumber <> emptyObjPageNumber) And foundEmptyObj Then
                emptyPages = emptyPages & "," & CStr(emptyObjPageNumber)
            End If

            If  len(oPar.getString()) <> 0 Or oPar.supportsService("com.sun.star.text.TextTable") Then
                noneEmptyPageNumber = oViewCursor.page
                foundEmptyObj = False
            Else
                REM If there is an image anchored to an empty paragraph, getSring will return 0
                REM so need to test if the paragraph contains other objects.
                If (curPageNumber <> noneEmptyPageNumber) Then
                    REM Obtain the view cursor, and then select the paragraph containing the view cursor.
                    oTextCursor = oText.createTextCursorByRange(oViewCursor)
                    REM Move to the start of the paragraph as a single point.
                    oTextCursor.gotoStartOfParagraph(False)
                    REM Move to the end of the current paragraph and expand the selection so that the entire paragraph is selected.
                    oTextCursor.gotoEndOfParagraph(True)
                    REM Enumerate the text content contained by this text cursor, including inserted drawing objects, such as the shape used by a button
                    oEnum = oTextCursor.createContentEnumeration(sTextContent)
                    If Not oEnum.hasMoreElements() Then
                        REM an empty paragraph on a new page has been found
                        REM if the next object is on another page, go back and delete the empty paragraph
                        emptyObjPageNumber = oViewCursor.page
                        foundEmptyObj = True
                    End If
                End If
            End If
        Loop

        REM delete empty pages
        emptyPagesArray = Split(emptyPages,",")
        oParEnum2 = ThisComponent.getText().createEnumeration()
        i = 0
        Do While oParEnum2.hasMoreElements() And (emptyPagesArray.Length - i > 0) ' I got "basic runtime error. Object variable not set on this line"
            oPar = oParEnum2.nextElement()
            oViewCursor.gotoRange(oPar,false)
            oViewCursor.gotoendofline(false)
            curPageNumber = oViewCursor.page
            emptyObjPageNumber = CULng(emptyPagesArray(i))
            If (curPageNumber = emptyObjPageNumber) Then
                oPar.dispose
                i = i+1
            End If
        Loop
    end sub

**Comment by QiangF** [comment]
Adding a sleep and it is working now!

    (defun my-org-export-to-odt-and-open ()
        (interactive)
        (let ((file-name (org-odt-export-to-odt)))
          (progn
             (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.SilentlyReload")
             (sleep-for 1.5)
             (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.DeleteEmptyParagraph"))))

**Comment by QiangF** [comment]
The final version:

    sub DeleteEmptyParagraph(Optional inFileURL)
        myNoneEmptyPageNumber = 0
        myFoundEmptyObj = False
        myParToBeDeleted = ""

        If IsMissing(inFileURL) Then
        interactive = True
        ' Most likely, the Macro is run interactively. Act on
        ' the current document
        If ThisComponent.HasLocation() Then
            inDoc = ThisComponent
            inFileURL = inDoc.GetLocation()
        End If
        Else
        interactive = False
        Dim oProps(0) as New com.sun.star.beans.PropertyValue
        oProps(0).Name = "Hidden"
        oProps(0).Value = True
        inDoc = StarDesktop.loadComponentFromURL(inFileURL, "_blank", 0, oProps())
        End If

        REM find empty pages
        paragraphs = inDoc.Text
        oViewCursor = inDoc.CurrentController.getViewCursor()
        restart:
        for each oPar in paragraphs
            oViewCursor.gotoRange(oPar,false)
            oViewCursor.gotoendofline(false)
            myCurrentPageNumber = oViewCursor.page
            If myFoundEmptyObj And (myCurrentPageNumber <> emptyObjPageNumber) Then
                REM an empty page is an empty object on a single page
                REM save empty page number in a string
                If myParToBeDeleted <> "" then
                    parToBeDeleted.dispose
                    myParToBeDeleted = ""
                    goto restart
                End If
                myParToBeDeleted = ""
            End If

            myStr = oPar.String
            If myStr <> "" then
                myNoneEmptyPageNumber = oViewCursor.page
                myFoundEmptyObj = False
                goto continue
            Else
                for each portion in oPar
                    myTextProp = portion.TextPortionType
                    if (myTextProp <> "Text" And portion.TextPortionType <> "SoftPageBreak") then
                        myNoneEmptyPageNumber = oViewCursor.page
                        myFoundEmptyObj = False
                        myParToBeDeleted = ""
                        goto continue
                    else
                        if myCurrentPageNumber <> myNoneEmptyPageNumber then
                            REM an empty paragraph on a new page has been found
                            REM if the next object is on another page, go back and delete the empty paragraph
                            emptyObjPageNumber = oViewCursor.page
                            myFoundEmptyObj = True
                            myParToBeDeleted = "1"
                            parToBeDeleted = oPar
                        end if
                    end if
                next portion
            end if
            continue:
        next oPar

        If (inDoc.isModified() AND inDoc.hasLocation() AND (Not inDoc.isReadOnly())) Then
        inDoc.store()
        End If

        If Not interactive Then
        inDoc.Close(True)
        End If
    end sub

**Comment by kjambunathan** [comment]
> SilentlyReload

Ok.  I have added a LibreOffice macro called `Reload`.  It is slightly different from the version you shared with me.  Please test drive it, and let me know if it falls short of your expectation.

**Comment by QiangF** [comment]
Please also include this one too, if a soft pagebreak follows by a pagebreak, it
removes the pagebreak, seems it needs to be run interactively.

    sub DeleteEmptyPage(Optional inFileURL)
        If IsMissing(inFileURL) Then
        interactive = True
        ' Most likely, the Macro is run interactively. Act on
        ' the current document
        If ThisComponent.HasLocation() Then
            inDoc = ThisComponent
            inFileURL = inDoc.GetLocation()
        End If
        Else
        interactive = False
        Dim oProps(0) as New com.sun.star.beans.PropertyValue
        oProps(0).Name = "Hidden"
        oProps(0).Value = True
        inDoc = StarDesktop.loadComponentFromURL(inFileURL, "_blank", 0, oProps())
        End If

        paragraphs = inDoc.Text
        for each para in paragraphs
            deletepara = False
            if para.String = "" and para.BreakType = 5 then
                for each portion in para
                    if portion.TextPortionType = "SoftPageBreak" then
                        deletepara = True
                    elseif portion.TextPortionType <> "Text" then
                        exit for
                    end if
                next portion
                if deletepara then
                    para.dispose()
                end if
            end if
        next para

        If (inDoc.isModified() AND inDoc.hasLocation() AND (Not inDoc.isReadOnly())) Then
        inDoc.store()
        End If

        If Not interactive Then
        inDoc.Close(True)
        End If
    end sub

**Comment by kjambunathan** [comment]
> Please also include this one too, if a soft pagebreak follows by a pagebreak, it
removes the pagebreak, I can't find a way for it to run non-interactively.

I am currently reviewing your requests, specifically the back-forths  in this thread [[Solved] How to remove all empty pages with a macro](https://forum.openoffice.org/en/forum/viewtopic.php?f=20&t=94529).  (I feel) I might have a few questions or suggestions for you in day or two.

**Comment by QiangF** [comment]
Your version of reload will be blocked by a dialogue box if the document is
accidentally changed. And we don't need to run it non-interactively, so I think
the ignore changes is necessary and other things are not needed. However the
DeleteEmptyPages will benefit from an non-interactive version.

    Sub SilentlyReload
    inDoc = ThisComponent
    If Not IsNull(inDoc) Then
        inDoc.setModified(False)  'Ignore changes'
        dispatcher = createUnoService("com.sun.star.frame.DispatchHelper")
        dispatcher.executeDispatch(inDoc.CurrentController.Frame, ".uno:Reload", "", 0, Array())
    End If
    End Sub

    sub DeleteEmptyPages
        inDoc = ThisComponent
        paragraphs = inDoc.Text
        for each para in paragraphs
            deletepara = False
            if para.String = "" and para.BreakType = 5 then
                for each portion in para
                    if portion.TextPortionType = "SoftPageBreak" then
                        deletepara = True
                    elseif portion.TextPortionType <> "Text" then
                        exit for
                    end if
                next portion
                if deletepara then
                    para.dispose()
                end if
            end if
        next para

        If (inDoc.isModified() AND inDoc.hasLocation() AND (Not inDoc.isReadOnly())) Then
            inDoc.store()
        End If
    end sub

**Comment by QiangF** [comment]
This fix the para.String method doesn't exist error.

    sub DeleteEmptyPages
        inDoc = ThisComponent
        paragraphs = inDoc.Text
        for each para in paragraphs
            deletepara = False
            If para.supportsService("com.sun.star.text.TextTable") Then
                goto continue
            elseif para.String = "" and para.BreakType = 5 then

                for each portion in para
                    if portion.TextPortionType = "SoftPageBreak" then
                        deletepara = True
                    elseif portion.TextPortionType <> "Text" then
                        exit for
                    end if
                next portion
                if deletepara then
                    para.dispose()
                end if
            end if
        continue:
        next para

        If (inDoc.isModified() AND inDoc.hasLocation() AND (Not inDoc.isReadOnly())) Then
            inDoc.store()
        End If
    end sub

**Comment by kjambunathan** [comment]
_(LibreOffice Macros aren't our area of expertise and I strongly feel that we should avoid venturing in to writing and -re-writing any macros that would require an expert understanding of LibreOffice APIs.)_ 

I would like to explore if there is a way to achieve what you want with _just_ the ODT exporter.  

 

Please don't use `#+PAGEBREAK:`. Instead, use  `:page-break` attributes.  

In the following `Org` snippet, the second image requests a page-break after itself and the chapter immediately following it requests a page-break before it i.e., Going by user request alone, there are two back-to-back pagebreaks.  But if you view at the exported document in LibreOffice, you will see that no empty pages at all.

    #+options:  toc:nil author:nil tex:t latex:t :H 10
    #+language: zh-CN
    #+odt_display_outline_level:  0
    #+odt_styles_file: "./presentation_cn.xml"
    #+odt_content_template_file: "./default_template.xml"

    #+attr_odt: :page-break "before"
    #+attr_odt: :style "align_right"
    #+attr_odt: :width 4.1 :anchor "as-char"
    [[./org-mode-unicorn.png]]
    #+attr_odt: :page-break "after"
    #+caption: 1
    #+label: fig: 2
    #+attr_odt: :width 7.1 :style "center_image" :anchor "as-char"
    [[./org-mode-unicorn.png]]

    # Some text

    * Heading 1
      :PROPERTIES:
      :ATTR_ODT: :page-break t
      :END:

    Some text

There are many examples of how to use page-breaks [here](https://raw.githubusercontent.com/kjambunathan/org-mode-ox-odt/master/testing/examples/odt/pagebreak.org).
