### ISSUE TITLE
Question: how to insert line breaks in figure caption

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#5]
Multi-line caption can be useful when there needs more description of the
caption in a seperate line.

**Comment by kjambunathan** [comment]
> Multi-line caption can be useful when there needs more description of the caption in a seperate line.

Your questions tell me that you are new to Org mode.  With more experience, you may not raise such questions.  Nevertheless, see what happens with this snippet

    #+CAPTION: First line of caption \\
    #+CAPTION: Second line of caption
    [[./org-mode-unicorn.png]]
