### ISSUE TITLE
Maybe add a pause between macros in org-odt-transform-processes

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#51]
I have reload after update all,  but sometimes the document is not reloaded. I guess it may need a pause in between.

**Comment by kjambunathan** [comment]
> I have reload after update all, but sometimes the document is not reloaded. I guess it may need a pause in between.

Can you do a `C-h v org-odt-transform-processes` at your side and copy-paste the value here.

**Comment by QiangF** [comment]
My org-odt-transform-processes is

    (("reload" "soffice" "--norestore" "macro:///OrgMode.Utilities.SilentlyReload(%I)")
    ("update field" "soffice" "--norestore" "--invisible" "--headless" "macro:///OrgMode.Utilities.UpdateAll(%I)"))

Libreoffice sometimes fails to refresh the file, and I new to export twice to get the file reloaded.

**Comment by kjambunathan** [comment]
My LibreOffice 6.1 crashes when I start recording a macro.

Here is a suggestion, and this *I feel* fix things for you.  

Edit `UpdateAll` as follows.

Towards the end of UpdateAll, I do a `close` using API call.  Remove that replace that line with two `executeDispatch` calls: first for `.uno:save` and then for `.uno:close`.  (*Hint*: You can generate these two `executeDispatch` calls by doing a `Record Macro` for the above operations)

----

Regarding the macro calls, I see that you are using your own `ReloadAll`.  I suggest that you replace it will my version of `Reload`.   This change will ensure that we are working with same settings.

-----

Swap the order of the entries in `org-odt-transform-processes`.  i.e., Do `UpdateAll` first, followed by a `Reload`.


-------

Of the above three suggestions, *I feel* the `executeDispatch` changes is the most important one.  And it will give the expected result.  Let me know if this suggestion would or not.  If it works, I will update the `oxt` file.

**Comment by kjambunathan** [comment]
> My LibreOffice 6.1 crashes when I start recording a macro.

See https://bugs.documentfoundation.org/show_bug.cgi?id=122041

**Comment by QiangF** [comment]
Yes, reload should be run after UpdateAll. I'll try this for a week and report back if it works. 
Thank you!

**Comment by QiangF** [comment]
It seems that the problem happens because the later macro in org-odt-transform-process is run when
the previous has not finished, and using executeDispatch put it in order, now everything is
working. I modified UpdateAll as follows:

   If (inDoc.isModified() AND inDoc.hasLocation() AND (Not inDoc.isReadOnly())) Then
       dispatcher.executeDispatch(inDoc.CurrentController.Frame, ".uno:Save", "", 0, Array())
   End If

   If Not interactive Then
      dispatcher.executeDispatch(inDoc.CurrentController.Frame, ".uno:CloseDoc", "", 0, Array())
   End If  

    (setq org-odt-transform-processes '(("update field" "soffice" "--norestore" "--invisible" "--headless" "macro:///OrgMode.Utilities.UpdateAll(%I)"))

When I want the file to be reloaded, I run

    (defun my-org-odt-export-buffer ()
        (interactive)
        (let ((file-name (org-odt-export-to-odt)))
          (progn
            (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.Reload"))))

**Comment by QiangF** [comment]
The following is useful when I only want to see part of the document.

    (defun my-org-odt-export-subtree ()
        (interactive)
        (let ((file-name (org-odt-export-to-odt nil t nil
                                                '(:title nil :date nil :author nil
                                                  :preserve-breaks nil :with-latex t
                                                  :with-toc nil :with-title nil ))))
            (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.Reload")))

**Comment by kjambunathan** [comment]
> It seems that the problem happens because the later macro in org-odt-transform-process is run when
the previous has not finished, and using executeDispatch put it in order, now everything is
working. 

_executeDispatch_ is asynchronous, and I wonder when my suggested workaround will break.  

Your question has been bothering me and I wanted to find a right fix.  I posted a query in OpenOffice.org forum a few hours ago.  (See [Synchronous API equivalent for executeDispatch(.uno:UpdateAl](https://forum.openoffice.org/en/forum/viewtopic.php?f=45&t=96384). From the very first reply, it looks like I may not get the right solution in that forum.
