### ISSUE TITLE
Inline formula not working in caption

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#52]
I use mathtoweb for math formula.

    (setq org-latex-to-mathml-convert-command
                "java -jar %j -unicode -force -df %o %I"
                org-latex-to-mathml-jar-file
                "~/.dotfiles/usr/scripts/mathtoweb.jar")

A simple test for table caption
    
    #+caption: $ln \dot{\epsilon}$
    |1|2|

**Comment by QiangF** [comment]
I am not sure if this patch fix this:

    org-mode-ox-odt/todo2/0021-ox-odt-Fix-handling-math-snippets-in-captions.patch

**Comment by kjambunathan** [comment]
> org-mode-ox-odt/todo2/ ...

This weekend  I will focus on clearing all the pending todos (atleast the easier ones).  Once that is done, I will work on documenting all the cool features that is *exclusive* to this branch.
