### ISSUE TITLE
#+AUTHOR, #+SUBTITLE not supported

### ISSUE THREAD

**Issue by jacknashg** [kjambunathan/org-mode-ox-odt#58]
Export settings like #+AUTHOR and #+SUBTITLE don't work with ox-odt.
Can someone address this issue please.

**Comment by kjambunathan** [comment]
> #+AUTHOR, #+SUBTITLE not supported 

The fix is available in `ox-odt-9.2.3.245.tar`.  See [README](https://github.com/kjambunathan/org-mode-ox-odt#installation) for instructions on how to install this version at your end.

**Comment by kjambunathan** [comment]
With the above changes, when I export the snippet below 

```
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: This is Title
#+date: <2019-05-13 Mon>
#+author: Jambunathan K
#+email: kjambunathan@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 26.1 (Org mode 9.2.3)

#+options: tex:t
#+description:
#+keywords:
#+subtitle: This is Subtitle
#+odt_styles_file:
#+odt_extra_images:
#+odt_extra_styles:
#+odt_extra_automatic_styles:
#+odt_master_styles:
#+odt_content_template_file:
#+odt_automatic_styles:
#+odt_display_outline_level: 2
#+bib_file:

Some text.

```

I see

![Screenshot from 2019-05-13 20-02-51](https://user-images.githubusercontent.com/19869864/57629889-37ad9380-75ba-11e9-84db-0f45573260f0.png)

**Comment by jacknashg** [comment]
thank you, kjambunathan, for your quick response and fix.
i believe this issue has been resolved.
it seems, however, the new version (version 9.2.3.245) cannot be installed through as is suggested in [README](https://github.com/kjambunathan/org-mode-ox-odt#installation) .

here is what i discovered:

1. i delete the old version (version 9.2.3.242)

2. i double checked and ensured my package-archives config includes the refered url:
![深度截图_选择区域_20190514093150](https://user-images.githubusercontent.com/14989990/57664731-f786f900-762b-11e9-8875-a9431c60387e.png)

3. after package-refresh-contents, i still get this:
![深度截图_选择区域_20190514093008](https://user-images.githubusercontent.com/14989990/57664807-22714d00-762c-11e9-9f47-c926dd4c749e.png)

4. i tried to install it anyway, and this is what i get:
![深度截图_选择区域_20190514093244](https://user-images.githubusercontent.com/14989990/57664827-32892c80-762c-11e9-9ee6-6bea175c84e6.png)
![深度截图_选择区域_20190514093259](https://user-images.githubusercontent.com/14989990/57664831-3452f000-762c-11e9-9fe9-3216bf3d6ad9.png)


so, kjambunathan, am i missing something? pls help me out.

**Comment by kjambunathan** [comment]
> it seems, however, the new version (version 9.2.3.245) cannot be installed through as is suggested in README .

The new version is online now.  

(I pushed the `tar` file but failed to push the `archive-contents` file.  Now I have fixed it.)

**Comment by jacknashg** [comment]
it works. awesome!
thank you!
