### ISSUE TITLE
Feature request: fine grained control of both image and caption widths

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#61]
An example use case: the figure below has a long caption and a small figure, currently the caption is forced to have the same width as the figure, and it doesn't look good.

    #+caption: This is a very long long long long long long long long caption.
    #+label: org
    #+attr_odt: :width 3 :anchor "as-char" :style "OrgCenter"
    [[./org-mode-unicorn.png]]

Maybe the outer frame size should be specified with an extra attribute for the caption, like:

    #+attr_odt: :width 10
    #+caption: This is a very long long long long long long long long caption.
    #+label: org
    #+attr_odt: :width 3 :anchor "as-char" :style "OrgCenter"
    [[./org-mode-unicorn.png]]

A better default if no specification for the outer frame may be just occupy the whole width of the column.

**Comment by kjambunathan** [comment]
> Feature request: fine grained control of both image and caption widths

There are just too many moving parts in typesetting an captioned image.  There are two frames, a text box (and the paragraph style within text box), and also a paragraph that surrounds all these.  The `#+ATTR_ODT` as it stands today cannot capture all the xml attributes that goes in to configuing all these parts.   

Let me rework the existing implementation so that it will not only do what you request but much more, in a more easy-to-understand way.

**Comment by kjambunathan** [comment]
> Feature request: fine grained control of both image and caption widths 

Here is a screenshot of the new change in action.

![Screenshot from 2019-10-18 15-17-24](https://user-images.githubusercontent.com/19869864/67085234-15005600-f1bc-11e9-9b52-8a26f787c2ed.png)


Here is the sample snippet for you to try out.

```
* Image as it is

#+caption: This is a very long long long long long long long long caption.
[[./org-mode-unicorn.png]]

* Image scaled to width of 3cms
:PROPERTIES:
:ATTR_ODT: :page-break t
:END:

#+attr_odt: :width 3
#+caption: This is a very long long long long long long long long caption.
[[./org-mode-unicorn.png]]

* Image scaled to width of 3cms but with a caption width of 7cms

#+attr_odt: :width (3 7)
#+caption: This is a very long long long long long long long long caption.
[[./org-mode-unicorn.png]]

* Image as it is, but with a caption width of 7cms
:PROPERTIES:
:ATTR_ODT: :page-break t
:END:

#+attr_odt: :width (nil 7)
#+caption: This is a very long long long long long long long long caption.
[[./org-mode-unicorn.png]]

* Image size is 3x6 cms, and caption box is 9x12cms

#+attr_odt: :width (3 6) :height (9 12)
#+caption: This is a very long long long long long long long long caption.
[[./org-mode-unicorn.png]]

```

**Comment by kjambunathan** [comment]
> Feature request: fine grained control of both image and caption widths

>> There are just too many moving parts in typesetting a captioned image. There are two frames, a text box (and the paragraph within that text box), and also a paragraph that surrounds all these. The #+ATTR_ODT as it stands today cannot capture all the xml attributes that can go in to configuing all these diverse parts.

> Let me rework the existing implementation so that it will not only do what you request but much more, in a more easy-to-understand way.

The `:anchor` property is very confusing.  I am planning to remove the `:anchor` property and replace it with a `:template` property.  Meanwhile, you can test out the new feature and see if it requires more adjustments.

**Comment by QiangF** [comment]
Works like a charm! However, the ":style" property is not used. For example the image can't be centered with:

    * Image scaled to width of 3cms but with a caption width of 7cms
    #+attr_odt: :width (3 7) :style "OrgTitle"
    #+caption: This is a very long long long long long long long long caption.
    [[./org-mode-unicorn.png]]

If the image is centered by default, the style specification can be omitted, as captioned image are often centered.

**Comment by kjambunathan** [comment]
> However, the ":style" property is not used. For example the image can't be centered with:

I have pushed the necessary changes.

This is what I get

![Screenshot from 2019-10-18 22-39-42](https://user-images.githubusercontent.com/19869864/67113987-7514ed80-f1f8-11e9-8020-351d7c115f64.png)

when I export this

#+attr_odt: :width (3 7)
#+caption: This is a very long long long long long long long long caption.
[[./org-mode-unicorn.png]]
```

```

**Comment by kjambunathan** [comment]
> However, the ":style" property is not used. For example the image can't be centered with:

Btw, you wouldn't have a need for `:style` property anymore.  Let me know if it is otherwise.
