### ISSUE TITLE
Feature request: infer caption type from the label of an object

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#7]
The use cases are:
1. you insert a graphic table, and want it to have a caption of table
2. you have multiple images in a frame, and want the frame to have a caption of
   figure
So if the caption type can be infered from the label prefix, such as:

    #+caption: hello
    #+labe: fig:1

will be a figure caption not matter where it is placed, that will give the user
more flexibility.

**Comment by kjambunathan** [comment]
Could you please review this bug and see if it is still relevant?  If not, could you please close it.

**Comment by QiangF** [comment]
The subfigure is a perfect solution!
https://github.com/kjambunathan/org-mode-ox-odt/issues/53
