### ISSUE TITLE
Bug: ODT exporter does not honour +LANGUAGE line [9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.1/lisp/org/)]

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#80]
See https://lists.gnu.org/archive/html/emacs-orgmode/2020-08/msg00140.html

Dear maintainer,

the ODT exporter always exports as English, even if a document is not
written in English and contains a corresponding +LANGUAGE line. Take for
example this German document:

    #+AUTHOR: Ich
    #+TITLE: Test
    #+LANGUAGE: de
    
    Dies ist ein Test.

When it is exported as ODT, the main language is set to English. As a
result, the office application's spell checker (LibreOffice's one in my
case) highlights everything as wrong that isn't accidentally a valid
word in English. To fix that one has to manually change the document's
main language to German (in this case) via the office application's
menus. This is annoying, especially if the intention is to automatically
further convert to DOCX and send the document out unmodified. The HTML
exporter on the other hand handles the +LANGUAGE line just fine.

  -quintus

Emacs  : GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)
 of 2019-09-23, modified by Debian
Package: Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ 
/usr/share/emacs/26.1/lisp/org/)

**Comment by ouboub** [comment]
very good, thanks!
I could test Hebrew as well, if you are willing to implement that as well.

**Comment by kjambunathan** [comment]
> I can confirm german, spanish, hebrew, english_US but I fail with british, shouldn't that be english_GB?

If you choose `English (United Kingdom)` in completion table you get "en-GB".  LibreOffice's mode-line also prefers  `English (UK)` to using `English (GB)`.

> BTW the sentence you picked up locks strange, but so be it.

From https://kermitproject.org/utf8.html#notes

The \"I can eat glass\" phrase and initial translations (about 30 of
them) were borrowed from Ethan Mollick\'s [I Can Eat
Glass](http://hcs.harvard.edu/~igp/glass.html) page (which disappeared
on or about June 2004) and converted to UTF-8. Since Ethan\'s original
page is gone, I should mention that his purpose was to offer travelers a
phrase they could use in any country that would command a certain kind
of respect, or at least get attention. See
[Credits](https://kermitproject.org/utf8.html#credits) for the many
additional contributions since then. When submitting new entries, the
word \"hurt\" (if you have a choice) is used in the sense of \"cause
harm\", \"do damage\", or \"bother\", rather than \"inflict pain\" or
\"make sad\". In this vein Otto Stolz comments (as do others further
down; personally I think it\'s better for the purpose of this page to
have extra entries and/or to show a greater repertoire of characters
than it is to enforce a strict interpretation of the word \"hurt\"!):

> This is the meaning I have translated to the Swabian dialect. However,
> I just have noticed that most of the German variants translate the
> \"inflict pain\" meaning. The German example should read:
>
> > \"Ich kann Glas essen ohne mir zu schaden.\"
>
> rather than:
>
> > \"Ich kann Glas essen, ohne mir weh zu tun.\"
>
> (The comma fell victim to the 1996 orthographic reform, cf.
> <http://www.ids-mannheim.de/reform/e3-1.html#P76>.

**Comment by kjambunathan** [comment]
Btw, I discovered the following side-effect ... so re-opening this bug

> https://github.com/kjambunathan/org-mode-ox-odt/commit/286a9b789db842cfa3a2fa68e4383bf6101da10c

This commit for changing language/locale "breaks" the "in buffer" configuration of font size.  FWIW,  I have shared a recipe for quick configuration of font sizes here https://github.com/kjambunathan/org-mode-ox-odt/discussions/102#discussioncomment-1440557.  (Hint:  See the initial few lines of `diff` in that comment)

Here is a sample snippet:

```org
#+odt_extra_styles: <style:style style:name="Standard" style:family="paragraph"
#+odt_extra_styles: 	     style:class="text">
#+odt_extra_styles:   <style:text-properties fo:font-size="10pt"/>
#+odt_extra_styles: </style:style>

#+language: en_GB

Phrases in this document are translations of "I can eat glass and it
doesn't hurt me" in to various languages.  They are taken from [[https://kermitproject.org/utf8.html][UTF-8
Sampler]].



```

**Comment by kjambunathan** [comment]
> Ethan Mollick's [I Can Eat Glass](http://hcs.harvard.edu/~igp/glass.html) page (which disappeared
> on or about June 2004)

This page is in Wayback Machine ...  https://web.archive.org/web/20010308220934/http://www.hcs.harvard.edu/~igp/glass.html.

**Comment by ouboub** [comment]
> Btw, I discovered the following side-effect ... so re-opening this bug
> 
> > [286a9b7](https://github.com/kjambunathan/org-mode-ox-odt/commit/286a9b789db842cfa3a2fa68e4383bf6101da10c)
> 
> This commit for changing language/locale "breaks" the "in buffer" configuration of font size. FWIW, I have shared a recipe for quick configuration of font sizes here [#102 (reply in thread)](https://github.com/kjambunathan/org-mode-ox-odt/discussions/102#discussioncomment-1440557). (Hint: See the initial few lines of `diff` in that comment)
> 
> Here is a sample snippet:
> 
> ```
> #+odt_extra_styles: <style:style style:name="Standard" style:family="paragraph"
> #+odt_extra_styles: 	     style:class="text">
> #+odt_extra_styles:   <style:text-properties fo:font-size="10pt"/>
> #+odt_extra_styles: </style:style>
> 
> #+language: en_GB
> 
> Phrases in this document are translations of "I can eat glass and it
> doesn't hurt me" in to various languages.  They are taken from [[https://kermitproject.org/utf8.html][UTF-8
> Sampler]].
> ```

oops, I did not pay attention, but you are right, and for me right now the 10pt configuration is more important, so 
I run
git checkout -b 10pt 774c32566^
then 
make clean
and 
make 
and I am back to the correct 10pt configuration,
If you find a fix, I would appreciate it

**Comment by kjambunathan** [comment]
I have added `org-odt-experimental-features`.  By default, LANGUAGE feature is ON.  I have kept the option ON so that I can get feedback on the feature.

I have introduced a new style `OrgUser` which the user can setup.   So, if you have any `Standard` style in `#+odt_extra_styles: `, rename it to `OrgUser`.  (Even if you don't do this renaming, old `org` files will continue to work as before)

For example, the snippet will export to 10pt German document by default (i.e., when  EXPERIMENTAL`language` feature is ON) and will export to 10pt English (UK) document otherwise (i.e., when EXPERIMENTAL `language` feature is OFF)

There shouldn't be any need for you to turn OFF `org-odt-experimental-features` at all.  (I will be adding `starmath` to  `org-odt-experimental-features` very soon)


```
#+odt_extra_styles: <style:style style:name="OrgUser" style:family="paragraph"
#+odt_extra_styles: 	     style:class="text">
#+odt_extra_styles:   <style:text-properties fo:font-size="10pt"/>
#+odt_extra_styles: </style:style>

#+language: de_DE

Phrases in this document are translations of "I can eat glass and it
doesn't hurt me" in to various languages.  They are taken from [[https://kermitproject.org/utf8.html][UTF-8
Sampler]].
```
