### ISSUE TITLE
Inconsistencies in ODT document headers

### ISSUE THREAD

**Issue by apiraino** [kjambunathan/org-mode-ox-odt#81]
Hi,

let's take this example from the `./testing/examples/odt/masterdocument.org`:

The document header suggests to write (reduced version):
```
#+OPTIONS: date:t e:t email:t f:t inline:t num:t

#+TITLE: Testfile for OpenDocumentText Exporter
#+AUTHOR:    Jambunathan K
#+EMAIL:     kjambunathan@gmail.com
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
```

When compiled and exported, the .odt document just show the title and the author.

By trial and error, here's a slightly better version:

```
#+OPTIONS: date:t e:t email:t f:t inline:t num:t

#+TITLE: Document title
#+date: <2020-10-13 Tue>
#+author: John Doe
#+email: doe@domain.com
#+language: en
```

But I notice a couple of things:
- The email is rendered as a link over the author text pointing to a document path instead of a `mailto:` link
- UPPERCASE labels do not work
- if I move the `date` under `author`, the `author` is not rendered anymore
- How do I print a line with just the clickable email?

Ideally my goal is to create a template that exports as follows:
- Document title
- date
- author (non clickable)
- email (clickable `mailto:` link)
- www (clickable `href:` link)

I'm sure that I am not using the template correctly, what am I doing wrong? :-)

Thanks for the help!

**Comment by kjambunathan** [comment]
> Ideally my goal is to create a template that exports as follows:
> 
>     Document title
>     date
>     author (non clickable)
>     email (clickable mailto: link)
>     www (clickable href: link)

In the following snippet, 

1. I have suppressed content that is auto-generated by the ODT exporter (based on document metadata). 
2. I have rolled out my own initial content.  You see two variations one using Org-like syntax, other using inline ODT / XML.

One side-effect of suppressing the various metadata fields is that it not only suppresses the fields getting in to content.xml (which is what you want), but also suppresses those fields getting in to meta.xml`.  To understand what I mean, in LibreOffice experiment with `View -> Field Shadings`, `View -> Field Names`, and `File -> Properties`.  


```
#+options: title:nil author:nil date:nil email:nil

#+title: Alpha & Beta
#+date: <2020-10-14 Wed>
#+author: Jambunathan K
#+email: kjambunathan@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.0.50 (Org mode 9.3.7)

#+ATTR_ODT: :style OrgTitle
{{{title}}}

#+ATTR_ODT: :style OrgDocInfo
#+begin_center
{{{date}}}

{{{author}}}

[[mailto:kjambunathan@gmail.com][{{{email}}}]]

[[https://orgmode.org]]
#+end_center

#+begin_export odt
<text:p text:style-name="OrgTitle">Emacs &amp; Vim</text:p>

<text:p text:style-name="OrgDocInfo"><text:span text:style-name="OrgActiveTimestamp">&lt;2020-10-14 Wed&gt;</text:span></text:p>

<text:p text:style-name="OrgDocInfo">Jambunathan K</text:p>

<text:p text:style-name="OrgDocInfo"><text:a xlink:type="simple" xlink:href="mailto:kjambunathan@gmail.com">kjambunathan@gmail.com</text:a></text:p>

<text:p text:style-name="OrgDocInfo"><text:a xlink:type="simple" xlink:href="https://orgmode.org">https://orgmode.org</text:a></text:p>
#+end_export

```

**Comment by kjambunathan** [comment]
I have edited my response a bit.  (I wonder if github sends email notifications for edits)  So, to see the updated response, see https://github.com/kjambunathan/org-mode-ox-odt/issues/81#issuecomment-708126536

**Comment by apiraino** [comment]
Thank you so much for the great answer! Very interesting how you build the document.

I have one more question: manually handling the document header will result in having the headers after the table of contents that is created automatically. I can comment the automatic creation of table of content with:
```
#+options: title:nil author:nil date:nil email:nil toc:nil
```
but then I wonder if I can print it after the document header. I've tried guessing the macro name for the table of contents without success (`{{{toc}}}` for example). Is there a workaround to print it?

Thanks again!

**Comment by kjambunathan** [comment]
Regarding your question about TOC, take a look at
https://orgmode.org/manual/Table-of-Contents.html.  That page says,

Org normally inserts the table of contents directly before the first
headline of the file. To move the table of contents to a different
location, first turn off the default with org-export-with-toc variable or
with ‘#+OPTIONS: toc:nil’. Then insert ‘#+TOC: headlines N’ at the desired
location(s).


#+OPTIONS: toc:nil


...


#+TOC: headlines 2

**Comment by apiraino** [comment]
ah thank you so much, it makes sense to use the Orgmode features.

Closing this.
