### ISSUE TITLE
Equation of accented symbol not shown correctly

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#85]
I am using mathtoweb.jar:

    (setq org-latex-to-mathml-convert-command
        "java -jar %j -unicode -force -df %o %I"
        org-latex-to-mathml-jar-file
        "path_to/mathtoweb.jar")

An example is:

    \begin{equation*}
        \bar{a} \dot{a}
    \end{equation*}

After exporting I get two a

**Comment by kjambunathan** [comment]
> I am using mathtoweb.jar:
> 
> ```
> (setq org-latex-to-mathml-convert-command
>     "java -jar %j -unicode -force -df %o %I"
>     org-latex-to-mathml-jar-file
>     "path_to/mathtoweb.jar")
> ```
> 
> An example is:
> 
> ```
> \begin{equation*}
>     \bar{a} \dot{a}
> \end{equation*}
> ```

With

(setq org-latex-to-mathml-convert-command "latexmlmath \"%i\" --presentationmathml=%o")

there is a slight improvement. 

I see a bar and dot.  But they are NOT right above the  a.   I am not much familiar with mathml etc.  May be we could use some other converter.  For example,  http://asciimath.org/ (https://github.com/asciidoctor/asciimath)--atleast the web interface--renders the equation as expected.

May be you can try using asciimath's mathml converter and  see if that helps.

**Comment by QiangF** [comment]
Can you please add support for latex2mathml? :-)
https://github.com/roniemartinez/latex2mathml

**Comment by kjambunathan** [comment]
> Can you please add support for latex2mathml? :-)
> https://github.com/roniemartinez/latex2mathml

It is just a matter of changing the `org-latex-to-mathml-convert-command`.


For [latex2mathml](https://github.com/roniemartinez/latex2mathml), you can use

    (setq org-latex-to-mathml-convert-command "latex2mathml -f %I > %o")


For [texmath](https://github.com/jgm/texmath), you can use 

    (setq  org-latex-to-mathml-convert-command "texmath -f tex -t mathml %I > %o")

**Comment by kjambunathan** [comment]
mathtoweb seems to have moved here https://sourceforge.net/projects/mathtoweb/files/mathtoweb_ver_400/

**Comment by QiangF** [comment]
The output mathml of mathtoweb is displayed correctly in firefox, I think mathtoweb is still the best portable solution. The issue happens during the conversion of mathml to libreoffice starmath.
[dota.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/6522742/dota.zip)

**Comment by QiangF** [comment]
Actually it's caused by libreoffice inability to process mathml.
https://bugs.documentfoundation.org/show_bug.cgi?id=47414

**Comment by kjambunathan** [comment]
> \begin{equation*}
>     \bar{a} \dot{a}
> \end{equation*}

> After exporting I get two a

Ok.  I am experimenting with adding support for starmath fragments in the ODT exporter.    Try the following fragment.  Instructions are right in the example.  I also include a screenshot of the exported file.



```
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:mark c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Suport for =starmath= formulae in ODT exporter
#+date: <2021-05-22 Sat>
#+author: Jambunathan K
#+email: kjambunathan@debian
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.0.50 (Org mode 9.3.7)

#+options: tex:t
#+description:
#+keywords:
#+subtitle:
# #+odt_preferred_output_format: png
#+odt_styles_file:
#+odt_extra_images:
#+odt_extra_styles:
#+odt_extra_automatic_styles:
#+odt_master_styles:
#+odt_content_template_file:
#+odt_automatic_styles:
#+odt_display_outline_level: 2
#+odt_endnote_regexp: ^$
#+bib_file:


* How do I enable =starmath= support?

ODT exporter supports starmath fragments.  To get =starmath= support,
install the following advice in your =.emacs=.

#+begin_src emacs-lisp
  (advice-add 'org-create-math-formula :override
	      'org-create-math-formula-from-starmath)
#+end_src

** How do I increase the size of a math formula?

For changing the size of the formula, see 

[[https://ask.libreoffice.org/en/question/138143/how-to-increase-the-font-size-of-the-equation-in-libreoffice-impress/][How
to increase the font size of the equation in LibreOffice impress
[closed] - Ask LibreOffice]]

#+CAPTION: Equation written in starmath
\begin{equation}
{ dot a overline {a}   }
\end{equation}

----------------

Now a larger formula ...

#+CAPTION: Above equation but in twice the size
\begin{equation}
size*2{ { dot a overline {a}   }}
\end{equation}

----------------

Now it is even larger ...

#+CAPTION: Above equation but thrice the size
\begin{equation}
size*3{ { dot a overline {a}   }}
\end{equation}

* How do I disable =starmath= support

To swith back to regular latex fragments, add this to your =.emacs=.

#+begin_src emacs-lisp
  (advice-remove 'org-create-math-formula
		 'org-create-math-formula-from-starmath)
#+end_src

```

![starmath](https://user-images.githubusercontent.com/19869864/119222406-e07c1b00-bb11-11eb-962a-72158d45033e.png)

**Comment by kjambunathan** [comment]
Forgot to mention this.  You need to install the elisp functions in https://github.com/kjambunathan/org-mode-ox-odt/issues/87

**Comment by kjambunathan** [comment]
> It is just a matter of changing the `org-latex-to-mathml-convert-command`.
> 
> For [texmath](https://github.com/jgm/texmath), you can use
> 
> ```
> (setq org-latex-to-mathml-convert-command "latex2mathml -f %I > %o")
> ```
> 
> For [latex2mathml](https://github.com/roniemartinez/latex2mathml), you can use
> 
> ```
> (setq  org-latex-to-mathml-convert-command "texmath -f tex -t mathml %I > %o")
> ```

@dlukes, I am tagging you here because I happened to see your message [Using pandoc to convert LaTeX math to MathML](https://lists.gnu.org/archive/html/emacs-orgmode/2022-03/msg00002.html)

>  `(setqorg-latex-to-mathml-convert-command "pandoc -f latex -t html5 --mathml%I -o %o")' 

I believe, the `pandoc` command uses `texmath` internally.  Note that both `pandoc` and `texmath` are by the same author.  May be it is `texmath` that you should be recommending ....

**Comment by dlukes** [comment]
Taking a look at [the readme](https://github.com/jgm/texmath), it seems that `texmath` is primarily meant as a library (for use within `pandoc`): "By default, only the Haskell library is installed. To install a test program, texmath, use the executable Cabal flag". Plus unlike `pandoc`, there aren't any prebuilt binaries, which makes installation complicated.

You're right that it would be a leaner, more focused tool to recommend (and thanks for making me aware of it -- I had no idea this component of `pandoc` was available separately). But the whole point of recommending `pandoc` for this purpose is that it's by far the most versatile and therefore ubiquitous tool of all those mentioned. It's widely available and easy to install, and what's more, people are already likely to have it installed -- unlike the other ones.
