### ISSUE TITLE
Bug: ODT export of Chinese text inserts spaces for line breaks

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#89]
https://lists.gnu.org/archive/html/emacs-orgmode/2021-06/msg00579.html

Consider the following org document.

```
* Test
1本人不想亲自拿到学历学位证书、急于离校者,可书面委托他人代领学历学位证
书,29日起即可离校;2本人想亲自领取学历学位证书者,按学校规定的程序及有关
要求办理离校手续,领取相关证书后离校;
```

This was produced by pasting in a single, long line, and then using alt-Q (a 
normal thing to do, and good for readability, because org-mode doesn't wrap 
lines by default).

Exporting to ODT produces the following (body text, omitting titles, headers 
and such).

```
1本人不想亲自拿到学历学位证书、急于离校者,可书面委托他人代领学历学位证 书,29日起即可离校;2本人想亲自领取学历学位证书者,按学校规定的程序及有关 
要求办理离校手续,领取相关证书后离校;
```

Between 证 and 书, and between 关 and 要, there is a space. Chinese typography does 
not allow for spaces mid-sentence.

So, it would make sense to add a rule to the exporter: if one of the characters 
before or after a source-text line break is a Chinese, Japanese or Korean 
character, do not add a space. (The space is valid, of course, if the 
characters on either side of the line breaks are Roman or [I would guess] 
Cyrillic as well.)

(Side note: Exporting to a LaTeX buffer shows that the line breaks have been 
copied into the .tex document as is -- but, provided that you have a 
`usepackage{xeCJK}` in the preamble, LaTeX produces correct, space-free output. 
So -- Org "gets away with it" because of LaTeX's handling of CJK text. It seems 
for ODT, Org needs to handle the spacing within its own logic.)

This is org 9.1.9... bit old, I know, but I'm gonna take a wild guess that this 
has not been a high-visibility issue.

------------

You can try the below config :-)

```elisp
(defun eh-org-wash-text (text backend _info)
  "导出 org file 时，删除中文之间不必要的空格。"
  (when (or (org-export-derived-backend-p backend 'html)
            (org-export-derived-backend-p backend 'odt))
    (let ((regexp "[[:multibyte:]]")
          (string text))
      ;; org-mode 默认将一个换行符转换为空格，但中文不需要这个空格，删除。
      (setq string
            (replace-regexp-in-string
             (format "\\(%s\\) *\n *\\(%s\\)" regexp regexp)
             "\\1\\2" string))
      ;; 删除粗体之后的空格
      (dolist (str '("</b>" "</code>" "</del>" "</i>"))
        (setq string
              (replace-regexp-in-string
               (format "\\(%s\\)\\(%s\\)[ ]+\\(%s\\)" regexp str regexp)
               "\\1\\2\\3" string)))
      ;; 删除粗体之前的空格
      (dolist (str '("<b>" "<code>" "<del>" "<i>" "<span class=\"underline\">"))
        (setq string
              (replace-regexp-in-string
               (format "\\(%s\\)[ ]+\\(%s\\)\\(%s\\)" regexp str regexp)
               "\\1\\2\\3" string)))
      string)))

(add-hook 'org-export-filter-headline-functions #'eh-org-wash-text)
(add-hook 'org-export-filter-paragraph-functions #'eh-org-wash-text)
```

-------

Notice that [[:multibyte:]] means almost any non-ASCII script, e.g. Cyrillic:

```elisp
(let ((sample "abc абв def"))
  (and (string-match "[[:multibyte:]]\+" sample)
       (match-string 0 sample)))
"абв"
```

It seems, `org-fill-paragraph' M-q is smart enough to avoid a space before or after a CJK character, so it is possible to determine correct way to splice lines, despite e.g. "Script" Unicode property is not exposed to elisp: https://www.gnu.org/software/emacs/manual/html_node/elisp/Character-Properties.html (Anyway maintaining explicit list of scripts is not a straightforward approach.)

P.S.

JavaScript in browsers allows to filter characters that belong to particular script:

```
"abc абв def".match(/\p{Script=Cyrillic}+/u)
Array [ "абв" ]
```

I have not found such feature in regular expressions available in Emacs.

------------

There are a few ways to approach this:

```
(aref char-script-table ?中) -> 'han

(string-match-p "\\cc" "中") -> 0

(aref (char-category-set ?中) ?|) -> t
```

------

Confirmed: newlines are copied to ODT document as is and they appear as spaces in libreoffice. I did not tried HTML since I am unsure if browsers should glue paragraphs with newlines into continuous string without spaces. Maybe it is necessary to add some attributes for proper representation (e.g. "lang"), however "#+LANGUAGE: cn" does not help even though libreoffice considers paragraph as Chinese. 

Thank you. I have not noticed all features hidden behind \c. I believe,

    (rx (category can-break))

is more readable and I am a bit surprised that there is no descriptive aliases char-categories such as ?|. Just to add another example:

```
    (category-set-mnemonics (char-category-set ?ф)) -> ".LYchjy"
```

and `describe-categories' to decipher it.

As to splicing lines, I found `fill-delete-newlines' that uses `fill-nospace-between-words-table' besides ?| category to determine whether space should be suppressed while splicing lines. In addition there are some variables to tune behavior.

**Comment by kjambunathan** [comment]
@QiangF , I can't read/understand chinese.   Can you read Chinese? Can you help me understand what the issue is? Is the issue with the ODT exporter or is it with the core exporter?  Or may be it is a issue with the way filling happens in Chinese text?

**Comment by QiangF** [comment]
Yes, I can read Chinese. This issue perhaps is due to paragraph filling that add extra spaces to Chinese text. Chinese words don't need to be seperated with spaces, to express the same infomation, a paragraph in Chinese is often much shorter than in English, so it's great for saving papers.

I am already using the fix proposed by tumashu and I don't think we need any extra fix in your odt exporter.

**Comment by kjambunathan** [comment]
> I am already using the fix proposed by tumashu and I don't think we need any extra fix in your odt exporter.

Ok. Thanks for the help.
