### ISSUE TITLE
Support for List Tables in LaTeX export

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#92]
### Support for List Tables in LaTeX export

Continutation of discussion from See https://github.com/kjambunathan/org-mode-ox-odt/issues/91#issuecomment-877929487.  This bug is specifically to discuss support for  list tables in LaTeX export.  This feature was requested by @ouboub

**Comment by kjambunathan** [comment]
Hello @ouboub,  I have pushed a fix for supporting  list tables in LaTeX export.   See commit log and diff for details.  You can use this issue for noting down any LaTeX-related issues that you may run into.

**Comment by kjambunathan** [comment]
Please upgrade to elpa/ox-odt-9.3.7.323.tar.  This has support for list tables in LaTeX.

**Comment by ouboub** [comment]
thanks a lot, I will do this right now
