### ISSUE TITLE
Add support for image rotation

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#96]
In libreoffice, an image can be rotated 90 degrees right, 90 degrees left or 180 degrees.

**Comment by kjambunathan** [comment]
> In libreoffice, an image can be rotated 90 degrees right, 90 degrees left or 180 degrees

The required change on XML side is very small.

```xml
<draw:frame ... draw:transform="rotate (1.57)"><draw:image .../> </draw:frame>
```

Introducing this change cleanly will require significant amount of refactoring.  I don' want to disturb the existing code too much for a feature which will get occasional use.  

That said, having an ability to rotate the image could be useful in general.  I will keep this request in mind when I get to refactor the code.

In summary, I will accept this enhancement ... but I am unlikely to work on it anytime sooner.

**Comment by kjambunathan** [comment]
You may find it easier to use Org Babel, and have `imagemagick` do the rotate/conversion for you. 


For example,


```
#+name: rotate-image
#+begin_src emacs-lisp :var in-file="" :var angle=90 :results value raw :exports results
(if (string= in-file "") ""
  (let ((im-in-options (format "-rotate %d" angle))
	(out-file (format "%s-rotated-%.0f.%s" (file-name-sans-extension in-file) angle (file-name-extension in-file)))
	(im-out-options ""))
    (shell-command (mapconcat #'identity
		    (list "convert"
			  im-in-options
			  in-file
			  im-out-options
			  out-file)
		    " "))
    (format "[[file:%s]]" out-file)))
#+end_src

#+name: org-mode-unicorn-90
#+CALL: rotate-image(in-file="org-mode-unicorn.png", angle=90)

#+name: org-mode-unicorn-180
#+CALL: rotate-image(in-file="org-mode-unicorn.png", angle=180)

Some text.

#+CAPTION: Rotated by 90
#+RESULTS: org-mode-unicorn-90

More text.

#+ATTR_ODT: :scale 0.5
#+CAPTION: Rotated by 180 and Scaled to Half the Size
#+RESULTS: org-mode-unicorn-180

More and  more text


```


![Screenshot from 2021-09-04 14-04-17](https://user-images.githubusercontent.com/19869864/132088451-ae206f25-1286-43ca-b4f6-8be614d02bda.png)

**Comment by QiangF** [comment]
That's a nice tip. Thank you!

**Comment by kjambunathan** [comment]
> The required change on XML side is very small.
> 
> ```
> <draw:frame ... draw:transform="rotate (1.57)"><draw:image .../> </draw:frame>
> ```
> 
> Introducing this change cleanly will require significant amount of refactoring. I don' want to disturb the existing code too much for a feature which will get occasional use.
> 
> That said, having an ability to rotate the image could be useful in general. I will keep this request in mind when I get to refactor the code.
> 
> In summary, I will accept this enhancement ... but I am unlikely to work on it anytime sooner.

To get this

![Screenshot from 2021-10-19 07-18-40](https://user-images.githubusercontent.com/19869864/137830447-bd7b3545-4c23-4b64-b652-1d1111e28253.png)


do this

```org
#+CAPTION: Image Rotation
#+ATTR_ODT: :list-table t
- 
  -
    #+ATTR_ODT: :width 3
    [[./org-mode-unicorn.png]]
  -
    #+ATTR_ODT: :width 3
    #+CAPTION: Rotated by 180°
    #+ATTR_ODT: :inner-frame (extra "draw:transform=\"rotate (3.14)\"")
    [[./org-mode-unicorn.png]]
  -
     #+ATTR_ODT: :width 3
     #+CAPTION: Rotated by 90°
     #+ATTR_ODT: :inner-frame (extra "draw:transform=\"rotate (1.57)\"")
     [[./org-mode-unicorn.png]]
  - 
     #+ATTR_ODT: :width 3
     #+CAPTION: Rotated by 45°
     #+ATTR_ODT: :inner-frame (extra "draw:transform=\"rotate (.79)\"")
     [[./org-mode-unicorn.png]]
```

**Comment by QiangF** [comment]
Amazing, those property keywords are really powerful.
