### ISSUE TITLE
make page break before body text style attribute specification work for heading

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#97]
The two recommended way for adding pagebreak are :

1. insert page break before heading

    \* heading
    :properties:
    :attr_odt: :page-break t
    `:end:`

2. insert page break before body text

    `# slide-tag`
    #+attr_odt: :page-break "before"
    body text

Properties drawer can't be piled up, and attr_odt can, like this:

    :attr_odt: :style body
    :attr_odt: :page-break t
    body text

so No. 2 in the above list works better with user snippets.

Currently I am using odt document with page aspect ratio of a odp slide to make presentations. I work on one slide at a time. I use a slide-tag to seperate each slide. I need a unified way to add a pagebreak before the current slide, so that when the whole document is exported, the slide looks exactly the same as the slide when exported seperately. That's the use case for this feature request.

There still remains one problem: empty pages betweeen slide, because some page breaks before slide is unnecessary, but we didn 't know untill the whole document is rendered in libreoffice. 

Below is some elisp code to make viewing the current slide easier.

    (defun my-org-odt-export-to-odt ()
    (let ((file-name))
        (if global-so-long-mode
            (progn
            (so-long-disable)
            (setq file-name (org-odt-export-to-odt))
            (so-long-enable))
            (setq file-name (org-odt-export-to-odt)))
        (call-process "soffice" nil 0 nil file-name "macro:///OrgMode.Utilities.SilentlyReload")
        file-name))

```
   (require 'cl)
   (defun my-org-odt-export-slide ()
     (interactive)
     ;; export content under the current slide tag
     (save-excursion
       (let* ((temp-buffer (generate-new-buffer "odt-temp"))
              (slide-tag "^# slide-tag")
              (current-slide-end (if (re-search-forward slide-tag nil 'move)
                                     (line-beginning-position)
                                     (point)))
              (current-slide-start (progn
                                     (beginning-of-line)
                                     (re-search-backward slide-tag nil 'move)
                                     (point)))
              (cover-end (progn (goto-char 1)
                                (if (re-search-forward slide-tag nil 'move)
                                    (line-beginning-position)
                                    (point))))
              (cover (buffer-substring-no-properties 1 cover-end))
              (current-slide (buffer-substring-no-properties current-slide-start current-slide-end)))
         (if (<= cover-end current-slide-start)
             (flet ((buffer-file-name (&optional BUFFER) 
                      (concat default-directory "temp.org")))
               (with-current-buffer temp-buffer
                 (insert cover)
                 (insert current-slide)
                 (my-org-odt-export-to-odt)))
             (my-org-odt-export-to-odt)))))
```

**Comment by QiangF** [comment]
I find a forum link that might offer a solution to remove blank pages

https://forum.aspose.com/t/remove-all-blank-or-empty-pages-from-word-document-c-net/226093

    MS Word or LibreOffice/OpenOffice documents are not fixed page formats; they are flow formats more like HTML files. Examples of MS Word documents are DOCX, DOTX, RTF, DOC etc. And OpenOffice can work with these file formats ODT, OTT, XML etc. So, there is no concept of Page in MS Word document and Pages are created on the fly when you open a Word document with MS Word or OpenOffice applications. Also, there is no easy way to programmatically determine where a Page starts or ends and no easy way to determine whether some particular Page is blank or empty. One way to achieve this is to split Word document into smaller one-Page Word documents and check if those one-Page documents have content or not. Then concatenate or merge non-empty documents again into one Word document.

**Comment by kjambunathan** [comment]
I have trouble understanding your requirements.   

I suggest that you upload a zip file to this issue that has all the following information:

1. A simple `.org`  file that you use for creating slides.
2. The problematic `.odt` file that is created by the ODT exporter
3. The "desired" `.odt` file that you create with your snippets.

Once I look at the `.org` file and `.odt` file I will be able to help you better.

Don't forget to include the relevant ODT styles in the `.org` file ...

**Comment by kjambunathan** [comment]
You opened the "same" issue here https://github.com/kjambunathan/org-mode-ox-odt/issues/46.  I added page break feature in response to that issue.    

Please consider uploading a zip file with minimal working example ....

**Comment by QiangF** [comment]
Sorry for making it looks confusing. Please ignore my remarks above. The feature request is about making the following pattern work:

```
    #+attr_odt: :page-break "before"
    * This is a heading with a pagebreak before
    Body text.
```

**Comment by QiangF** [comment]
Please see an example in the attachment.
[Uploading example.zip…]()

**Comment by kjambunathan** [comment]
I see no issue with the exporter.  The problem is with the styes you are using.  You should use proper header (instead of trying to shove the heading in to page header).  The attached zip file gives an indication of how you can approach the design of your slides.  Start with `example.diff` in the attached `zip` file.  

These are the changes

1.  Use the second level heading as page header
2. Hide level1 and level2 headings.  They also have a pagebreak before them
3. Use an "empty" level2 headngs for slides that don't have a title.

For the sake of simplicity, I have ignored TOC etc.

I am including the `diff` file verbatim here, so that the search engines can index it's contents.



[example-v1.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/7224413/example-v1.zip)


```
diff --git a/example.org b/example.org
index 7956c97..16674da 100644
--- a/example.org
+++ b/example.org
@@ -1,3 +1,5 @@
+#+odt_preferred_output_format: pdf
+
 #+odt_extra_images: backgrounds/Cover.png
 #+odt_extra_images: backgrounds/Standard.png
 #+odt_extra_images: backgrounds/Epilogue.png
@@ -13,6 +15,32 @@
 #+odt_styles_file: ./styles/presentation_cn_big.xml
 #+odt_content_template_file: ./styles/default_template.xml
 
+#+odt_extra_styles: <style:style style:name="SlideHeader" style:family="paragraph" style:parent-style-name="Header_20_and_20_Footer" style:class="extra">
+#+odt_extra_styles:  <style:paragraph-properties fo:text-align="center" style:justify-single-word="false" text:number-lines="false" text:line-number="0">
+#+odt_extra_styles:   <style:tab-stops>
+#+odt_extra_styles:    <style:tab-stop style:position="8.5cm" style:type="center"/>
+#+odt_extra_styles:    <style:tab-stop style:position="17cm" style:type="right"/>
+#+odt_extra_styles:   </style:tab-stops>
+#+odt_extra_styles:  </style:paragraph-properties>
+#+odt_extra_styles:  <style:text-properties fo:font-size="24pt" fo:font-weight="bold"/>
+#+odt_extra_styles: </style:style>
+
+#+odt_extra_styles: <style:style style:name="Heading_20_1_20_unnumbered_20_with_20_pagebreak" style:display-name="Heading 1 unnumbered with pagebreak" style:family="paragraph" style:parent-style-name="Heading_20_1_unnumbered" style:master-page-name="">
+#+odt_extra_styles:  <style:paragraph-properties style:page-number="auto" fo:break-before="page"/>
+#+odt_extra_styles: </style:style>
+
+#+odt_extra_styles: <style:style style:name="Heading_20_1_20_unnumbered_20_with_20_pagebreak_20_and_20_hidden" style:display-name="Heading 1 unnumbered with pagebreak and hidden" style:family="paragraph" style:parent-style-name="Heading_20_1_20_unnumbered_20_with_20_pagebreak">
+#+odt_extra_styles:  <style:text-properties text:display="none"/>
+#+odt_extra_styles: </style:style>
+
+#+odt_extra_styles: <style:style style:name="Heading_20_2_20_unnumbered_20_with_20_pagebreak" style:display-name="Heading 2 unnumbered with pagebreak" style:family="paragraph" style:parent-style-name="Heading_20_2_unnumbered" style:master-page-name="">
+#+odt_extra_styles:  <style:paragraph-properties style:page-number="auto" fo:break-before="page"/>
+#+odt_extra_styles: </style:style>
+
+#+odt_extra_styles: <style:style style:name="Heading_20_2_20_unnumbered_20_with_20_pagebreak_20_and_20_hidden" style:display-name="Heading 2 unnumbered with pagebreak and hidden" style:family="paragraph" style:parent-style-name="Heading_20_2_20_unnumbered_20_with_20_pagebreak">
+#+odt_extra_styles:  <style:text-properties text:display="none"/>
+#+odt_extra_styles: </style:style>
+
 #+attr_odt: :style "OrgTitle"
 This is a long
 \\
@@ -25,25 +53,36 @@ Author
 #+toc: headlines 2
 
 # slide-tag
-* Heading 1
+* Slide 1
 :properties:
-:attr_odt: :page-break t
+:attr_odt: :style "Heading_20_1_20_unnumbered_20_with_20_pagebreak_20_and_20_hidden"
 :end:
 This is the first slide
 
+# ** Slide 2 without heading
+** 
+:PROPERTIES:
+:attr_odt: :style "Heading_20_1_20_unnumbered_20_with_20_pagebreak_20_and_20_hidden"
+:END:
 # slide-tag
-#+attr_odt: :page-break "before"
+# #+attr_odt: :page-break "before"
 This is a slide without a heading.
 
 # slide-tag
-* Heading 1
+* Slide 3
 :properties:
-:attr_odt: :page-break t
+:attr_odt: :style "Heading_20_1_20_unnumbered_20_with_20_pagebreak_20_and_20_hidden"
 :end:
 This is the third slide
 
+# ** Slide 4 without heading
+** 
+:PROPERTIES:
+:attr_odt: :style "Heading_20_2_20_unnumbered_20_with_20_pagebreak_20_and_20_hidden"
+:END:
+
 # slide-tag
-#+attr_odt: :page-break "before"
+# #+attr_odt: :page-break "before"
 This is the fourth slide.
 
 You see the iconsistency of specified pagebreaks befor heading and normal paragraph.
diff --git a/styles/presentation_cn_big.xml b/styles/presentation_cn_big.xml
index a4dabc4..1d86a58 100644
--- a/styles/presentation_cn_big.xml
+++ b/styles/presentation_cn_big.xml
@@ -2293,6 +2293,9 @@
     <!-- include and remove header footer in this file -->
 
     <style:master-page style:name="StandardPage" style:page-layout-name="Mpm1">
+      <style:header>
+	<text:p text:style-name="SlideHeader"><text:chapter text:display="name" text:outline-level="2">Heading 2</text:chapter></text:p>
+      </style:header>
       <style:footer>
         <text:p text:style-name="MP1"><text:page-number text:select-page="current"></text:page-number></text:p>
       </style:footer>

```

**Comment by kjambunathan** [comment]
When I exported the file to PDF, I came across a bug,  I have opened  https://bugs.documentfoundation.org/show_bug.cgi?id=144700 against LibreOffice.  You may want to keep track of this LibreOffice bug as well.

**Comment by kjambunathan** [comment]
FWIW, this is what I see in LibreOffice UI after my suggested changes.

![Screenshot from 2021-09-24 14-16-20](https://user-images.githubusercontent.com/19869864/134652943-a41076cf-d2be-4037-8d47-b77b0a7f8341.png)

**Comment by QiangF** [comment]
Thank you Sir.
I never thought about using a slide header. My approach for a slide without a heading is adding blank lines to move the text down:

    # slide-tag
    #+attr_odt: :page-break "before"
    \\
    \\
    This is a slide without a heading.

Your approach is more elegant, by using an "empty" heading for slides that don't have a title, we can see the hierarchy of the presentation easily.
However, the "empty" heading is shown in the toc, which can be seen in the above screenshot.

There are some extra steps to exclude these "empty" headings from showing in the toc. Looks like it need manual intervention and can't be automated, based on what I found on the web.

One method to exclude headings in a sub-document is to use a Table of Contents (ToC) where the entries use Create from > “Additional styles” (rather than “Outline”). By using a separate custom style for each heading in the sub-document (e.g., Heading 1 sub in place of Heading 1) these headings will then not be included in the ToC. I am not aware of any method for excluding heading inclusion in a ToC based on location within the document.
https://superuser.com/questions/1534749/exclude-certain-headings-from-numbering-in-libreoffice-writer

The exported pdf don't have black strips, but seems to have extra lines on my computer. I need to look into it further.

**Comment by QiangF** [comment]
What I see in the pdf is exactly what I see in libreoffice, all have extra gray lines around the text. Below is the pdf opened in masterpdfeditor
![img_2021_09_24__22_59_27](https://user-images.githubusercontent.com/8192731/134697046-ab5280c5-be8e-4bd2-9e17-d68378ba0744.png)

**Comment by QiangF** [comment]
This is what displayed in libreoffice:
![Uploading img_2021_09_24__23_04_32.png…]()

**Comment by QiangF** [comment]
Here is the exported pdf of the example.odt you attached on my machine
[example-exported-to-pdf-by-q.pdf](https://github.com/kjambunathan/org-mode-ox-odt/files/7226716/example-exported-to-pdf-by-q.pdf)

**Comment by QiangF** [comment]
What's I was originally proposing is to unite the ":attr_odt:" is specified, currently we use "#+attr_odt:" for normal text, and ":attr_odt:" in property drawer for headings. The issue you raised with heading that can be hidden both on the slide and in toc, is surely more important to design presentation slide with odt format. I don't care the way attr_odt is specified any more, if you can get the latter issue resovled :-)

**Comment by kjambunathan** [comment]
> Turns out we need some extra steps to exclude these "empty" headings from showing in the toc,

At https://github.com/kjambunathan/org-mode-ox-odt/blob/25a31020d87b57b2bb91e10cfb8258523e96b176/lisp/ox-odt.el#L1756, add the following see `cl-some` conditional.

Even with this change, if you 'Update' indices, then the empty headlines will come back up.  So, as long as you aren't updating the indices, the empty headlines will be stripped from TOC.  Once you produce your document, you may want to 'Protect' the TOC index from further writes.

```
diff --git a/lisp/ox-odt.el b/lisp/ox-odt.el
index 330779341..3a0f9b438 100644
--- a/lisp/ox-odt.el
+++ b/lisp/ox-odt.el
@@ -1754,12 +1754,13 @@ See `org-odt--build-date-styles' for implementation details."
     (when headlines
       (let ((toc-text (mapconcat
 		       (lambda (headline)
-			 (let* ((entry (org-odt-format-headline--wrap
-					headline backend info 'org-odt-format-toc-headline))
-				(level (org-export-get-relative-level headline info))
-				(style (format "Contents_20_%d" (- level parent-level))))
-			   (format "\n<text:p text:style-name=\"%s\">%s</text:p>"
-				   style entry)))
+			 (when (cl-some #'org-string-nw-p (org-element-property :title headline)) 
+			   (let* ((entry (org-odt-format-headline--wrap
+					  headline backend info 'org-odt-format-toc-headline))
+				  (level (org-export-get-relative-level headline info))
+				  (style (format "Contents_20_%d" (- level parent-level))))
+			     (format "\n<text:p text:style-name=\"%s\">%s</text:p>"
+				     style entry))))
 		       headlines "\n")))
 	(if (> parent-level 1) toc-text
 	  (concat (org-odt-begin-toc title depth parent-level) toc-text


```

> One method to exclude headings in a sub-document is to use a Table of Contents (ToC) where the entries use Create from > “Additional styles” (rather than “Outline”). By using a separate custom style for each heading in the sub-document (e.g., Heading 1 sub in place of Heading 1) these headings will then not be included in the ToC.


Changing the TOC template is elaborate, and I will consider implementing it ONLY IF there is a dire need .   

The easiest way of sneaking custom template would be to  add the "fixup" the toc-related XML content in styles.xml and content.xml.

**Comment by kjambunathan** [comment]
I have re-opened the bug.  Let the LibreOffice team come back with what they find.  I don't have access to Windows machine.  So, I have included you in the cc-list of the LibreOffice bug.  Hope it is ok with you.

**Comment by QiangF** [comment]
Changing the lisp code  is good enough. I am also curious on how the transparency of the background image lead to black stripe in the output pdf. Thank you for your time!
